### ISSUE TITLE
Borderlands GOTY Enhanced massive performance drop rendering particle effects

### ISSUE THREAD

**Issue by lavadrop** [doitsujin/dxvk#1012]
When playing the Island of Dr. Ned DLC, having more than 2 particle effects on screen impacts performance heavily.
I'm getting 60 fps normally, but when the games renders fire or lightning, my performance drops to 14 FPS. The issue can be triggered easily when shooting bats on the beach with a shock weapon.
I did an apitrace but apitrace makes Borderlands hang right after launching. All I could do is get Proton logs all the way to the bug.

### Software information
Borderlands GOTY Enhanced. 729040.
Custom graphics level, Borderless window, 2560*1080 60Hz, VSync On, Pause game on focus On, Framerate locking off, 16x Anisotropic filtering, FXAA on, Dynamic shadows on, Ultra shadow detail, bullet decals on, Foliage Texture and Detail High, Ambient occlusion Bloom DOF Flare outs ON, Level of detail High.

### System information
- GPU: RX 580
- Driver: DRM 3.27.0, 5.0.2-050002-generic, LLVM 9.0.0, OpenGL 4.5 (Compatibility Profile) Mesa 19.1.0-devel - padoka PPA
- Wine version: Proton 4.2-2
- DXVK version: 1.0.1

### Apitrace file(s)
- https://www.dropbox.com/s/bl0fwlpa02jdfr3/Launcher.zip
### Log files
- d3d11.log:
- dxgi.log: 
[steam-729040.zip](https://github.com/doitsujin/dxvk/files/3075656/steam-729040.zip)

**Comment by doitsujin** [comment]
And that is 100% a DXVK bug and doesn't happen on Windows?

**Comment by lavadrop** [comment]
I have no idea, I don't have Windows.
Is there any other way to get apitrace to work? I've tried running the Ubuntu repository apitrace but I can't get it to record anything.

**Comment by doitsujin** [comment]
See https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace on how to apitrace stuff. If that doesn't work, you're kind of screwed.

**Comment by lavadrop** [comment]
I did exactly that and I can't even reach the title screen.

**Comment by doitsujin** [comment]
Since you're using almost the same GPU as me you could also try RenderDoc, assuming that the game is 64-bit - just install it and put `ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%` into the Steam launch options and hit F12 as soon as the problem starts occuring, it'll then create a `.rdc` file in `/tmp/RenderDoc`.

Not quite as useful, but maybe it shows something.

**Comment by arzardk** [comment]
![image](https://user-images.githubusercontent.com/37209942/56468514-40d19780-6436-11e9-8fef-a36f73cffe97.png)
According to the [Steam](https://store.steampowered.com/app/729040/Borderlands_Game_of_the_Year_Enhanced/) this game is working on DirectX 9.0c and has nothing to do with DirectX 11/DXVK. Am I wrong?

**Comment by lavadrop** [comment]
I’ll try that

**Comment by lavadrop** [comment]
There you go.

It's a big file.

https://www.dropbox.com/s/9bpmkod71dkzzwe/wine64-preloader_2019.04.28_14.36_frame12370.rdc.gz?dl=0

Thank you!

**Comment by ErikEklund** [comment]
Seen similar issues in World of Warcraft. Windows has silky smooth 60 fps with some boss particle effect covering the screen, Wine without DXVK runs slow (30-ish I seem to remember) but major slowdown with the same effect, and DXVK runs 60 fps smooth until particle effects come and then drops to < 5 fps. All on the same hardware. I do suspect there is some dxvk-specific slowdown.

**Comment by doitsujin** [comment]
@ErikEklund Assuming that you're on RADV, does enabling `dxvk.useEarlyDiscard = True` in dxvk.conf (see wiki) help?

In general, there's absolutely nothing I can do to optimize alpha blending.

**Comment by Blisto91** [comment]
Unless the original author complains then i think this one can be closed.
I have not been able to reproduce this on my R9 380 with mesa 21.3.7. And that's even with me trying to go all the way back to dxvk 1.0.3 to test.

This game has this other issue where when i set vsync on or fps limiter below 100 i can get horrible fps drops when i move my mouse around. And even shows in game selection menu since it has vsync on i think. When i turn off vsync and set fps limiter to unlimited it seems fine ingame.
This does not happen on windows. But it also doesn't happen on windows with dxvk, so i think that is another issue.
