### ISSUE TITLE
Question: DXVK shared resources?

### ISSUE THREAD

**Issue by Kreyren** [doitsujin/dxvk#1033]
Working on https://github.com/PhoenicisOrg/scripts/issues/914 which results in 
![image](https://user-images.githubusercontent.com/11302521/56852947-69b3ca00-6919-11e9-88d8-176dd8a5ddec.png)

Was told by upstream that FiveM **won't work on linux** due DXVK missing shared resources function based on https://forum.fivem.net/t/request-fivem-linux-client/182056/3

![image](https://user-images.githubusercontent.com/11302521/56853005-1a21ce00-691a-11e9-9cd1-f6913282a499.png)

Can you confirm?

**Comment by K0bin** [comment]
#836

#899

**Comment by Guy1524** [comment]
Hello all, I made some progress on winevulkan's shared memory extension, and it now works with joshua ashton's shared-resources branch, if somebody can provide me with steps to get fiveM to the point where it needs shared-resources I can do some debugging and try to get it working.

**Comment by Tank-Missile** [comment]
@Guy1524 Just download the installer and run it inside the prefix. If you're using the steam version, run the following:

`WINEPREFIX=$HOME/.steam/steam/steamapps/compatdata/271590/pfx $HOME/.steam/steam/steamapps/common/<Proton Version>/dist/bin/wine <FiveM Installer Location>`

If you're just using the Rockstar launcher, I'm not sure where GTA V is installed to. The installer will begin updating the cache, and then the Rockstar launcher will appear and ask for your username and password. However, the launcher at this point will fail to connect to Rockstar servers. [This is because the in-game ROS request is redirected to ros.citizenfx.internal](https://github.com/citizenfx/fivem/blob/master/code/components/ros-patches-five/src/SCUIStub.cpp). A workaround to this issue is to modify your /etc/hosts file to redirect requests from ros.citizenfx.internal to 192.81.241.100 (the IP address of prod.ros.rockstargames.com). The IP address could change over time, but there's not a good way to fix that issue without redirecting ros.citizenfx.internal to prod.ros.rockstargames.com instead. However, I don't think there's a way to redirect one domain to another. Once the /etc/hosts file has been set up, the launcher will be able to connect to the Rockstar servers and start the game. At this point, FiveM crashes with a ros-patches-five.dll error.

**Comment by Kreyren** [comment]
> Hello all, I made some progress on winevulkan's shared memory extension, and it now works with joshua ashton's shared-resources branch, if somebody can provide me with steps to get fiveM to the point where it needs shared-resources I can do some debugging and try to get it working.

Could you reference the branch?

**Comment by Guy1524** [comment]
@Kreyren haven't looked at the code in ages and IDK if it still works or what quirks there are.

My branch: https://github.com/Guy1524/wine/tree/shared-resources

Josh's branch: https://github.com/Joshua-Ashton/dxvk/tree/dxvk-shared-resources

There's some modifications you have to make to Josh's work though, I forget the specifics.

**Comment by Tank-Missile** [comment]
@Guy1524 I modified tkg's scripts in order to pull from your branch and Josh's, and I was able to create a proton build from them. However, this required a patch to dll/winevulkan/vulkan.c to remove three unused classes and their corresponding code: VkImportMemoryFdInfoKHR, VkMemoryGetFdInfoKHR, and VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR. For whatever reason, you added these classes to vulkan.c, but never did anything with them. I'd like to know if you plan on working on your branch further, or if it's past you at this point.
