### ISSUE TITLE
Heavy stutters on a specific Overwatch map

### ISSUE THREAD

**Issue by ptkato** [doitsujin/dxvk#1045]
I'm running into heavy stutters while playing Overwatch and that happens only on the Horizon Lunar Colony map, it literally makes the game unplayable. All the other maps run smooth as silk, except this one.

### System information
- GPU: RX 550
- Driver: 19.0.3
- Wine version: tkg-4.6
- DXVK version: 1.1.1

I've played the same map a few wine/dxvk/mesa versions back and all had this same issue.

**Comment by tannisroot** [comment]
This is not a bug. The game has an obscene amount of shaders, and most of them seems to be on this map, which results in heavy stutter because they have to be converted and compiled before a frame can be displayed.
Just use the state ache that comes with Lutris installer and let it compile most shaders in one go first before playing the game.

**Comment by ptkato** [comment]
> Just use the state ache that comes with Lutris installer and let it compile most shaders in one go first before playing the game.

I actually did that, no matter how much I waited, it always stuttered.

**Comment by varris1** [comment]
What Tannis said. Blizzard keeps changing the shaders with every update which makes the state 
cache useless as well.

Have some patience and the stutters will be gone after some time.

**Comment by doitsujin** [comment]
Yeah, not a bug. Sorry that it's annoying, but there's not much we can do if game updates keep breaking the state cache.
