### ISSUE TITLE
Mass Effect Andromeda: Strange light effect

### ISSUE THREAD

**Issue by greencopper** [doitsujin/dxvk#1054]
In the last two releases of dxvk Mass Effect Andromeda is suffering massively from strange light effects.

![Screenshot_2019-05-14_05-09-20](https://user-images.githubusercontent.com/1302896/57668378-656cf980-7607-11e9-9066-5c00ddecc4f3.png)
![Screenshot_2019-05-14_05-10-26](https://user-images.githubusercontent.com/1302896/57668379-656cf980-7607-11e9-8599-1cd1eaebc6f7.png)
![Screenshot_2019-05-14_05-11-40](https://user-images.githubusercontent.com/1302896/57668380-66059000-7607-11e9-8130-2c79d366fd8d.png)

I normally run the game very nicely at low or even medium settings with my GTX 1050 Ti.

Log file:

[MassEffectAndromeda_d3d11.log](https://github.com/doitsujin/dxvk/files/3175683/MassEffectAndromeda_d3d11.log)
[MassEffectAndromeda_dxgi.log](https://github.com/doitsujin/dxvk/files/3175685/MassEffectAndromeda_dxgi.log)

I tried making an apitrace, but just getting to the menu at the first picture from above makes the size of the trace file more than 450MB big and it is extremely slow.

**Comment by doitsujin** [comment]
The game still works fine on my end. Is there anything special you do before the issue pops up? Which settings are you using exactly?

> but just getting to the menu at the first picture from above makes the size of the trace file more than 450MB big and it is extremely slow.

Which is unfortunately quite normal when using apitrace, nothing can be done about that.

**Comment by doitsujin** [comment]
Tested on my GTX 670 with the same driver version and no issues there either.

**Comment by greencopper** [comment]
I will try to investigate further sometime tomorrow evening and provide you with the details of my settings and also see if I can get the result of the apitrace attached to the report.

By the way, amazing work you do! Thanks a ton!

**Comment by VortexAcherontic** [comment]
What driver version are you running?
NVidias drivers are known for some missing VK capabilities with different drivers.
I once had also a bunch of VK issues just related to an older driver and because @doitsujin was not able to reproduce the issue with his NV GPU.

The 410 series for example have some missing VK extension which made some object being invisible (#847 )
At least it's the first thing pop into my head because from the bright quads shown in the last 2 screenshots I looks for me like an shader issue which could be caused by an older driver.

Also (because I don't know about your system you're running) if you have an Optimus Notebook (Intel GPU + discrete NV GPU) there might be also some incomplete VK support. (In case you're running Bumblebee I also had a lot of issues with that one on my old Notebook)

**Comment by greencopper** [comment]
I didn't have time to look further into the issue until today, but when I did the problem was gone. Prior to running Mass Effect Andromeda Nvidia and Wine was upgraded on Arch. Perhaps that somehow solved the issue.
