### ISSUE TITLE
Feature Request: support default section in config file

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#1072]
In addition to [per-app-configuration](https://github.com/doitsujin/dxvk/wiki/Configuration#per-app-configuration) could you please add `[DEFAULT]` and/or`[default]` section support?

* Would look more like INI file
  ```ini
  [DEFAULT]
  dxvk.option = true

  [app.exe]
  dxvk.option = false
  ```
* Easier to use with python's `configparser` (requires section, `default_section == "DEFAULT"`) 
  ```python
  #!/bin/env python
  
  import configparser
  
  config = configparser.ConfigParser()
  config.read('dxvk.conf')
  print('dxvk.option: ' + config['DEFAULT']['dxvk.option'])
  ```
  _At least [protonfixes](https://github.com/simons-public/protonfixes/blob/master/protonfixes/util.py#L469) using this to generate DXVK config files (and likely broken now)._

**Comment by doitsujin** [comment]
DXVK config files are no ini files and I refuse to implement anything that breaks current configuration files.

**Comment by pchome** [comment]
I don't think it should break current configuration files.

I just think that currently `[DEFAULT]` treated as a game executable named `DEFAULT`, but could be just default section. Could be either present or not.

Python is just a simple example.

**Comment by doitsujin** [comment]
I'm just asking for a **good reason** to add code which is completely useless to the way DXVK functions.

**Comment by pchome** [comment]
I understand.
Unfortunately I have no other reasons. Only those:
* users can better organize their config file, e.g. placing default options at the end of file.
* to edit a config file using INI file editor, e.g. a few more strings to python example for `zenity` support and it could be a simple GUI over dxvk.conf
  _I personally using `protonfixes`, it's the only reason I currently care about. But `protonfixes` should just add/**clean** fake sections in generated config files._
 
_The default section shouldn't be exactly named "DEFAULT", use any name you like ("general", "dxvk", ...). I suggest only a default section which don't be compared to exe._

Anyway, feel free to close this request.

**Comment by loathingKernel** [comment]
I hope you don't mind if I offer my two cents on this. I dislike the current ability to specify an exe name for localized options in a system-wide config because games can have their executables with the same names. NFS comes to mind which uses `speed.exe` as names in some titles.

A different approach to this would be config merging, i.e. setting `DXVK_CONFIG="<global_path>;<local_path>"` would iterate them sequentially and merge the configs. Configuration from the exe dir could be prefixed or suffixed depending on the merge order. I don't know how easy it would be to implement but to me it is seems like a more unified way to handle this.

That being said, I am neither for nor against said change as I am not actively using it.

**Comment by doitsujin** [comment]
I really don't get why there's so much fuss about the config file.
Here's a rule on how it should be used 99% of the time:

1. **Don't use it**.

The **only** valid reason to use the configuration file is to try out workarounds that aren't enabled by default for a given game yet, or to force-enable/disable Vsync in some games that don't have an in-game option.

The global config thing was requested because it allows Lutris scripts to enable workarounds before they make it into a DXVK release, which was a good reason to add it.

Multiple games using the same exe name are a problem, yes, but it's also an issue for the built-in workarounds which probably cannot be solved in any reasonable way. It's also fairly rare so it shouldn't be much of an issue in practice.

In any case, you can still just put a separate dxvk.conf next to the game exe and put your per-game options there. None of this is rocket science, and it shouldn't be; I just get the feeling that some of you want to *make* it rocket science for no good reason.

**Comment by Joshua-Ashton** [comment]
The global scope is just the same as the default. This is completely unnecessary.

**Comment by pchome** [comment]
> I just get the feeling that some of you want to make it rocket science for no good reason.

Not me :)

_I don't usually use nor global config, neither config in game's directory.
But that thing (protonfixes) generates temporary config file for current game, and all "rocket science" is under the hood:_
* _creates empty config_
* _merges dxvk.conf from game's directory (if any)_
* _applies additional options (if any)_
* _sets DXVK_CONFIG_FILE=/tmp/protonfixes_dxvk.conf_
* _well, keeping a "garbage" in config file, which previously was ignored by DXVK_

_Useful tool for me, even if I want to on/off Vsync. But now there is a problem. And I want to know, if proposed change **won't happen** in DXVK, then I just going to change protonfixes code._

**Comment by doitsujin** [comment]
> And I want to know, if proposed change won't happen in DXVK, then I just going to change protonfixes code.

That's probably the better solution.
