### ISSUE TITLE
Overwatch picks wrong GPU

### ISSUE THREAD

**Issue by concatime** [doitsujin/dxvk#1074]
This is neither a crash nor a rendering issue, so I do not submit a apitrace log.

### Software information
Overwatch, latest version available.

### System information
- GPU: AMD Radeon 520
- Driver: Amdgpu
- Wine version: wine-4.8 (Staging)
- DXVK version: 1.2.1

### Log files
- d3d11.log: https://gist.github.com/concatime/72bb7281f40224d1d24b26c07e6e8c1e#file-overwatch_d3d11-log
- dxgi.log: https://gist.github.com/concatime/72bb7281f40224d1d24b26c07e6e8c1e#file-overwatch_dxgi-log

When I launch Overwatch, DXVK always picks the wrong GPU. It happens only with this game.
I tried Heartstone, Heroes of the Storm, Unigine Heaven and Unigine Valley, they all launch with the discrete GPU, and not the APU.

I use Sway, wayland-based, but this happens also with X11.

![overwatch](https://user-images.githubusercontent.com/26262387/58197208-c648a180-7c99-11e9-894a-8a2a88398838.png)
![heroes_of_the_storm](https://user-images.githubusercontent.com/26262387/58197203-c3e64780-7c99-11e9-8c73-e8278958e910.png)

**Comment by doitsujin** [comment]
Not a bug. There's no such thing as a wrong GPU, and it's not DXVK's responsibility to pick a GPU but the game's, and for some reason it seems to pick your integrated one (note that the game doesn't even *know* what an integrated GPU even is).

It's still a bit weird because DXVK lists dedicated GPUs first if they are reported correctly as such by the Vulkan driver.

Anyway, check the [Device Filter](https://github.com/doitsujin/dxvk#device-filter) section on the README on how to force DXVK to only report one specific GPU to the application.

**Comment by concatime** [comment]
It was quick, and simple, thank you!
