### ISSUE TITLE
Battlefield 4, have issues going fullscreen due to DXGI Error

### ISSUE THREAD

**Issue by Alexithymia2014** [doitsujin/dxvk#1081]
I've been experiencing crash errors when Battlefield 4 goes fullscreen after clicking into it. It starts up windowed mode. The DXGI Error I receive is:
https://i.imgur.com/riAwHKr.png

I've tried all different versions of DXVK (ranging from 0.90 to 1.2.1) and Wine ranging from 3.16 to 4.9 (anything above 4.6 crashes Origin which is not related I don't think).

It looks to be related to issue #153 but I thought that was merged in and fixed?

### Software information
Battlefield 4 (and possibly 1, and V)

### System information
- GPU: AMD Radeon RX 580
- Driver: Mesa 19.0 with LLVM 8.0 but also tried mesa-git and LLVM 9.0 svn on Arch Linux
- Wine version: Tried different ones between 3.16 and 4.6 (anything above 4.6 crashes Origin)
- DXVK version: Different versions 0.90 through 1.2.1

**Comment by K0bin** [comment]
Record an apitrace so we can actually reproduce the issue.

**Comment by doitsujin** [comment]
Can you at least post the dxvk logs? Also, what are your display settings in game (resolution, refresh rate, ...)?

**Comment by Alexithymia2014** [comment]
Hi,

Thanks for the response, I ended up fully reinstalling it through Lutris and it worked fine which I found a little bizarre. The settings were 2560x1440 at 144Hz. If it happens again I'll open a new issue with an apitrace if I can figure that out with Origin running and and the d3d11 log. The d3d11 log was rather sparse when I checked it last.

**Comment by K0bin** [comment]
> The d3d11 log was rather sparse when I checked it last.

The dxgi log is the thing thats relevant here. (do post the d3d11 log as well though). And make sure its the games log, not the one created by origin.

**Comment by doitsujin** [comment]
> The settings were 2560x1440 at 144Hz.

It's possible that wine doesn't enumerate the display modes correctly; wouldn't be the first time this happens (*especially* with 144 Hz displays). Unfortunately that's not something I can fix in DXVK.

**Comment by Alexithymia2014** [comment]
I see, I regret opening this issue then! I'll keep an eye out for high refresh rates with any future games. Should I file a bug with Wine then if it doesn't already exist?

**Comment by pchome** [comment]
@doitsujin 
> Unfortunately that's not something I can fix in DXVK.

### prelude

Since [it is possible to use Wine's own DXGI implementation instead of the one provided by DXVK](https://github.com/doitsujin/dxvk/wiki/DXGI), more things going out of DXVK control, but Wine also have similar settings([via registry](https://wiki.winehq.org/Useful_Registry_Keys)).

I'm not sure if those settings can be translated directly from the `dxgi.`  configuration options, but the following ones looks like replacements:
* `VideoMemorySize` for `dxgi.maxDeviceMemory` or `dxgi.maxSharedMemory`
* `VideoPciDeviceID`/`VideoPciVendorID` for `dxgi.customDeviceId`/`dxgi.customVendorId` (`dxgi.nvapiHack`)

You could at least mentioned them on Wiki page, if it's true.

<hr>

> 144 Hz displays
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\DirectDraw]
"ForceRefreshRate"=dword:00000090
```
?
