### ISSUE TITLE
Event[0] stuck on black screen after title screen, validation errors

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#112]
### Software information
Event[0] gets stuck on a black screen after displaying the title. Validation errors printed in the console. On the black screen, HUD framerate counter continues to update, and "Failed to fast clear 62" is spammed in the console.

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21-staging
- DXVK version: git 3dea58d

### Apitrace file(s)
apitrace failed to pick up the application.

### Log files
[event0_console.log](https://github.com/doitsujin/dxvk/files/1773087/event0_console.log)
[event0_d3d11.log](https://github.com/doitsujin/dxvk/files/1773088/event0_d3d11.log)
[event0_dxgi.log](https://github.com/doitsujin/dxvk/files/1773089/event0_dxgi.log)

**Comment by exolyte** [comment]
Game is still responsive after the credit screen for me: it shows a black screen, but hovering over buttons makes them visible. Wined3d displays the menu correctly. I was able to start a new game with dxvk and the intro worked just fine, but the game did hang my GPU in the first loading screen after the intro.

GPU: RX 570
Driver: mesa-git
Wine version: 3.6
DXVK version: 4c298d4
LLVM: llvm-svn

Apitrace with dxvk since the game crashed when using wined3d together with apitrace. 
https://mega.nz/#!yE8TmA5B!8vEQSxN-0EgpDDpCbWwWk-xFwlGzkgpIIhZFSNg_qUk

**Comment by exolyte** [comment]
I just noticed that the menu renders fine with RADV_DEBUG=nofastclears so I'm guessing this is related to https://bugs.freedesktop.org/show_bug.cgi?id=106687 and https://github.com/doitsujin/dxvk/issues/289

**Comment by exolyte** [comment]
The menu issue has been fixed in latest mesa-git.

**Comment by doitsujin** [comment]
Closing, seems to be fixed.
