### ISSUE TITLE
Overwatch crashes when started with DXVK

### ISSUE THREAD

**Issue by mrsupiri** [doitsujin/dxvk#1133]
Overwatch crashes as soon as it opened when DXVK is enabled on lutris but it work fine (with low FPS) when DXVK is disabled. I tried many different DXVK versions including D9VK 0.13 and 0.11. I am running league of legends with d9vk 0.13 and getting around 110 FPS with no issue.

### Software information
Overwatch with DXVK and ESync Enable

### System information
- GPU: Nvidia GeForce MX130 (with optimus)
- Driver: 430.26
- Wine version: ge-protonified-nofshack-4.9-x86_64
- DXVK version: dxvk-1.3
- OS: Manjaro 18.0.4 KDE
- CPU: Intel core i5 i5-8250U

### Log files
- Overwatch error log: https://pastebin.com/kbBngvZy
- Lutris log: https://pastebin.com/kbBngvZy

**Comment by Askannz** [comment]
What method do you use for GPU switching ? Bumblebee, optimus-manager, or manual Prime configuration ?

**Comment by mrsupiri** [comment]
optimus-manager

**Comment by Askannz** [comment]
Since you have an Optimus laptop, make sure sure Overwatch is using the correct Vulkan ICD (right click on Overwatch in Lutris, "Configure", "System options", and set "Vulkan ICD loader" to "nvidia_icd.json". I kinda doubt that it's the issue given that Battle.net picks up the correct GPU, but doesn't hurt to check.

Also, Blizzard games require a metric ton of dependencies, make sure you have them all : https://github.com/lutris/lutris/wiki/Game:-Overwatch

**Comment by mrsupiri** [comment]
It started working with DXVK after setting the Vulkan ICD loader, before my GPU was also listed as GTX 450 but now Overwatch is detecting the right GPU too.
