### ISSUE TITLE
ME:Andromeda doesnt start with new Dxgi

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1140]
### Software information
Mass Effect Andromeda launching only with wine's Dxgi

### System information
- GPU: RX560
- Driver: Mesa RADV/ACO from AUR
- Wine version: wine-4.12.1.r18.g5d7a86d0 ( TkG Staging Esync )
- DXVK version: 1.3.1

### Log files
[MassEffectAndromeda_d3d11.log](https://github.com/doitsujin/dxvk/files/3414760/MassEffectAndromeda_d3d11.log)
[MassEffectAndromeda_dxgi.log](https://github.com/doitsujin/dxvk/files/3414761/MassEffectAndromeda_dxgi.log)
[mealog.txt](https://github.com/doitsujin/dxvk/files/3414762/mealog.txt)

**Comment by doitsujin** [comment]
Does it work if you **disable** nvapi in winecfg?

**Comment by t14462** [comment]
nvapi64 disabled - nothing changes.

**Comment by doitsujin** [comment]
Just managed to test it again and the game works fine for me.

**Comment by t14462** [comment]
It is on AMD RX, on Mesa ACO from AUR?

Hmm... Maybe it is Wine-TkG problem :-/

**Comment by aguasmenores** [comment]
Hi, I can reproduce this. DXVK 1.3.2.
DXVK's DXGI doesn't start. I have to use Wine's DXGI.
Wine staging 4.14 from Wine's repos https://wiki.winehq.org/Ubuntu.
[MassEffectAndromeda_dxgi.log](https://github.com/doitsujin/dxvk/files/3561889/MassEffectAndromeda_dxgi.log)
[MassEffectAndromeda_d3d11.log](https://github.com/doitsujin/dxvk/files/3561890/MassEffectAndromeda_d3d11.log)
[mea-console-output.txt](https://github.com/doitsujin/dxvk/files/3561891/mea-console-output.txt)



[dxvk.conf.txt](https://github.com/doitsujin/dxvk/files/3561883/dxvk.conf.txt)



![Captura de pantalla de 2019-08-31 01-59-37](https://user-images.githubusercontent.com/36234118/64056367-12598b00-cb93-11e9-9e69-f5d9a211e81e.png)

**Comment by aguasmenores** [comment]
Just a comment. With Proton 4.2, provided by Steam, the game works. But if I change in Lutris to Wine 4.14 staging, the previous error shows up.

**Comment by greencopper** [comment]
I can confirm this. Running on Arch Linux 5.3.11-arch1-1 with wine-4.20 (Staging), Nvidia 440.31 and DXVK 1.4.4. I haven't played the game since I had the strange lightning issue, so today I wanted to see if anything had changed since the upgrades both to Nvidia and DXVK.

![Screenshot_2019-11-18_17-49-05](https://user-images.githubusercontent.com/1302896/69071808-dcf26a00-0a2a-11ea-8fdf-08df88d1f716.png)

[MassEffectAndromeda_d3d11.log](https://github.com/doitsujin/dxvk/files/3859668/MassEffectAndromeda_d3d11.log)
[MassEffectAndromeda_dxgi.log](https://github.com/doitsujin/dxvk/files/3859669/MassEffectAndromeda_dxgi.log)

**Comment by doitsujin** [comment]
@greencopper can you test this commit: 9e69a610cb1fe5c7bbeef304627dadc9566f2160

**Comment by greencopper** [comment]
I'm sorry for my very late reply. I have just upgraded to 1.4.6 this evening and the problem is gone! Thank you very much for your amazing work!
