### ISSUE TITLE
DXVK with android

### ISSUE THREAD

**Issue by 13431904801** [doitsujin/dxvk#1183]
Is there anyone tried to use DXVK in android? Or Could it be used in android?

**Comment by K0bin** [comment]
Even if someone would figure out a way to make x86 software run with decent performance on ARM cpus (big if already), Android Vulkan drivers don't support the things DXVK needs and are generally very buggy.

**Comment by doitsujin** [comment]
Short answer: No.

**Comment by Kreyren** [comment]
in theory if you can use i363/amd64 arch then it should work.

I was experimenting with it on Android kernel and it was somewhat useble with few workarounds. Worse case scenario you can make Franken kernel if Android is missing functions and frontend should work on used Java.

**Comment by doitsujin** [comment]
You'd also need a capable GPU + Vulkan driver that implements the full D3D11 feature set + wine patches that allow winevulkan to work on Android + DXVK patches that allow it to work on Android (because Android really wants to be special and needs special care, just standard Vulkan probably isn't going to work).
