### ISSUE TITLE
Hitman 2 not detecting DirectX 11

### ISSUE THREAD

**Issue by WillHaRSI** [doitsujin/dxvk#1201]
Hitman 2 was updated this on 9/24 and now start up does not detect DirectX 11. 

This game is rated platinum on ProtonDb. 

Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU: AMD RX 560
- Driver: Mesa 19.2
- Wine version: Proton 4.11-6
- DXVK version: 1.4

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by skeevy420** [comment]
Are you using ACO?  

I'm in the middle of testing something else with Hitman 2 right now, but both the update came in and I was testing a patch for ACO on mesa master so I switch from mesa from git master to mesa with ACO based on a git diff patch and was thinking that was the reason for my error.  Thought it might have been due to using dxvk-ags, but that was reverted when I validated all the game files and the issue still occurred so it's very doubtful dxvk-ags is responsible.

Gonna test plain ACO in about 20 minutes (PC is busy at the moment) followed by a recompile of mesa from master and test that.

The error I'm seeing has something about GfeSDK.dll in it.  I've rebooted since seeing that and didn't get a copy/paste of my terminal output.  Sorry, thought it was related to other stuff I've been doing and didn't think it relevant to get.

**Comment by K0bin** [comment]
> The error I'm seeing has something about GfeSDK.dll in it.

Make sure Nvapi is disabled in your wine prefix. As far as I know, GfeSDK.dll is part of Nvidias Geforce Experience.

Did you change anything in the dxvk config file?

**Comment by K0bin** [comment]
The config file seems alright. I was just wondering if you had changed the vendor id to Nvidia but thats not the case.

**Comment by skeevy420** [comment]
Just tested with mesa-aco and it has the issue.  Started compiling mesa-master, waiting on the 32-bit part to finish, and about to reboot and test that.  

Tested mesa-aco with both a Proton-Tkg build from last night with dxvk from f37d4b58 (one commit after 1.4) and Proton 4.11-6 with the dxvk 1.4 they include.

**Comment by doitsujin** [comment]
This is not my bug. I don't know what they changed in the game but it just errors out for absolutely no reason; the same thing happens with wined3d.

**Comment by skeevy420** [comment]
The 2nd update didn't fix it and I tested that with both 1.3.4 and master with an up-to-date TKG Proton and 1.4 with Proton 4.11-6 and both of those with both Mesa versions.  There's a issue over at the Proton tracker as well.

What did fix it was using dxvk-ags with the header set to 5.1

**Comment by doitsujin** [comment]
> What did fix it was using dxvk-ags with the header set to 5.1

Interesting; for me the game just crashes if I do that.

**Comment by skeevy420** [comment]
aufkrawall noticed it was only working with with proton-tkg and not with Proton 4.11-6.

**Comment by doitsujin** [comment]
Turns out there was an entry point missing from my AGS DLL:
I added a missing function: https://github.com/doitsujin/dxvk-ags/commit/224dbbaa4ca8d0bedfc72e08da536e072b59740a

With the latest code, this works now.

**Comment by skeevy420** [comment]
Thanks.

**Comment by WillHaRSI** [comment]
Thanks!

**Comment by skeevy420** [comment]
Should I start an issue over at dxvk-ags for this?

That dxvk-ags update works just fine for me with proton-tkg but not with proton 4.11-6.  I'm not sure if that's an actual issue with anything here or if Tk-Glitch adds some special sauce for ags possibly making it a proton issue.
