### ISSUE TITLE
Unable to select monitors in Wow 8.2.5

### ISSUE THREAD

**Issue by devoid42** [doitsujin/dxvk#1202]
Starting with today's patch (8.2.5) the game started ONLY on the primary monitor of the system (as set by the window manager) .  Additionally the wow system configuration shows 3 monitors available erroneously ( I only have two screens).  Selecting any of the monitors in the configuration has no affect on where the game is show.  Both the monitor selections and the ability to change which screen the game was shown on worked previously.  

Unsure if they swapped out to using different API's that aren't being properly reported.

**Comment by doitsujin** [comment]
Wine doesn't really have any sort of usable multi-monitor support on X11, so DXVK currently doesn't implement it at all.

You could try this branch though: https://github.com/doitsujin/dxvk/tree/dxgi-multi-monitor
Note that this will **only** work properly if your monitors are the same model due to wine limitations.

If that doesn't work, please check if wined3d works any better, but this probably just isn't a DXVK bug.
