### ISSUE TITLE
World of Tanks rendering issues

### ISSUE THREAD

**Issue by gollum1001** [doitsujin/dxvk#1209]
- The surface tiles are not where they should be (stone is next to sand where should be only grass)
- Far away trees and grass has an red aura

# Software information
World of Tanks (reproducible with maximum and lowest graphics settings)
 
### System information
- GPU: RX 5700
- Driver: amdvlk (tested with 2019.Q3.6 from github and 19.30-855429)
- Wine version: wine-4.11
- DXVK version: 1.4.1

### Apitrace file(s)
WoT does not run without DXVK

### Log files
[WorldOfTanks_d3d11.log](https://github.com/doitsujin/dxvk/files/3667491/WorldOfTanks_d3d11.log)
[WorldOfTanks_dxgi.log](https://github.com/doitsujin/dxvk/files/3667492/WorldOfTanks_dxgi.log)

![Untitled](https://user-images.githubusercontent.com/20999314/65834467-8fd00280-e2db-11e9-8fc8-6543e9e31233.png)

**Comment by Joshua-Ashton** [comment]
Have you tested RADV?
I think it's functional for Navi on latest master but I could be wrong there.

**Comment by doitsujin** [comment]
Driver bug.

**Comment by gollum1001** [comment]
Trying with RADV was the first thing I did but it didn't even initialize.
I'm currently trying to get a capture under Windows.
Windows with native DirectX works fine but Windows with dxvk gives the same artefacts, so its must be an dxvk or an OS-independent AMD bug.

**Comment by doitsujin** [comment]
> Trying with RADV was the first thing I did but it didn't even initialize.
What exactly do you mean by that, and were you running mesa-git? Mesa 19.1 obviously doesn't have any sort of Navi support (and I'm not sure if it made it into 19.2, probably not).

AMDVLK is basically the Windows driver with a different compiler backend, so yes, shared bugs are not uncommon.

I don't consider this a DXVK bug unless someone reports the same issue with a different GPU that has better driver support.

**Comment by gollum1001** [comment]
I'm using Xubuntu so I have to use a ppa or compile it myself. I haven't got the Vulkan drivers from the ppas to work and I'm currently trying to compile it myself.

**Comment by gollum1001** [comment]
Works with radv. Sorry for wasting your time.

**Comment by doitsujin** [comment]
Cool; feel free to report a bug on the [AMDVLK](https://github.com/GPUOpen-Drivers/AMDVLK/issues) bug tracker.

**Comment by G-P-L** [comment]
Hi!
Not really a Navi issue, I had exactly the same problem (ground texture issues and objects in the distance have purple alpha layers which are disappearing if I go closer) with Raven Ridge (Ryzen 5 2400G/Vega11) using the AMDVLK driver, until last week... I got some updates on my Arch system one week ago (which not included AMDVLK, but there was a kernel and Mesa update I think) and since then the whole GUI has texture issues with stroboscopic glitching everywhere with this setup (see the image attached).
![2019-10-14-21-40-45](https://user-images.githubusercontent.com/23557883/66778372-bf7e2d80-eecb-11e9-948c-539a66369dad.png)
Which is sad, because otherwise DXVK+AMDVLK worked very well besides the texturing errors and because RADV has other problem in my case (but not DXVK related).

**Comment by marwonline** [comment]
> Works with radv. Sorry for wasting your time.

Just for documentation purpose: 

- make sure that you've "AMD RADV" installed . `vulkaninfo | grep "GPU id"`  

- use RADV via environment variable when starting wine: `DXVK_FILTER_DEVICE_NAME="AMD RADV"`
- use environment `DXVK_HUD=full` and check if "RADV" shows as the driver when the game starts
- Enable experimental `RADV_PERFTEST=aco` if you need/want more performance.
