### ISSUE TITLE
So perhaps we could get a solution visual studio build?

### ISSUE THREAD

**Issue by LethalManBoob** [doitsujin/dxvk#1281]
Would love to use this but im way past done hunting down software for each git, no disrespect to you of course.

**Comment by Joshua-Ashton** [comment]
MinGW builds can be found at https://git.froggi.es/doitsujin/dxvk/-/jobs for every commit (as of recently)

As for compiling with Visual Studio, just use `meson --backend vs2019 --buildtype release build` in a Visual Studio command prompt to generate solution files.

**Comment by doitsujin** [comment]
What Josh said, meson can generate that automatically. I do not intend to provide a solution for what amounts to probably 25 different Visual Studio versions within less than a year.

**Comment by LethalManBoob** [comment]
(i put the files in the mentioned directory) C:\Users\user\source\repos>meson --backend vs2019 --buildtype release build
'meson' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Joshua-Ashton** [comment]
Installing meson might be a good idea.

**Comment by Joshua-Ashton** [comment]
Can this be closed?

**Comment by doitsujin** [comment]
Yes.

**Comment by bo3b** [comment]
Adding some detail in the very unlikely case that someone else runs across this. Or maybe me, 2 years from now when I've forgotten what I did to get this working.

Using `meson --backend vs2019 --buildtype release build` works as described, with a few gotchas.

- You need to install the [meson build system](https://github.com/mesonbuild/meson/releases), and also need the [glslang tool](https://github.com/KhronosGroup/glslang/releases). It's also sufficient to just cmake the glslang tool and target the install where you can add it to the path.
- If you want to build for x64, you need to run the x64 version of the [VS command prompt](https://learn.microsoft.com/en-us/cpp/build/how-to-enable-a-64-bit-visual-cpp-toolset-on-the-command-line?view=msvc-170). By default it is a 32 bit environment and will only create an x86 target.
- The d3d8 build fails to build. It cannot find the d3d8.h header file, and after being provided that from `include/native/directx/` it has some other missing reference, so unless you need to work out the details, disable it in the configuration.
- You cannot easily build to vs2017 as a target, because you need a C++17 compliant compiler.
