### ISSUE TITLE
More games to add d3d9.deferSurfaceCreation = True

### ISSUE THREAD

**Issue by BillFleming** [doitsujin/dxvk#1287]
Frogs,

I have confirmed with the newly merged v1.5 the following game exes that also need d3d9.deferSurfaceCreation = True to become playable.
Will add more games to the list if I find them.

- Nelke_and_the_Legendary_Alchemists.exe
- Atelier_Lulua.exe

:frog:

**Comment by doitsujin** [comment]
There's already a discussion going on about that [here](https://github.com/doitsujin/dxvk/commit/9be0bf95ca5667b8b7078211a972ffd7fff5d330), please continue there.

I'll add these, but I'd like to have a more or less complete list of affected games rather than having dozens of commits adding each one individually.

**Comment by doitsujin** [comment]
Fixed as of eed57ed6c4a01443ea22882037bb8b3f9b8296c6.
