### ISSUE TITLE
Elder Scrolls Online doesn't work on latest AMDVLK (Vulkan 1.1)

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#133]
The window freezes without showing anything, it seems the process hangs...

d3d11-triangles.exe works, though.

The logs don't seem to provide anything meaningful...

d3d11.log:

```
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11Device::QueryInterface: Unknown interface query
warn:  6543dbb6-1b48-42f5-ab82-e97ec74326f6
```
dxgi.log:

```
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_AMD_rasterization_order
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxgiFactory::MakeWindowAssociation: Ignoring flags
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
```

It could be a bug on their side too.

**Comment by schtufbox** [comment]
After reading this, and having literally just updated Nvidia driver due to new vulkan update, I thought I'd better test ESO with Nvidia on vulkan 1.1, not seeing the above issue, so not affecting ESO if you're using nvidia.  AMD only issue? :(

**Comment by Guy1524** [comment]
What version of wine are you on.  Remember to follow the issue template BTW

**Comment by ssorgatem** [comment]
I've tried everything from 2.21 staging to wine-vulkan 3.3 and wine-vulkan3.3.+staging3.3. Makes no difference.
@schtufbox  well, it works well on RADV. So maybe it's AMD breaking their own driver...

It could also be a Vega-specific issue. Too many of them lately.

**Comment by doitsujin** [comment]
I don't bother supporting that driver anymore because it just has way too many issues, and I recommend against using it with DXVK until the situation improves *significantly*.

With Vega you're basically screwed because RADV *also* has a bunch of nasty issues with those cards, most games won't render correctly because for some reason it randomly invalidates depth-stencil images. The same issue has been partially fixed on Polaris and earlier cards, and in case it doesn't work, the `RADV_DEBUG=nohiz` workaround still gets the job done, but I was told that this does not work at all on Vega.

**Comment by ssorgatem** [comment]
Well, AMDVLK worked well for a week... 
I guess it was too much to expect it to keep working... xD

Well, at least DXVK+mesa-git seem to work for ESO on Vega. For now, at least.
