### ISSUE TITLE
GTA: SA - Black screen upon opening the "Audio Setup" menu

### ISSUE THREAD

**Issue by guihkx** [doitsujin/dxvk#1331]
So, I've installed some GTA:SA mods to see if they'd work with Proton, and one of them apparently changes something in the "Audio Setup" menu, which makes D9VK display only a black screen when you open it. But since the menu renders just fine with wined3d, I decided to report it here.

### Software information
Grand Theft Auto: San Andreas ([downgraded](https://gtaforums.com/topic/927016-san-andreas-downgrader/) to version 1.0, [plus a few mods installed](https://i.imgur.com/sd7OKW6.png))

### System information
- GPU: GTX 660
- Driver: 440.44
- Proton: 4.11-11

### Apitrace file(s)
- https://mega.nz/#!mZMkVA6C!5S6oRGKCEBXqHAzqSBUfeLwM1F2iyW_6wuWaE35Hl4Q

### Log files
- d3d9.log: https://gist.github.com/guihkx/f53d77da1d95bb6cf2decf812ba023e3/raw/13b171b49770567973ea67b5e366d8d21c62b5c2/steam-12120.log

**Comment by doitsujin** [comment]
Is this not correct?
![Screenshot_20200110_161824](https://user-images.githubusercontent.com/25567304/72159359-7a7b7180-33bc-11ea-9f3b-2eb2cc8bae2c.png)

FWIW it looks the same with wined3d, and it also looks the same on my AMD box with both DXVK and wined3d.

**Comment by ViNi-Arco** [comment]
This black screen error is because of Widescreen Fix, I removed it in mine to test what it was causing and solved this problem, so I recommend taking it out and setting up the audio, and putting the Widescreen Fix back in.

**Comment by ViNi-Arco** [comment]
If you are going to play GTA San Andreas at 60 FPS I recommend you use this fix as it fixes a lot of problems because of the high framerate:
https://www.mixmods.com.br/2019/06/framerate-vigilante.html

**Comment by guihkx** [comment]
@doitsujin Yup, it is rendering 100% correct.

@ViNi-Arco That was it! Disabling the `wesser_widescreen` mod now makes D9VK render the menu properly.  (Btw, the mod is located at `scripts/wshps.asi`).

But like I mentioned before, wined3d renders the menu just fine, even with the mod enabled, so perhaps it's worth taking a look into this one?

Thanks for the fps fix as well!

**Comment by ViNi-Arco** [comment]
guihkx, can you help me by testing my skygfx? because in my game he presents this problem the car glass:
http://www.img.tpx.cz/uploads/GTASArefbug.png

I want to know if SkyGfx is the cause, or is incompatible with my GTASA, to install it you put the SkyGfx folder in the modloader, remove your SkyGfx temporarily for the game to use only mine.

here my skygfx:
https://drive.google.com/open?id=1ZANRoY7faRRR4E12i22G1-aZQwHtpntR

**Comment by Joshua-Ashton** [comment]
I own GTA: SA... Can you send me the widescreen mod you are using?

**Comment by ViNi-Arco** [comment]
I'm using this one that's having the same problem as his:
https://sharemods.com/574xbwkkemsj/_SA__Widescreen_Fix.7z.html

**Comment by guihkx** [comment]
@ViNi-Arco I'm seeing the same problem as you: https://i.imgur.com/uQYQV52.jpg

@Joshua-Ashton Please check out the link @ViNi-Arco provided. FYI it needs [modloader](https://www.mixmods.com.br/2015/01/SA-Modloader.html) to work, and I'm not entirely sure if you'd have to downgrade your GTA:SA to version 1.0, like I did. To downgrade it I've used [this tool](https://gtaforums.com/topic/927016-san-andreas-downgrader/). You can run it with wine, but you need to install .NET 4.5 first (`winetricks -q dotnet45`), and only the downgrading functionally worked for me, so installing mods using that tool probably won't work for you either)

**Comment by ViNi-Arco** [comment]
Thanks @guihkx for testing, the problem was with SkyGfx same, The Hero has released a new version that fixes this problem, see:

http://www.img.tpx.cz/uploads/GTASAglassfix01.png
http://www.img.tpx.cz/uploads/GTASAglassfix02.png
https://gtaforums.com/topic/750681-skygfx-ps2-xbox-and-mobile-graphics-for-pc/


If you want to try my SkyGfx, it's the same as the original, but with tweaks that works better than the defaults:
https://drive.google.com/open?id=1lPFiY90RpALo6l9E0c-zPf1CDjXZ5yoV

**Comment by ViNi-Arco** [comment]
@guihkx Downgrade is not necessary. I already have the gtasa1.0us version

**Comment by ViNi-Arco** [comment]
Hi Josh, how are you? This is a problem with WidescreenFix incompatibility with dxvk, I tested it a lot, and arrived at this conclusion:

With this older version of Widescreen Fix the game starts and has a black audio menu:
https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/gtasa-wshps

With the latest version of Widescreen Fix GTA SA doesn't even open:
https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/gtasa

With WineD3D it works correctly on both occasions.

**Comment by guihkx** [comment]
Hey guys.

In an attempt to make reproducing this bug an easier task to fix it, here's a "quick" guide I made:

### Background

Alright, so this bug only happens with DXVK, and only when the Widescreen Fix mod (`wshps.asi`) is enabled. Unfortunately, this mod does not work in the Steam version of GTA:SA, so a downgrade is necessary.

### Downgrading
1. Assuming you already have GTA:SA downloaded and installed via Steam, download [this RAR archive](https://mega.nz/file/5hlWyaiD#D_NcekRlHJWoABv_FWzOTvpSTTvHM48K8OyBJZLw4v8) in order to downgrade the game. [(here's where I got it)](https://gtaforums.com/topic/936600-iii-iv-various-gta-downgraders/?do=findComment&comment=1070917019)
2. Extract the RAR archive into the game's main folder.
3. Assuming you have Wine installed, open a terminal window from the game's main folder and run the following command: `wine start install.bat`
4. A Wine's command prompt window will open, and the downgrade will begin. Just wait until the window closes and you're good to go.

### Installing the Widescreen Fix mod

1. To make things easier, I've put together [this ZIP archive](https://github.com/doitsujin/dxvk/files/4504045/asi_loader%2Bwshps.zip), which contains Silent's ASI Loader and the Widescreen Fix mod. Here's the list of files and the exact location I've downloaded them:
```
asi_loader+wshps.zip
├── scripts
│   ├── global.ini
│   └── wshps.asi
├── vorbisFile.dll
└── vorbisHooked.dll
```
**global.ini**, **wshps.asi**: https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/gtasa-wshps
**vorbisFile.dll**, **vorbisHooked.dll**: https://www.gtagarage.com/mods/show.php?id=21709

The only thing you might optionally do before extracting the ZIP archive in`to the game's main folder, is backup the original `vorbisFile.dll`.

After all of that, run the game normally using Steam. Once the main menu loads, head to **Options** > **Audio Setup**. It should instantly show you a black screen (and btw, if you have `DXVK_HUD=full` set, those stats will temporarily disappear too, until you leave the menu by hitting Escape).

That's it. Any questions? Let me know.

**Comment by ViNi-Arco** [comment]
@guihkx I finally made it! now works perfectly, without any problem, see:

https://img.tpx.cz/uploads/GTASA-FiX-Audio-iMG-iSSUES-01.png

It has to be this version:
https://ci.appveyor.com/project/ThirteenAG/widescreenfixespack/builds/29792983/artifacts

As it was deleted I uploaded it here for you:
https://drive.google.com/file/d/1VRzsKZ7Igmbx4D3S5x2pUxEuftGXzPIN/view?usp=sharing

Delete your WindeScreenFix and wshps.asi so that the one I uploaded works ok ?!
It is already set up, there is no need for adjustment, it will automatically identify your monitor resolution automatically

Even if I play in 4: 3 it works perfectly, I bought a 4: 3 monitor to play old games but the WideScreenFix improves on it too see:

Without WideScreenFix:
https://img.tpx.cz/uploads/GTASA-FiX-Audio-iMG-iSSUES-02.png

With WideScreenFix:
https://img.tpx.cz/uploads/GTASA-FiX-Audio-iMG-iSSUES-03.png

**Comment by guihkx** [comment]
Unfortunately your gdrive link is private atm, but after it's fixed I'll gladly give it a try :)

Thanks

**Comment by ViNi-Arco** [comment]
out! sorry forgot to leave public now go try again

**Comment by guihkx** [comment]
Yup, using that specific version doesn't make the audio menu go black anymore. But for some odd reason, I get frame drops/stuttering if I move my mouse around in the main menu. It stops after 7~10 seconds, and Proton's log file doesn't show absolutely anything during the stuttering period...

I'm using so many plugins though, so it could be related to that. I'll do some tests using only the widescreen plugin, later.

Question: Did you bisect the widescreen plugin to find out where exactly it "breaks"? If so, I wonder if that's useful information for DXVK to implement a fix/workaround on their end.

**Comment by ViNi-Arco** [comment]
> But for some odd reason, I get frame drops/stuttering if I move my mouse around in the main menu.

I don't have this problem of fps when moving the mouse.

Do you use a gaming mouse? I've been researching a lot about this problem you are facing, and some have been "successful" by decreasing mouse polling and others using native dll's, see:
https://www.reddit.com/r/wine_gaming/comments/ehey1i/fps_drops_when_moving_mouse/
https://www.reddit.com/r/wine_gaming/comments/dzyv0v/fps_drops_when_moving_cursor_in_games/
https://www.reddit.com/r/leagueoflinux/comments/cjmrhl/low_fps_while_moving_mouse/

> I'm using so many plugins though, so it could be related to that. I'll do some tests using only the widescreen plugin, later.

There is a chance that this is the problem, because I had problems with the Project2DFX and III.VC.SA.LimitAdjuster.asi mod in the past, and managed to solve it by changing some settings, I had a performance problem with SkyGfx too and I already solved, Make GTA San Andreas working on Linux with Mods has been, let's say, complicated ... and your tests managed to find the cause of the problem?

**Comment by ViNi-Arco** [comment]
I tested it on another monitor with a higher resolution and I didn't have this problem with fps when moving the mouse.

After more tests, I manage to improve SkyGfx more to work without problems in Wine, now it has less crash chanche and better performance, download here and replace that previous version that I made available the previous link:
https://drive.google.com/file/d/1Atg7wws4ceFhKGpPALdAIkHckB2xqyYc/view?usp=sharing

**Comment by guihkx** [comment]
>Do you use a gaming mouse?

Yes I do, and the polling rate is set to 1000 Hz by default. I tried lowering it down to 500 Hz, but it didn't affect anything.

It can't be that, because I'm still able reproduce this choppiness by having only the (newer) widescreen fix enabled in modloader. It has to be related to this new version of the mod, because it doesn't happen at all with the older version. Regardless, this "mouse lagginess" happens only for a short period of time in the main menu, so it's not that big of a deal, I guess...

>After more tests, I manage to improve SkyGfx more to work without problems in Wine

I haven't actually played GTA:SA in a long while, but the majority of times it did crash for me while I was beating the game, happened during a cutscene / loading screen (e.g. leaving the safe house). But I'll replace my SkyGfx with yours, just in case 👍

**Comment by guihkx** [comment]
After revisiting and following the steps described on https://github.com/doitsujin/dxvk/issues/1331#issuecomment-616589377, I'm happy to close this one as fixed! :)

![image](https://user-images.githubusercontent.com/626206/126863464-5d3b72df-2197-420a-9389-9f3634130ff7.png)
