### ISSUE TITLE
Battlefield 3 Drivers Unknow

### ISSUE THREAD

**Issue by Alllgator343** [doitsujin/dxvk#1335]
Hello. I have a problem with launching Battlefield 3

An error pops up during level loading

Information about my system:
OS: Linux Mint 19.3
Drivers: Nvidia 440.44
Graphics card: Nvidia GTX 1050ti
DXVK: i have tried to use 1.4-1.5.1
Wine version: 3.21-5.0rc4

![Снимок экрана от 2020-01-12 17-56-10](https://user-images.githubusercontent.com/39007688/72219517-c9660a00-3568-11ea-8c9a-42fb295de06a.png)

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by Alllgator343** [comment]
> Please make an apitrace.

How can i do it?

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace

**Comment by doitsujin** [comment]
Posting log files would also be nice... there's a reason why the issue template asks for them, ignoring that just means that addressing your issue will take longer.

**Comment by K0bin** [comment]
Which level/map is crashing? Campaign? Multiplayer?

**Comment by Alllgator343** [comment]
> Posting log files would also be nice... there's a reason why the issue template asks for them, ignoring that just means that addressing your issue will take longer.
> 
> Battlefield 3 is actually known to work with DXVK so this probably isn't really a bug, but something weird on your system/wine setup (does the game need d3dx11?).

I don't know how i can create log file and apitrace file. :( Tell me please.

**Comment by loathingKernel** [comment]
> I don't know how i can create log file and apitrace file. :( Tell me please.

https://github.com/doitsujin/dxvk/issues/1335#issuecomment-573421892

**Comment by lle211967** [comment]
Hi,
try to disable the nvapi64 and/or nvapi32 Libraries in winecfg and try again.
Is a old BF 3 Bug and many other games has the same probs with nvapixx. I don't think it has anything to do with DXVK.

Hope it will help you.
All the Best :-)
lle

**Comment by SveSop** [comment]
@Alllgator343 I did a quick investigation since i happened to own the game.

BF3 seems to be using some nvapi calls (as suspected), but as lle211967 sais above you could just disable this (winecfg and set nvapi/nvcuda/nvencodeapi/nvcuvid to "Disabled") and make sure your dxvk.conf file does not set `dxgi.nvapiHack = False`

However i ran with my custom nvapi set and found BF3 used some basic querying of things like `NvAPI_GetDisplayDriverVersion`. If you are using the default wine-staging version of nvapi, this "version" will be totally off, and could possibly trigger something like this.
Other nvapi functions was querying for SLIState and Stereo (vr). It also ran `NvAPI_D3D11_SetDepthBoundsTest` and that worked quite nice.

I only tested this in "Campaign" mode, cos i did not get this to work if i tried to launch through the webbrowser. Probably not working very well with online games tho, but well.. such is the nature of anti-cheats like PunkBuster perhaps... i dunno.

Let me know if you are interested in investigating further, although i guess disabling nvapi and running with the default dxvk setting of `dxgi.nvapiHack = True` is the easiest solution. I tested this aswell, and no calls to nvapi was made, nor any error messages.

**Comment by NerosTie** [comment]
Tested on my side and I have no issue at all with BF3.

@Alllgator343 Why do you use such an old version of Wine?

**Comment by Alllgator343** [comment]
I'm sorry for the long answer. After updating the driver everything worked
