### ISSUE TITLE
The Sims 2 Ultimate (Origin) not launching through DXVK

### ISSUE THREAD

**Issue by redandvidya** [doitsujin/dxvk#1347]
Fresh install of Sims 2 (Origin edition). Origin install was fine, game install was fine, just launching it doesn't work.

The game just doesn't launch. At all. I don't know why. I reached out to @tannisroot about this issue, but he seemed very resistant to help about the fact that I used openSUSE Leap 15.1 (which btw, I don't think opinions and bias about distros should be relevant and I don't think that's good behavior for a Lutris maintainer but that's just my opinion)

Anyways, I looked in the log but it was very confusing. I can understand most logs but this one was outputting different errors so much.

### Software information
The Sims 2 Ultimate Collection (Origin)
Running on OpenSUSE Leap 15.1 with Wine and PlayOnLinux installed.

### System information
- GPU: RX 570
- Driver: Mesa 18.3.2
- Wine version: Wine-staging 5.0rc5
- DXVK version: 1.5.1 and dxvk
master.9e5e4c1cfcbc0ac5e7f89adc645a63728faffdc3

### Apitrace file(s)
I wasn't able to generate any apitrace file for some reason. There was just no file. IDK why.

### Log files
https://pastebin.com/1vQibhAw

**Comment by doitsujin** [comment]
> Driver: Mesa 18.3.2

You're running a one-year old graphics driver, please update that thing and try again.

**Comment by Joshua-Ashton** [comment]
> which btw, I don't think opinions and bias about distros should be relevant and I don't think that's good behavior for a Lutris maintainer but that's just my opinion

If something is crappy and old, then something is crappy and old. That's not my or @tannisroot's opinion, that's just fact.

If you're determined to use outdated software for absolutely no reason then you are asking for situations like this and you're better off just using WineD3D.

**Comment by Glog78** [comment]
redan if you like opensuse than you might want to give https://software.opensuse.org/distributions/tumbleweed (opensuse tumbleweed) a try. It is basically the opensuse rolling distribution which comes with very modern software. In your case the advised modern versions of mesa. 

Also there seems to be more modern versions of mesa on the opensuse build service for leap -> https://build.opensuse.org/package/show/X11:XOrg/Mesa. Since i haven't used opensuse for more than a decade now i can't exactly tell how you can easily use packages from the build server (including the required dependencies. Thats something you better asked the people over at opensuse.

**Comment by redandvidya** [comment]
Just because something is old doesn’t mean it’s crappy. I have run “bleeding edge stable” distros like Arch, (I love Arch but it has its faults) Manjaro, and Void and every single one of them have broken my installs, leaving me with a broken mess of a linux distro.
(inb4 someone says you didn’t use Arch right lmaoooo)

On the other side, for me, more stable distros like Debian, Mint, and now SUSE Leap have worked wonderfully well. So you can’t say “facts” because ultimately user experience also factors in. 

If you are going have backing from something like Valve, I think you need to factor in that people have reasons for sticking with OS’s like Windows 7, because they’re stable and they just work. Why would someone coming from Windows 10 go to something like Arch complaining about lots of updates and getting..lots of updates?

Anyways I will be updating my driver and vulkan loader and testing it again. That’s all you guys really needed to say, as there’s no need to, again, say “oh this distro is terrible because x y z” becuase ultimately we all have our tastes in operating systems, and I think we shouldn’t lash out at others for picking the distro that they want.

**Comment by redandvidya** [comment]
@Glog78 Tumbleweed seems very interesting, I’ll try it out on a different machine. Anyways I will be trying your workaround when I get home. Thank you!

**Comment by Glog78** [comment]
Don't be angry at the dev's :) They are doing a fantastic job but the stable versions or enterprice versions comes at the price that some very modern software doesn't run out of the box. In this terms dxvk and d9vk are "very modern".  But i can give you the following words -> both dxvk and d9vk are incredible in terms of compatibility and performance for gaming under wine. So even it is a hassle sometimes to get running that price pay's off easily by the experience once you have them running. I cross my fingers the the build server fixes everything else you might check for newer vulkan loader on the build server too. Sadly i can't help more because i dropped suse to long ago. Have a great time.

**Comment by doitsujin** [comment]
> If you are going have backing from something like Valve, I think you need to factor in that people have reasons for sticking with OS’s like Windows 7

If you're still using Windows 7 then firts of all you're running an *unsupported* OS, you can't run most D3D12 titles either. Either people keep their system up to date to run modern software, or they don't and have to live with the fact that some things just aren't going to work.

That said, most people on Windows 7 at least keep their drivers somewhat up to date.

Anyway, Sims 2 clearly works for the majority of users, and I think we'd rather spend our time fixing *actual* bugs and annoyances.

**Comment by Margen67** [comment]
![](https://ubuntu-is-stable.com/stable.jpg)

**Comment by redandvidya** [comment]
Welp, this is clearly a bug with DXVK. I installed the latest Mesa driver, like you said, but it still doesn't work lmao. However, I also had installed Sims 3 at that time, and when I launched the game with the D9VK launch flag (I don't think proton has 1.5 integrated yet) whaddaya know, it works. It doesn't make sense that Proton + D9VK work but VANILLA WINE and DXVK doesn't. I don't think distro choices are entirely to blame here

**Comment by TedsterTech** [comment]
> Why would someone coming from Windows 10 go to something like Arch complaining about lots of updates and getting..lots of updates?

Curious choice of argument, if I'm understanding correctly:
When Windows 10 updates, it often adds bloat, removes features, breaks things, and is often fundamentally not ready for shipping.
Running a testing or bleeding set of packages is different for they are produced with a fundamental amount of confidence they will work, and, since packages are far more modular, the effect of any particular package being bad is often far less than Windows 10, say, completely ruining webcam usage for some users or something to that degree.
It's not so much about the updates, generally, as the effect of the updates; I barely notice the changes from updates, as they are often minor improvements, additions of features, or security fixes. The idea of a 'golden master' in software is becoming more and more ridiculous as time goes on; you should probably keep your stuff relatively up-to-date if you want to use it in an up-to-date way.

**Comment by Joshua-Ashton** [comment]
> I don't think proton has 1.5 integrated yet

Proton is on 1.5.1, the exact same release as the latest right now.

I *know* The Sims 2 works on 1.5.1, it's something that gets explicitly tested by numerous people before we tag a release.

**Comment by Joshua-Ashton** [comment]
Does it even work on WineD3D for you?

**Comment by redandvidya** [comment]
@TedsterTech I was speaking from personal experience, as I’ve had many an arch update that left me with a broken mess of a system, kinda like Windows 10, which is why I said that that was comparable to W10 Updates.

**Comment by redandvidya** [comment]
@Joshua-Ashton No, it doesn’t work with WineD3D. This is vanilla wine, and TS2 has been very traditionally a hit or miss on it. I’m installing DXVK because people are telling me “Just use DXVK and Wine for TS2 it’s faster and works better” but now it’s not working, and I’m confused, and I’m now reporting the issue but people are somehow pointing to my choice of distro? I’ve seen DXVK for TS2 work for distros even older than Leap 15, (Fedora 29 and Ubuntu 18.04) So why now it isn’t working?

**Comment by redandvidya** [comment]
I’m not attacking you guys for your work on DXVK, I think it’s a wonderful project to modernize old games running on wine...but I don’t think that people should attack me as well for choosing a distro. At least SUSE Leap hasn’t given me as much of a headache.

**Comment by Glog78** [comment]
Ok i checked the package description of opensuse leap 15.1 ... i think only updating mesa isn't enough
they provide still a 1.0.65.0 of vulkan loader and validation layers .... https://software.opensuse.org/package/vulkan


DXVK needs something 1.1 .... lets check if we find one 
https://build.opensuse.org/package/show/X11:Wayland/vulkan-loader << this one works for 64bit wine on leap but not with 32bit  :/ (cause the i586) is missing

https://build.opensuse.org/package/show/openSUSE:Factory/vulkan-loader << but this are basically the development packages for leap 15.2

So i think with 15.2 there will be the needed software but all of the packages you now add by hand should be already in tumbleweed. So if i would like suse i would maybe change for tumbleweed and accept that (since it is an rolling distribtution) sometimes there might be a problem. 

Redan would it be possible if you ask the suse guys too, cause i am by no means an active or pro user in suse. Maybe there is an additional repository https://en.opensuse.org/Additional_package_repositories with up to date kernel / mesa / vulkan and so on available where you only need to add the repository and not single packages.

**Comment by redandvidya** [comment]
Thanks, that worked @Glog78
