### ISSUE TITLE
How do I turn off overlay?  (Windows 10, AMD RX 5700 XT video card)

### ISSUE THREAD

**Issue by eisberg77** [doitsujin/dxvk#1362]
Hello, 

I am getting an overlay that is showing me the driver version, Vulkan driver version, the name of my video card, and the FPS I am getting.

I am using Windows 10.  I have an AMD RX 5700 RX video card.

How do I disable this overlay?

**Comment by LordJBeckman** [comment]
More of a question than a issue but the configuration for the HUD and it's parameters are in the readme.md file on Github here for what you can set it to and as a Windows user (Yeah another one.) I just call it from a bat file.

set DXVK_HUD=0
@start "" "C:\Folder\ExeFile.exe"

Something like that.
If all works I suppose this can then be closed for bug reports and such, suppose the situation with AMD in particular and the driver situation has given a increase in Windows usage of DXVK especially recently when Sekiro was given this as some little workaround and more plus how it continues to improve performance and GPU behavior due to the problematic driver situation to try and explain it.

**Comment by doitsujin** [comment]
The HUD is disabled by default, so if it shows up, it means you enabled it somehow. Just undo that.

**Comment by doitsujin** [comment]
@LordJBeckman actually you're making it sound like it shows up for you as well. Did you set the environment variable in the Windows settings somewhere or do you have a dxvk.conf next to your game? Are you using official DXVK releases or some other builds?

This is not the first time someone asks how to disable the HUD even though **enabling it requires user action**, so I really don't have the slightest clue what's going on. Also just double-checked on Windows and I definitely don't get a HUD unless I explicitly enable it.

**Comment by LordJBeckman** [comment]
In my case I use it to enable the framerate counter so I can compare due to the ongoing problems with the 5700 / Navi GPU situation and it's behavior with adjusting the clock speeds often resulting in reduced performance.

Without anything specified the UI does not show up I was using the standard 1.5.1 release and then I also tested the latest compiled version from the link in the other issue from 1361 and nothing different there.

Outside of either setting a parameter in this way or using the options file I don't see how it could default to enabling the DXVK HUD at all unless using a earlier build if it's something that could be causing it.

Pretty certain the only way to get the driver version info and framerate would be using a value of 1 or the two separate "devinfo,fps" parameters together.

That or there's some bundled "fix" download linked to elsewhere and that includes the options file or a batch file which would also be a problem for whatever version of DXVK is being spread around and how that's bundled. Only a theory but with how popular quick fixes are it wouldn't come as much of a surprise there's some packed variant instead of just linking to the main Github repository here.

**Comment by LordJBeckman** [comment]
Main issue around Sekiro links to this Github though so it's not from that at least.
https://www.reddit.com/r/Amd/comments/ek9zvd/potential_fix_for_sekiros_performance_issues_with/

Or the little breakage AMD did with 19.12.1 until 20.1.3 yesterday for a number of Koei Tecmo titles though those always seem to have other issues as well.

Can't see any other way this would happen, defaults wouldn't change without being set to a different value and there's no way that could happen on it's own plus it's not from some other overlay or extension either.

**Comment by doitsujin** [comment]
Yeah that's kind of the point, it was actually *never* enabled by default so it's really confusing to see multiple complaints about the HUD being there by default all of the sudden, in multiple different places. Anyway, thanks for confirming.

**Comment by eisberg77** [comment]
> The HUD is disabled by default, so if it shows up, it means you enabled it somehow. Just undo that.

So what are the instructions to even turn it on?  Because I literally just downloaded the files from this github, the latest release, unpacked it, and moved the 2 directx files needed into the games install directory, and then ran the game.  I did absolutely nothing else. and its enabled.  I also have no .conf file at all next the games executable, I do have some cache file though.

**Comment by doitsujin** [comment]
It's in the README, if there's no config file then the `DXVK_HUD` environment variable might be set on your system (use google to find out how to set env vars on windows).
