### ISSUE TITLE
How to chose between DX10 and DX9 now?

### ISSUE THREAD

**Issue by Lalarian** [doitsujin/dxvk#1448]
Hello!

As long as D9VK was a seperate project I had the choice to tell Lutros which libs it should start with. So I could chose which API to use for which game.
But now after D9VK has been integrated into DXVK I do not understand, how I could manually select which one I want to use for a game.
For example I am playing Guild Wars 2.
I normally played the game in DX11, because it looked a bit better.
But sometimes I played in DX9, because it was faster, depending on the situation.

Now I am using directory that contains DXVK 1.5.4, but the game still runs in D9VK only.
How would I switch to DX11?
Thank you! :)

**Comment by doitsujin** [comment]
Guild Wars 2 does not support D3D11.

For other games, select it in the game options if possible. Which DirectX version is used isn't decided by DXVK at all.

**Comment by Lalarian** [comment]
Thank you!
I'm just asking because there was a visible difference between both APIs in
GW2. I read that it didn't support DX11, but running with DX11 the image
was much brighter and showed more shades compared to D9VK. So why did this
happen?

Am Sa., 15. Feb. 2020 um 09:50 Uhr schrieb Philip Rebohle <
notifications@github.com>:

**Comment by doitsujin** [comment]
What exactly did you *really* do? You *cannot* run the game with DX11 because the game doesn't support it.

**Comment by Lalarian** [comment]
For using D9VK I created a folder named "d9vk-versionXXX" in lutris' directory where I placed the D9VK libraries. In Lutris' options I activated "Enable DXVK" and set "DXVK version" to "d9vk-versionXXX" for making it use the D9VK libraries.
And when I didn't need the faster fps but wanted the other colors I selected "DXVK Version" as "1.5.1" from the given defaults list for making it use the DXVK library instead. The game ran using both settings, but everytime I toggles between both there was a distinctive graphical difference.

**Comment by doitsujin** [comment]
You were using wined3d then, which is wine's default OpenGL backend.

**Comment by Lalarian** [comment]
Thank you, this explains how it would run without using D9VK.
But it seems that I was using Lutris wrong then, didn't I? Could you please shortly explain this behaviour?
I would expect Wine to have loaded the dxvk libraries an output an error instead, because this game couldn't run with dx11?
Why did it not do this and run it using Wine OGL instead? Is there an automatic fallback to Wine's OGL if the selected API is not compatible?

**Comment by w-flo** [comment]
Basically, when you set lutris / proton to enable dxvk, they just make sure that DirectX9-DirectX11 is available for games to use in the version provided by dxvk instead of the default wine implementation. So dxvk replaces the default wined3d implementation if you enable that option. It is entirely up to the game whether or not the game uses any of those APIs. You could probably launch the windows calculator through Lutris and enable dxvk, but the calculator simply won't use any DirectX version at all (I guess). So libraries are only loaded on demand.

When you set Lutris to enable DirectX11 only, then all the other DirectX versions still use the default wined3d implementation, because they were not replaced to use dxvk. So in that case, DirectX9 games simply use wined3d.

**Comment by Lalarian** [comment]
Thank you very much!
I learned a bit more :)
