### ISSUE TITLE
StorageImageReadWithoutFormat should not be required for feature level 11_0

### ISSUE THREAD

**Issue by jozefkucia** [doitsujin/dxvk#150]
DXVK requires `StorageImageReadWithoutFormat` for feature 11_0 support. It shouldn't be required. Only the following 3 formats require the UAV typed load support in the 11_0 feature level: `R32_UINT`, `R32_SINT`, `R32_FLOAT`.

**Comment by doitsujin** [comment]
It might be true that this feature should technically not be required, but since there's no way to determine the *exact* UAV format accurately at compile time, I don't really see how to work around that without ruining performance at draw time.

Just assuming that a UAV with a float return type is `R32_FLOAT` when a load instruction is used sounds like an incorrect assumption.

**Comment by doitsujin** [comment]
09151f36168bad2630a3c642a8f4401a65e87ed5 should work on GPUs which do not support this capability as long as the application does not use typed loads for any other format.
