### ISSUE TITLE
Downsampling support

### ISSUE THREAD

**Issue by PeterBadzhakov** [doitsujin/dxvk#1539]
Is it possible to implement a sort of supersampling or downsampling algorithm in DXVK as found in AMD's VSR, Nvidia's DSR, GeDoSaTo, and SoTH?

**Comment by Joshua-Ashton** [comment]
This would be possible for D3D9 -- D3D11, not so much because texelFetch stuff can exist there.

**Comment by Joshua-Ashton** [comment]
(unless it was exposed as just more display modes there)

**Comment by PeterBadzhakov** [comment]
So, technically speaking, what would be the gist of it when using Vulkan?

**Comment by doitsujin** [comment]
[gamescope](https://github.com/Plagman/gamescope) already provides such functionality.

Downsampling is a **lot** more complex than just creating higher-resolution render targets, since you also need to take into account that the application will expect the window size to match, mouse input has to be remapped, etc.

**Comment by ruanformigoni** [comment]
Hi, although gamescope does downscaling, it does not provide a supersampling/downscaling algorithm [issue 692](https://github.com/Plagman/gamescope/issues/692). I've enabled FSR for supersampling [here](https://github.com/Plagman/gamescope/pull/702) (although that is not the purpose) and the results where good, however a proper supersampling algorithm would be better.
