### ISSUE TITLE
Not accurate or same colors while playing between Manjaro and Windows

### ISSUE THREAD

**Issue by hav4k** [doitsujin/dxvk#1579]
Hi.
I have problem with colors display in Manjaro:
Thought desktop 2D is fine, but when playing games through DXVK with Lutris or Steam Proton it's looks like "less brighter" than Windows 10. Why? Please, any help is apreciated.
My setup: Manjaro 19.0.2 GNOME, Nvidia 1070 Ti, last non free drivers 440.82 and Samsung S24D330H (tried HDMI and DisplayPort, with identical result).
Suggests? Thanks for reply.

**Comment by doitsujin** [comment]
Which games are you talking about?

**Comment by hav4k** [comment]
> Which games are you talking about?
> 
> This is almost guaranteed to be a setup issue on your end, like not using full RGB color space on one of the two systems (note that Nvidia **disables** full RGB by default on Windows when using HDMI, so Linux would actually be correct).

Thanks for quick reply, doitsujin. 

Happens with all my library of games, for example Homefront The Revolution (Steam Proton). I take screenshots playing with Manjaro, here:

https://ibb.co/album/btXdMF

I agree with you, for sure is a setup issue on my end but... any idea to solve it?.

Nvidia X Server Settings of Manjaro (attached image
), used with displayport to VGA adapter (not HDMI this time). And where check full RGB color settings with Windows? I dont see it...

![Captura de pantalla de 2020-04-19 01-04-58](https://user-images.githubusercontent.com/19598731/79673912-5c54b700-81de-11ea-879d-69028032aec8.png)

Greetings.

**Comment by doitsujin** [comment]
Settings seem correct :shrug: .

Anyway, please note that this isn't a support forum but an issue tracker, and unless there's some evidence that this is a bug in DXVK (you could check if using DXVK on Windows also leads to these issues) I can't really do anything here. There's probably better places to ask about it, although you'll probably have to provide more detailed info on your Windows-side setup as well.

**Comment by logan001** [comment]
just curios if you tried to take screenshots from both os and compare them on the same OS. are there any differences?. 
also if i remember correctly (i'm not on windows now) there is color profile for monitors in windows. i don't know if linux has such thing

**Comment by K0bin** [comment]
DXVK applies gamma in a different way compared to Windows. If you take a screenshot on Windows, that screenshot is not gamma adjusted while with DXVK it is.
So while the screenshots are probably gonna look different, the game on your screen will not.

We investigated this a while ago with D9VK: https://github.com/Joshua-Ashton/d9vk/issues/434

**Comment by doitsujin** [comment]
Should be noted that hardly anything (at least in the D3D11 world) even sets a gamma ramp, and I don't think it even *works* with D3D11 when using Proton at the moment.

**Comment by ViNi-Arco** [comment]
Hi @hav4k, On the Diolinux blog, he addresses a subject that is very similar to yours. I think it's a good idea for you to follow his steps to see if it improves for you, take a look at what he says when he finishes his thoughts:

`It is noticeable how much more natural the “sunlight” is, as well as the reflections are more vivid in the parts where the Vulkan ICD Loader is on, contrasting with the bands in which it is “OFF”.`

`With it activated, although the change is not at all drastic, the game was already running “beautifully” on Linux without this option activated, the graph is a little closer than I saw, as people see when playing the Blizzard game on the console , like the PS4.`

`Interestingly, I saw some people who tested Linux for the first time because they learned that Overwatch was running, commented that the graph “looked different”, somehow, even though they didn’t know how to explain exactly what is treatable, and maybe it’s exactly what, a way in which the rendering of lighting via Vulkan (DXVK) is done in this specific case.`

Access the Diolinux blog with the probable solution to your "problem" here:
https://diolinux.com.br/2019/08/vulkan-icd-loader-linux-gaming.html

**Comment by hav4k** [comment]
Hi, again.

Thanks a lot to everybody who reply me. 

Following yours suggest, i already test Spyro Reignited Trilogy with Manjaro and Windows:

https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=240a69f8-8cd3-11ea-a879-0edaf8f81e27

-DXVK 1.6.1 +Windows 10 (1909):

https://ibb.co/fdvGfbw

Results are identical, thought. So, is my faulty perception of vision or maybe monitor? :/

Checked icdloader and color profile, are fine without differences...

**Comment by hav4k** [comment]
Hi.

I return to comment that recently switch GPU for RX 5700 XT and it's solved. Non free drivers of Nvidia... issues? I don't know but now colors are fine.

Edit: Almost same setup, only changed GPU.

Regards.
