### ISSUE TITLE
dxvk 1.7 laptop temperature rised

### ISSUE THREAD

**Issue by arabcian** [doitsujin/dxvk#1696]
with older version like 1.4 my laptop temperature is around 68-72 if use dxvk 1.7 it rises to 72-80

**Comment by doitsujin** [comment]
Which means that we're making use of your hardware more efficiently. Great news!

**Comment by yLosh** [comment]
'0'

**Comment by WinterSnowfall** [comment]
You're probably [holding down spacebar](https://xkcd.com/1172/).

**Comment by harrypotterIUP** [comment]
> Which means that we're making use of your hardware more efficiently. Great news!

@doitsujin Why does higher efficiency equal higher temperature? Doesn't higher temperature equal higher power consumption, i.e. the opposite of efficient performance? Or maybe it's just a joke I don't understand?

**Comment by K0bin** [comment]
Unless you have a FPS limit in place or use vsync, games will run as fast as possible. When something is inefficient, it might lead to lower GPU utilization or low CPU utilization. So when efficiency improves, more of the hardware gets utilized and the computer produces more heat.

**Comment by harrypotterIUP** [comment]
> Unless you have a FPS limit in place or use vsync, games will run as fast as possible. When something is inefficient, it might lead to lower GPU utilization or low CPU utilization. So when efficiency improves, more of the hardware gets utilized and the computer produces more heat.

Hey @K0bin, thanks for the response. You're saying code improvements in DXVK between those versions that the issue author mentioned lead to better graphics or higher frame rate (both of which are desirable) which in turn also lead to increased GPU/CPU load. That makes sense so far.

However, I don't see what that has to do with efficiency. From my perspective, yes, you get more (i.e. better graphics, better FPS), but you also pay more (i.e. higher CPU/GPU load). I don't understand how you can make a statement about efficiency. That's why I was curious about the correlation.

Maybe it's just a simple typo and @doitsujin meant that the hardware is being used more ~efficiently~ *effectively*?

**Comment by WinterSnowfall** [comment]
The efficiency argued here is part of the translation layer. If it were inefficient (ergo doing stuff in a sub-optimal way) your GPU would have to wait a bunch doing nothing (idling). So an increase in translation efficiency (code improvements) lead to a more efficient use of the hardware form a performance standpoint (the goal here is performance not ENERGY efficiency, and the resulted performance improvement is what we are quantifying with said general-term efficiency). Hope it makes sense now.

**Comment by Blisto91** [comment]
To expand a bit on Winters explanation above. With the first paragraph below we are assuming there are no artificial limits holding the GPU back like a frame limit.

As said usually when we talk about efficiency in a dxvk context we mean how much of the available processing power are we able to put to to use providing frames instead of waiting around doing nothing.
An example could be a GPU where the utilization sits at 50% which would mean it's spending and awful lot of time not working on giving us new frames. It might be spending alot of time waiting for the CPU to finish it's part of the work.
It is implied here that more utilization equals more frames put out. If we spent more work but got the same amount of frames that ofc wouldn't be good.

Related to the second note, if we are somehow able to output more frames with the same amount of work we could then translate that into energy efficiency by applying a frame limiter. So in this case if we had a frame limit of 60 we would see lower lower utilization and power consumption (hopefully) since it takes less work to reach it.
As a extra addon to that also note that it is largely a myth that  Vulkan equals more performance. Usually when there is a bump on Windows compared to native it is usually up to the Vulkan driver being more efficient than e.g. the old Direct3D 9 driver. Or maybe optimizations have been made for a specific use case. But native DirectX could be just as efficient if the work was put into it in the drivers.
Afaiu Nvidia have pretty decent DirectX drivers and AMD improved theirs alot not too long ago.
