### ISSUE TITLE
Starcraft 2 has low performance with DXVK on Intel graphics

### ISSUE THREAD

**Issue by Venemo** [doitsujin/dxvk#1712]
I have a Dell XPS 13 7390 with the integrated Intel graphics. Starcraft 2 should be playable (even if not perfectly) on medium settings on this machine. However, DXVK has a huge performance discrepancy on this hardware.

The game is free to play, so the easiest way to reproduce this issue is to launch the first mission of the first campaign.

| Technology | Frame rate |
|-----------|-----------|
| wined3d | 30-35 fps |
| nine | 50-55 fps |
| DXVK | 25-30 fps |

As you can see, in this game DXVK performs slightly worse than even wined3d, and nine straight out blows DXVK out of the water.

### Software information

* Name of the game: Starcraft 2
* Graphics settings: all medium

### System information

* GPU: Intel UHD Graphics (Gen9, integrated into the i5-10210U, Comet Lake CPU)
* Driver: mesa 20.1.4
* Wine version: `wine-5.14-1.fc32.x86_64` (this is Wine Staging)
* DXVK version: `wine-dxvk-1.7-1.fc32.x86_64`
* Distro: Fedora 32
* Session: Gnome Wayland

### Apitrace file(s)

There is no graphical glitch, so I don't believe an apitrace is necessary.

### Log files

[SC2_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/5045399/SC2_x64_d3d9.log)

(There are no other log files present in the game directory.)

**Comment by doitsujin** [comment]
We kind of do need an apitrace to get an idea of what the game might be doing.

Is this common on other hardware as well? I don't think we test ANV at all.

**Comment by Venemo** [comment]
The game is free to play, but if you don't want to bother with installing it, I can make an apitrace sometime next week.

As far as I remember, the situation is not so bad on AMD (especially with ACO), there DXVK performs only slightly worse than Nine, but at least they are in the same ballpark. Has been a while since I last tested, so take that with a grain of salt.

**Comment by saboya** [comment]
I have a laptop with a Vega 10 (3700U), can help with some perf testing.

**Comment by tannisroot** [comment]
Can you compile and test the performance with this forked branch? https://github.com/K0bin/dxvk/tree/d3d9-constant-compacting

**Comment by Joshua-Ashton** [comment]
fwiw, the constant compacting branch has a perf decrease across the board on discrete gpus.

**Comment by Blisto91** [comment]
@Venemo Is this still a issue with latest dxvk and drivers?
I don't have a intel gpu but i did some quick tests with a R9 380 & mesa-git on dxvk 1.7.1, 1.10.1 and WINED3D. The performance seems to have improved a bit since 1.7.1 and is now seems faster than WINED3D. At least on my setup.

**Comment by Venemo** [comment]
@Blisto91 I haven't played anything on the Intel GPU for a very long time. If there is a reason to assume that the situation improved recently, I can re-test.

**Comment by Blisto91** [comment]
Rgr. I can't say that it has for you specifically, but there have been some improvements since 1.7.1 so was just interested if you still found the performance unsatisfying compared to the other two.

I'm mostly just checking out old issues 😁

**Comment by Vinjul1704** [comment]
Looks like it doesn't seem to be an issue anymore, at least on my Intel Arc A380 system. I did some quick benchmarks between DXVK 2.3, Master, 1.7.1 and WineD3D.

System:
- CPU: Intel Xeon E3-1270v5
- GPU: Intel Arc A380
- OS/Software: Arch, Mesa git, Sway, wine-ge-25

I used the following settings, which basically set everything the game claims it uses the GPU for to max and everything it claims it uses the CPU for to min, due to my rather weak CPU:
![image](https://github.com/doitsujin/dxvk/assets/16061278/26ae72b5-6c40-4316-9cc4-1474e9c16fbf)

I simply loaded a replay, didn't move the camera at all and wrote down the FPS using the ingame-counter (CTRL+ALT+F) at 1:00, 5:00 and 10:00 minutes in. The replay I used can be found here: https://lotv.spawningtool.com/82416/

I first compared DXVK 2.3 and WineD3D, 2 runs each:

| Time (Run #) | FPS (DXVK 2.3) | FPS (WineD3D) |
| - | - | - |
| 1:00 (Run 1) | ~115 | ~93 |
| 1:00 (Run 2) | ~116 | ~90 |
| 5:00 (Run 1) | ~107 | ~82 |
| 5:00 (Run 2) | ~108 | ~80 |
| 10:00 (Run 1) | ~106 | ~78 |
| 10:00 (Run 2) | ~106 | ~76 |

Next, I tested DXVK Master (specifically this artifact: https://github.com/doitsujin/dxvk/actions/runs/7921308612) and 1.7.1, but only 1 run each:

| Time | FPS (DXVK Master) | FPS (DXVK 1.7.1) |
| - | - | - |
| 1:00 | ~115 | ~74 |
| 5:00 | ~108 | ~70 |
| 10:00 | ~106 | ~67 |

Seems like the performance issue was fixed at some point over the years.

**Comment by K0bin** [comment]
I'm gonna close this then. If this turns out to still be a problem after all, please open a new issue.
