### ISSUE TITLE
getting DXVK to work with GW2 addon manager

### ISSUE THREAD

**Issue by seanbarr1988** [doitsujin/dxvk#1741]
Hi I am using the guild wars 2 addon manager (https://github.com/fmmmlee/GW2-Addon-Manager) to launch other addon DLL's such as arcDPS. However when i create a folder for DXVK the addon manager log simply states "loading dxvk.dll" but it does not complete and never gets loaded. can some one please help me get this to work.

**Comment by magnapeccatrix** [comment]
There is a section at [GW2 Addon Manager ](https://github.com/gw2-addon-loader/Approved-Addons)page that says:

How to Add Your Addon
Submit a PR where you add a folder with the name of your addon (preferably in relatively short and basic form, e.g. gw2radial or arcdps_bhud) with a completed update.yaml file within. See the d912pxy example as a rough guideline.

I also would like to give DXVK another try while also using addons from the Manager but in this case, there is nothing I can do as an end user it seems.

**Comment by magnapeccatrix** [comment]
![image](https://user-images.githubusercontent.com/15203877/117585302-5ea3ef00-b11a-11eb-8177-184694c152f5.png)

Excuse me to bump this but I noticed there is actually an option for DXVK on SelectRenderer addon, which is from the same person who created D912PXY but when I select DXVK, I get 3D output initilization error probably because I don't have DXVK.dll and don't know where to put it so SelectRender will see and use it. 

Any ideas about this or shall I make a new thread here or on the SelectRender though there is no issues placed on its page yet. 
Thank you for reading.

**Comment by magnapeccatrix** [comment]
https://github.com/megai2/SelectRenderer/issues/1 here is an update that seems to solve the problem. For future reference.

**Comment by Blisto91** [comment]
I think this one can be closed. As said any addons needs to be added as a PR in the repo.

**Comment by Blisto91** [comment]
@K0bin Also here i think 👀. Tho issue isn't with dxvk itself
