### ISSUE TITLE
Is it possible to disable log creation and just have logs go to stdout?

### ISSUE THREAD

**Issue by konomikitten** [doitsujin/dxvk#1743]
Topic kind of says it all, is there currently a way to keep the logging output of dxvk without writing logs files and just have logs go to stdout? If not could this be added?

**Comment by konomikitten** [comment]
I decided to just send them to `/tmp` for now but could we have a switch in the future to disable log file creation but not logging itself? Thanks.

**Comment by doitsujin** [comment]
May I ask what the use case is?

It's easy, but I really don't want to add even more unnecessary bloat. We already have a million environment variables to worry about.

**Comment by konomikitten** [comment]
> May I ask what the use case is?

I already capture the stdout and stderr of wine to a file having dxvk produce files is just duplicating what I already capture not to mention putting a bunch of files throughout game directories that can be hard to find and get rid of. I know it's a bit of a feature request but it would be really nice if dxvk didn't produce log files everywhere by default.

**Comment by doitsujin** [comment]
DXVK will continue to produce log files by default because otherwise we will see **even more** bug reports with zero information, and that is really the last thing I want.

I can add an option to disable file creation (even though I don't want to), but stderr alone is not reliable enough since DXVK is a windows library, and having to tell people how to capture stderr or manually enable logging especially with something like Lutris is just going to be a horrendous pain in the arse.
