### ISSUE TITLE
[d3d11] Need for Speed Most Wanted 2012 → missing shadows on cars? (I can't provide an apitrace, need help!)

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1745]
WineD3D:
![Screenshot_20200821_220059](https://user-images.githubusercontent.com/4572452/91076755-3fbf0480-e640-11ea-93f2-40d79960cca0.png)

DXVK:
![Screenshot_20200821_222447](https://user-images.githubusercontent.com/4572452/91076771-464d7c00-e640-11ea-89c6-f58a2f8c6487.png)

### System information
- GPU: Nvidia Geforce 730M
- Driver: 450.66
- Wine version: Proton 5.0-9 
- DXVK version: 1344

### Apitrace file(s)
I can't provide an apitrace, when I want to launch the game with the wrapper to do it, I have this error:
![Screenshot_20200821_225341](https://user-images.githubusercontent.com/4572452/91076958-8f9dcb80-e640-11ea-8364-7962d2675839.png)

I have no idea how to bypass that, if someone knows...

### Log files
[steam-1262560-wined3d.tar.gz](https://github.com/doitsujin/dxvk/files/5119568/steam-1262560-wined3d.tar.gz) (115 Mo uncompressed)
[steam-1262560-dxvk.log](https://github.com/doitsujin/dxvk/files/5119569/steam-1262560-dxvk.log)

**Comment by K0bin** [comment]
> I can't provide an apitrace, when I want to launch the game with the wrapper to do it, I have this error:

Did you copy all of the required files over? dxgitrace.dll, dxgi.dll and d3d11.dll

**Comment by NerosTie** [comment]
Yes, as usual.

Precision: it's the version on Steam. Maybe Origin check something before launching the game, I don't know...

**Comment by K0bin** [comment]
I managed to get a trace but it looks identical to what I get with D3D11 on Windows.

D3D11:
![grafik](https://user-images.githubusercontent.com/1131720/91084054-aac20880-e64b-11ea-9444-357abc6689ca.png)
DXVK:
![grafik](https://user-images.githubusercontent.com/1131720/91084067-b0b7e980-e64b-11ea-8fde-10e54489bd79.png)
D3D11:
![grafik](https://user-images.githubusercontent.com/1131720/91084078-b44b7080-e64b-11ea-9419-9de91192b198.png)
DXVK:
![grafik](https://user-images.githubusercontent.com/1131720/91084087-b7466100-e64b-11ea-8f59-ae00349f7a1c.png)

So this is either related to the ingame time of day and your position in the city (and maybe even car) or just a WineD3D bug instead. I'd go with the latter because it looks way too dark considering the rest of the scene. Also notice how bright my car still is under that bridge.

**Comment by K0bin** [comment]
Yeah it's a WineD3D bug indeed.

Replaying the trace with WineD3D looks totally off.
![grafik](https://user-images.githubusercontent.com/1131720/91084504-6420de00-e64c-11ea-9245-9af519c42d07.png)

![grafik](https://user-images.githubusercontent.com/1131720/91084556-7ac73500-e64c-11ea-9d2c-901d811d7811.png)

^ This is still the white car.

**Comment by NerosTie** [comment]
Thanks! :)
