### ISSUE TITLE
Hey would you mind building a release build for Newest-Windows-10 Pro?

### ISSUE THREAD

**Issue by lowspecchaos** [doitsujin/dxvk#1817]
I did try compiling it myself but Visual Studio was having none of it. meson errors -.- 
Like the performance is currently really close to Window's native performance in DX11.1,
Also Fullscreen-Exclusive can also break window on minimise,

(My PC doesn't like Windowed-FullScreenMode due to being Exclusive Fullscreen OS, i'm using
__COMPAT_LAYER=DisableDXMaximizedWindowedMode across most the OS)

 I would so love to do some more testing if you wouldn't mind & i understand my configuration 100% isn't supported xD 
But it would be nice to get a single build with no support on release.
Huge fan of your work,
BF4 looks epic, 
You all deserve a pat on the back lol,
Great Job 🥇 :) 
![image](https://user-images.githubusercontent.com/60080409/99136050-db965600-261a-11eb-8951-b0596eb5616b.png)

**Comment by K0bin** [comment]
Just use release 1.7.2.

**Comment by shijiediyo** [comment]
If you want to compile it in windows, you can use GIT. I tried and succeeded

**Comment by Lasloow** [comment]
The build is patched with https://github.com/Sporif/dxvk-async
[dxvk---no-package.tar.gz](https://github.com/doitsujin/dxvk/files/5550693/dxvk---no-package.tar.gz)

**Comment by seanmacky** [comment]
> The build is patched with https://github.com/Sporif/dxvk-async
> [dxvk---no-package.tar.gz](https://github.com/doitsujin/dxvk/files/5550693/dxvk---no-package.tar.gz)

Does this patch affect / allow asynchronous shader compilation in Dx9 games such as Guild Wars 2?

**Comment by altimumdelta** [comment]
Actually, it's very interesting it does work on Windows it self, even tho there's no mention in it and releases come 

While I'm not an expert debugger and profiling troubleshooter, so I'm not sure if this is at all helpful in depth, but on the surface DXVK actually has a benefit on Windows that it enables GPU profilers/debuggers which normally don't support a game's GFX API to be able to work on those games. I tried a DX11 game and it worked *fine*, it didn't crash and things seemed sound, though I mostly had no idea nor experience with most of it so I had no way of knowing how accurate or sensible those profiling results were that would actually be of any use and whether a real devloper could do some actual work with it's help.

Perhap's I'll try this again on that same game and poke around a bit what other's think. Certainly for that game it's not worthwhile, that game is getting a native Vulkan renderer anyway so the devs are rather focused on that, than on jerry-rigging a newer GPU profiler and trying to fix the old renderer.

The benefit may be the modern interface, more tools (filtering, searching), and perhaps some benefit in terms of visualizing the GPU work and timeline, but since it gives false (slower) results because of being another layer ontop then ofcourse everything wouldn't correspond to how it would be without DXVK, however in my case, it surprisingly was kinda even, it did not see a dramatic slowdown, it was pretty much the same, tho not any faster.

**Comment by Squall-Leonhart** [comment]
> Actually, it's very interesting it does work on Windows it self, even tho there's no mention in it and releases come in the non-Windows way of a .tar.gz file.
> Oh, BTW, I never built DXVK on Windows, I just used the linux bins. @lowspecchaos should have just tried the existing ones ;)

@altimumdelta 
The binaries are your typical dll's and work on windows no matter how you build them.

DXVK is basically the only way to play some games with AMD's drivers on Windows, since it circumvents the drivers overhead,   You  get a fair performance improvement in Witcher 3 and Sekiro for example, not to mention some games have been broken on RDNA since last year and DXVK fixes those,  it even improves GTA4's fps drops somewhat.

> Does this patch affect / allow asynchronous shader compilation in Dx9 games such as Guild Wars 2?
@seanmacky Yes

**Comment by lowspecchaos** [comment]
Hi again i've using the default libraries in release for DXVK but i saw them bottom of the DXVK github page says

"For non debian based distros, make sure that your mingw-w64-gcc cross compiler does have --enable-threads=posix enabled during configure. If your distro does ship its mingw-w64-gcc binary with --enable-threads=win32 you might have to recompile locally or open a bug at your distro's bugtracker to ask for it."

& i thought maybe targeting windows rather than linux might fix the issues i'm having with the window crashing on minimize 
Currently testing the DXVK-ASync build on Windows, Thank you for all the help :)
