### ISSUE TITLE
HUD to show VSYNC status

### ISSUE THREAD

**Issue by konomikitten** [doitsujin/dxvk#1870]
It'd be nice if there was a field in the HUD to show if VSYNC is on or off, thanks in advance.

**Comment by doitsujin** [comment]
Just had a somewhat lengthy discussion about this.

DXVK has been logging the effective Vulkan present mode (which dictates vsync behaviour) for some time, it's rather difficult to transfer this info back to the HUD. We'll just keep the info in the logs.

**Comment by WinterSnowfall** [comment]
If having a VSync indicator on the hud was somehow on your bucket list, [here's a build on top of dxvk 2.2](https://github.com/WinterSnowfall/dxvk/actions/runs/4995163297) which should work fine in most cases.

As doitsujin said, it's a rather big PITA to implement this correctly, so what I've done above is assume that the Vulkan present mode selected in the frontend/requested by the game is always available, which may or may not be the case, depending on what the Vulkan drivers ultimately decide. Since this approach isn't technically correct, even if it seems to mostly work fine in practice, it won't be merged (or even PRed).

I probably won't be rebasing it either, but if anyone wants to do that and keep using it, janky as it is, go ahead with my blessing.
