### ISSUE TITLE
[d3d9] Guild Wars 1 hangs

### ISSUE THREAD

**Issue by accela** [doitsujin/dxvk#1879]
Guild Wars 1 at a specific scene hangs and have to kill the game. It is 100% reproducible. 
Disabling dxvk and using wined3d works fine.
Possible point of interest the validation errors in the log below. Thank you.

### Software information
Guild Wars 1

### System information
- GPU: AMD RX 480
- Driver: Mesa git
- Wine version: wine-staging-6.0_rc4
- DXVK version: Latest from master

### Apitrace file(s)
https://drive.google.com/file/d/1XRuh6yCElI-VNbhQWCJ2dhd0sGRgqOwL/view?usp=sharing

### Log files
[guildwars.log](https://github.com/doitsujin/dxvk/files/5760500/guildwars.log)

**Comment by jrugia** [comment]
Can confirm this also happens with an RX 5500XT and Intel HD 5500 (i3 5005U cpu) with Mesa 20.3.2 and dxvk 1.7.3. An ideal spot to reproduce it is by trying to load the "Augury Rock" mission which hangs all the time. Works fine on Nvidia. Weirdly enough it doesn't affect the entire game.

I tried older Mesa builds and all 20.x.x have same issue. Works fine with 19.3.5 though.

@Joshua-Ashton or @doitsujin : This game is an MMO, if you need a test account to work on the issue I'd be happy to lend you one.

**Comment by doitsujin** [comment]
Can you please clarify what "hang" means in this case? GPU hang?

**Comment by accela** [comment]
Graphics freeze, music keep playing, can return to desktop.

**Comment by jrugia** [comment]
I've done a little more research into this. I initially thought Mesa 19.3.5 was the last known version to work with recent dxvk's, I was wrong. The game works fine with Mesa 20.1.xx and dxvk 1.7.3.

If you go as far back as DXVK 1.5.4 though, the game works fine again with newer Mesa versions, in my case I'm running 20.3.2.  Switching to 1.5.5 makes the game unstable again.

@doitsujin: I believe it's the game that hangs, process has to be killed manually. Rest of desktops keeps working fine otherwise.

DXVK 1.5.5: https://user-images.githubusercontent.com/13750621/103485596-be4e5e80-4df7-11eb-907f-513948893c09.mp4

DXVK 1.5.4: https://user-images.githubusercontent.com/13750621/103485617-f655a180-4df7-11eb-96f8-fa064c51f3b1.mp4

**Comment by Gnatzelle** [comment]
Can also confirm here (Ryzen 5 2400G, RX 570, AMDGPU + Mesa 20.3.4-2 on Arch Linux)...anything newer than v1.5.4 hangs the Game. 
Besides the spots @jrugia named, it happens also after you created a fresh Factions or Nightfall Character and be thrown at their respective starting locations ("Monastery Overlook" and "Island of Shehkah").

**Comment by greatlord** [comment]
Can also confirm here  AMD Ryzen 5 3400G, AMD fury   AMDGPU Mesa 20.3.4 on debian testing. 
it is freezing's direly when I do rotate in the game or start move any where in the game

**Comment by greatlord** [comment]
I found a solvitions to use DXVK 1.5.5 to 1.8.1  by disable state cache it does not frez any more
set env to DXVK_STATE_CACHE=0

**Comment by K0bin** [comment]
Can you try the build here: https://github.com/doitsujin/dxvk/actions/runs/716857969 and tell me whether that fixes it?

**Comment by Gnatzelle** [comment]
@K0bin Just tried your build and...it works :) No Crash when i start moving around in our Guild Hall, no crash in Augury Rock like in @jrugia Videos and no crash with a fresh Factions or Nightfall Character.

Really Awesome...Thank you ^^

**Comment by K0bin** [comment]
Great to hear.
