### ISSUE TITLE
[D3D11] Outward VRAM usage keep increasing every time loading new location

### ISSUE THREAD

**Issue by HenryJk** [doitsujin/dxvk#1984]
VRAM usage keep increasing every time loading new location. Eventually it leaks to RAM and degrade performance, usually loading a new location a single time is enough to make it leaks to normal RAM. Suspected objects not being unloaded properly.

### Software information
Outward, medium preset with advanced shader turned on.

### System information
- GPU: `GTX 1650 Max-Q`
- Driver: `nvidia 460.56-7`
- Wine version: `wine-staging v6.1 `
- DXVK version: `v1.7.3-37-g3f91cdbc`

### Apitrace file(s)
- [Outward.trace](https://drive.google.com/file/d/1g3w77Zz17n6ebUto7VmV0OdMA_zEVurC/view?usp=sharing)

### Log files
- d3d9.log:
- d3d11.log: [Outward_d3d11.log](https://github.com/doitsujin/dxvk/files/6176320/Outward_d3d11.log)
- dxgi.log: [Outward_dxgi.log](https://github.com/doitsujin/dxvk/files/6176321/Outward_dxgi.log)

Going out and in of a location increase VRAM usage and RAM usage.

![Screenshot from 2021-03-21 03-56-42](https://user-images.githubusercontent.com/25541369/111883998-a4d1b180-89f9-11eb-9a53-7de48a86f1bb.png)
![Screenshot from 2021-03-21 03-57-07](https://user-images.githubusercontent.com/25541369/111884001-a8fdcf00-89f9-11eb-9d31-1e3106373efd.png)
![Screenshot from 2021-03-21 03-57-23](https://user-images.githubusercontent.com/25541369/111884003-ad29ec80-89f9-11eb-8343-7fb42c79926b.png)

**Comment by doitsujin** [comment]
DXVK does not free VRAM allocations by design, this is no memory leak. If there is one, it's almost certanily the game's fault.

Also, the apitrace doesn't really contain anything useful since it just ends after a handful of black frames.

**Comment by HenryJk** [comment]
If the resource evicted from VRAM is actually unused, why would that cause any performance problem? Also, does apitrace actually work with steam game? I have tried multiple times and apitrace doesn't behave as I expect.

**Comment by Kron4ek** [comment]
I can't this reproduce this on AMD Polaris (though with DXVK 1.8.1-1c2edab), changed location about ten times and VRAM usage was still about the same, so this is probably Nvidia-specific. Does this applies to all locations or only the ones from the screenshots?

**Comment by HenryJk** [comment]
VRAM usage is via mangohud, and somehow, dxvk-hud doesn't report such increase. It applies to all locations but I do use nvidia.

**Comment by Kron4ek** [comment]
Ok, tried now with MangoHud and can confirm that VRAM usage value is different in DXVK and MangoHud. According to MangoHud, VRAM usage is stuck at 3.7 GB and RAM usage increases a little with every loading of location, so it looks like memory leak indeed, if the values are not wrong.

![outward_memory](https://user-images.githubusercontent.com/13851877/111905768-2d3e6980-8a6f-11eb-893b-5866b865dda9.jpg)

**Comment by HenryJk** [comment]
Do you get fps degradation as well? I won't mind memory increase if they aren't actually used, meaning don't degrade performance. The thing that bothers me is the fps degradation every loading screen. The degradation is especially huge on a town. If I load the game when my character already in town, I can maintain 60 fps. But when going out and in of a town, the fps start to tank.

**Comment by Kron4ek** [comment]
No, to my surprise, i don't get FPS degradation.

**Comment by HenryJk** [comment]
The worst degradation is between Abrassar Desert and Levant, or Abrassar Desert and Enmerkar Forest. For the latter, my FPS can tank to the 30s.

**Comment by K0bin** [comment]
> If the resource evicted from VRAM is actually unused, why would that cause any performance problem?

DXVK will create new resources in system memory when it runs out of VRAM. What doitsujin meant was that DXVK will never move resources around.

And yes, the MangoHUD metric is not relevant here. Focus on the DXVK HUD one.
There probably isn't much we can do here so just lower your texture resolution. 

Either way, can't do anything without an apitrace.

**Comment by Kron4ek** [comment]
[apitrace](https://drive.google.com/file/d/1CHegcNSHglYVuS7Yy_fziznFCD7AfIP_/view?usp=sharing) (4.6 GB when extracted).

**Comment by HenryJk** [comment]
How to create apitrace, really? Tried to do the command `apitrace-latest\bin\apitrace.exe trace -a dxgi Outward.exe` on windows and it seems to not working

**Comment by Kron4ek** [comment]
I used exactly the same command (on Wine), works for me.

`wine apitrace-latest-win64/bin/apitrace.exe trace -a dxgi Outward.exe`

**Comment by HenryJk** [comment]
New apitrace, this time it works properly
[Outward.7z](https://drive.google.com/file/d/1DRgycjJZO_75TQ_1rKTZapF7V3Xklfgb/view?usp=sharing)

Changing between thees 2 locations have a performance hit.
![Screenshot from 2021-03-22 06-13-10](https://user-images.githubusercontent.com/25541369/111922686-0ebf8900-8ad6-11eb-9635-3739c5d7428d.png)
![Screenshot from 2021-03-22 06-13-30](https://user-images.githubusercontent.com/25541369/111922688-11ba7980-8ad6-11eb-8d32-ab48a31a8878.png)
![Screenshot from 2021-03-22 06-13-49](https://user-images.githubusercontent.com/25541369/111922690-12eba680-8ad6-11eb-90e2-24d157b3a293.png)

**Comment by doitsujin** [comment]
wined3d doesn't have issues with that because the OpenGL driver does all the black magic for it. DXVK on AMD cards should also be more or less fine since the driver itself has more dynamic memory management than Nvidia's does.

This kind of thing usually happens when the game decides to recreate its render targets and those then end up in system memory, but as mentioned, there's pretty much nothing we can do about that without rewriting a lot of stuff. Lowering texture quality in game might help mitigate the issue, or changing the amount of VRAM reported to the game via dxvk.conf.

**Comment by HenryJk** [comment]
Correct me if I'm wrong, but basically the only way to solve this issue is by writing garbage collection for gpu?

**Comment by TheZoq2** [comment]
This issue seems to affect DCS world and squad, so I'd really appreciate a fix though I fully understand it being a massive amount of work.

> DXVK on AMD cards should also be more or less fine since the driver itself has more dynamic memory management than Nvidia's does.

I'm seeing these issues in DCS world on both my old rx 580 and new rx 6800. (game runs fine, then suddenly drops down to sub 5 FPS, especially in texture-heavy environments. IIRC, this doesn't happen right after VRAM usage goes above 100%, I've seen 150% etc. without issue. Maybe that's the render target thing you talked about.

> Correct me if I'm wrong, but basically the only way to solve this issue is by writing garbage collection for gpu? I wonder why is the unused garbage still affecting performance.

As I understand it, because it's never moved out of the GPU. When new textures etc. have to be loaded, those have to go in system RAM instead of VRAM.

**Comment by doitsujin** [comment]
I don't really know what to do here since the only real solution is to rewrite half of DXVK which is obviously not really viable.

**Comment by TheZoq2** [comment]
Yea, it's an unfortunate situation. In the DCS case, it seems like lowering texture quality a bit helps, and the problems are only happening on one map for me after my GPU upgrade.

**Comment by Bxaa** [comment]
Same issues in dx9 (all gamebryo games tes-4, f3\NV) vram overflow and slide show 1-5 fps. 
Dxvk start using shared memory? 
After loading new location vram not purge.

Is  there way to cap vram usage for dxvk?
d3d9.maxAvailableMemory not affect

**@doitsujin**
i'm use your buld 1.8-21-gd51562fc9 (fixed regression dx9)
(1.8.1 still crash game)

**Comment by TheZoq2** [comment]
> Is there way to cap vram usage for dxvk?
d3d9.maxAvailableMemory not affect

As I understand it, that just tells the game how much VRAM is available. But as far as the game is concerned, it has unloaded the textures from the previous level, it's just that dxvk does not do that in reality. So `.maxAvailableMemory` might fix the problem if the game does something like pre-caching a bunch of texture because the space is available.

**Comment by Bxaa** [comment]
So after test: max available memory - is a reason of issue. (in my case) 
Without it all work fine. 
Maybe will be useful to someone. (dx9)

**Comment by adamreichold** [comment]
I am sorry if this unrelated, but I noticed a similar issue with MudRunner running under Proton Experimtal: More detailed maps make the game being killed by the OOM killer after taking up more than 14 GB of memory. (This is on integrated graphics with shared memory, but since the memory is not attributed to the process, I guess that it is graphics memory.)

Using WineD3D, the game loads and runs those maps without issues. What is even more interesting, if I load the map using WineD3D and then resume it (instead of initializing a new game) using DXVK, things work as well. So it seems, the game's initialization routines interact in some really unfortunate way with DXVK's memory management.

**Comment by Blisto91** [comment]
@HenryJk Are you around to give this a fresh spin with dxvk master? Vram usage and management should be much improved now.

**Comment by HenryJk** [comment]
I can try again in a few days

**Comment by WinterSnowfall** [comment]
I've given this a spin and there's definitely some heavy defragging going on between areas, as the game destroys some allocations and keeps others. I can see this being a problem before defragging was added for sure, but as of 2.5 there's no memory bump when going between areas.
