### ISSUE TITLE
Windows support for compiled windows executables?

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#2]
I just tested compiled binaries from Windows and I'm getting:

> err:    CreateDXGIFactory: Requested version of IDXGIFactory not supported

on both d3d11-compute and triangle samples and even on dxvk-triagle which seems to use Vulkan directly..
removing dxgi.dll allows  dxvk-triagle to work but d3d11 samples fail with missing DXGICreateDevicePrivate entry point missing on d3d11.dll..

shouldn't your wrapper also work on Windows?

**Comment by doitsujin** [comment]
I haven't tested this on Windows yet, although in theory it *should* work.

The reason the DXGI and D3D11 sample executables don't work might be that they are not linked properly to the dxgi and d3d11 dlls yet. This is something that needs to be fixed in the build files.

Not sure why the dxvk-triangle sample isn't working though. As you said, it uses Vulkan directly and doesn't use DXGI.

**Comment by oscarbg** [comment]
maybe Vulkan loader or Vulkan vendor dll implementation (tested on AMD GPU) gets eventually loading dxgi dll.. need try with another GPU vendor to see if it gets fixed..

**Comment by doitsujin** [comment]
I changed the build files so that the d3d11 and dxgi samples are now independent of dxvk. With these changes, it works on my Windows 10 (also using an AMD GPU).

d3d11-triangle doesn't work properly with dxvk yet, there seems to be a bug in my swap chain code that doesn't occur on Linux/RADV. [Tutorial01](https://github.com/walbourn/directx-sdk-samples/tree/master/Direct3D11Tutorials) from the Microsoft SDK does work, however.
