### ISSUE TITLE
Nvidia overheating

### ISSUE THREAD

**Issue by Pshemas** [doitsujin/dxvk#2007]
I wonder whether there's anything can be done via setting etc to prevent gpu heating to quite noticeable levels when using DXVK. I've noticed that both my desktop gpu and the one of the laptop get pretty hot when I use DXVK, definitetly reaching higher temps than I see in native apps.
I love the extra performance that I get with DXVK (you deserve big, fat THANK YOU - thx to this project I've been able to launch some cad apps as well), but I'd love to tune it up a bit, especially on my laptop where this is a major pita (where fans get pretty loud, repasting the gpu with better thermal compound didn't help much).

**Comment by Joshua-Ashton** [comment]
You can force enable vsync if you don't have that already with `dxgi.syncInterval = 1`

**Comment by mirh** [comment]
V-sync is the worst frame limiter you could use. 
Anyway, are you sure this behaviour is just about dxvk itself, rather than the possible direct consequence of your gpu being able to get higher usage?

**Comment by WinterSnowfall** [comment]
> the possible direct consequence of your gpu being able to get higher usage?

This. It is most likely not a situation that only DXVK can get you in - chances are that using any other Vulkan-based apps will result in the same behavior as far as your GPU is concerned.

But, to answer the initial question - beside what's already been mentioned (frame rate limiters), I would say you'd have better luck trying to tune your GPU rather than DXVK or any other software that hits it with demanding loads. Or a combination of both. Since you mentioned you're using Nvidia, you should have the ability to set a desired power limit on the fly with command line utilities like nvidia-smi. If you are on Windows, there are a plethora of apps that can help you fine tune these things.

**Comment by doitsujin** [comment]
In a way it's actually great news that hardware runs hot with this because it means we're making good use of it.

Anyway, not a bug, see answer above.

**Comment by gabriele2000** [comment]
> V-sync is the worst frame limiter you could use.
> Anyway, are you sure this behaviour is just about dxvk itself, rather than the possible direct consequence of your gpu being able to get higher usage?

oh sure, vsync is the worst, yet I love to play without tearing which happens even at 40fps with vsync off

**Comment by mirh** [comment]
Tearing bearableness is pretty dependent on the response time of the pixels of the monitor. 
And there's quite the [debate](https://blurbusters.com/howto-low-lag-vsync-on/) if frame limiting couldn't be *basically almost* as good as vsync, but with none of the downsides. 

Anyhow, see https://github.com/doitsujin/dxvk/commit/4d8940957cb40fbd1be3eb6cc74d1677d3e352d4 for dxvk.

**Comment by gabriele2000** [comment]
> Tearing bearableness is pretty dependent on the response time of the pixels of the monitor.
> And there's quite the [debate](https://blurbusters.com/howto-low-lag-vsync-on/) if frame limiting couldn't be _basically almost_ as good as vsync, but with none of the downsides.
> 
> Anyhow, see [4d89409](https://github.com/doitsujin/dxvk/commit/4d8940957cb40fbd1be3eb6cc74d1677d3e352d4) for dxvk.

Thanks for the link to the fix, it work in some games and not in others, but that's ok.
Anyway, I have a 5ms TN display so no, either I've got a good response-time brain, or some games are utter garbage at rendering things... like why I can get tearing even under the maximum output of my display? In this case I've got a 120hz display

**Comment by mirh** [comment]
You can get tearing because if you don't sync to vblank (or you don't do some trickery like scanline sync), your gpu will throw a frame on screen whenever it wants. 
And "5ms" means nothing, you have to check actual reviews (hell, even high refresh rate monitors can [still have](https://www.rtings.com/monitor/tools/compare/aoc-cq32g1-vs-asus-vg245h/4309/573?usage=3623&threshold=0.10#comparison_1425) shitty permanence times)
