### ISSUE TITLE
Rewerite D3D12 для Cyberpunk 2077 на Windows 7

### ISSUE THREAD

**Issue by ToGoRo** [doitsujin/dxvk#2025]
CDProject made the mistake of not rewrite D3D12. The bottom line for everyone on Windows 7 crashes when restarting the game. Please, I see you are savvy. Maybe you can rewrite that file.

**Comment by Joshua-Ashton** [comment]
You don't need to make the same issue twice.

**Comment by Iglu47** [comment]
@ToGoRo have you tried [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2337475489) already?
(also make sure you have all the files officially supplied with the game 😕)

**Comment by ToGoRo** [comment]
> @ToGoRo have you tried [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2337475489) already?
> (also make sure you have all the files officially supplied with the game )

**This method does not help at all. Since the problem is in the DLL files themselves, this creates a problem. Since they didn't adapt the dl files for Windows 7.**

**Comment by ZachBacon** [comment]
I don't want to be this guy, but I'll be this guy, Windows 7 was end of lifed last year, and dxvk while technically yes can work on windows its primary target is Linux, it maybe time to move on from Windows 7, also pretty sure this was mentioned, but cyberpunk 2077 is a dx12 game, not a dx9,10, or 11 game which dxvk targets.

**Comment by Iglu47** [comment]
> Since they didn't adapt the dxd12.dll files for Windows 7.

It is not clear what exactly you are talking about, since `Cyberpunk 2077` uses [D3D12On7](https://devblogs.microsoft.com/directx/porting-directx-12-games-to-windows-7/) just for _this_ reason.
Just make sure you are using the official build of Windows 7 and do not have any other technical problems (unrelated to dx12).

But in any case, this tracker should not be a place for solving problems related to things officially supported by the developers of the game.

**Comment by Iglu47** [comment]
> Since they didn't adapt the dxd12.dll files for Windows 7.

It is not clear what exactly you are talking about, since `Cyberpunk 2077` uses [D3D12on7](https://devblogs.microsoft.com/directx/porting-directx-12-games-to-windows-7/) just for _this_ reason.
Just make sure you are using the official build of Windows 7 and do not have any other technical problems (unrelated to dx12).
But in any case, this tracker should not be a place for solving problems related to things officially supported by the developers of the game.

**Comment by Iglu47** [comment]
> Since they didn't adapt the dxd12.dll files for Windows 7.

It is not clear what exactly you are talking about, since `Cyberpunk 2077` uses [D3D12On7](https://devblogs.microsoft.com/directx/porting-directx-12-games-to-windows-7/) just for "_this_" reason.
Make sure you are using the official build of Windows 7 and do not have any other technical problems (unrelated to dx12).
But in any case, this tracker should not be a place for solving problems related to things officially supported by the developers of the game.
