### ISSUE TITLE
AC Odyssey Crashes

### ISSUE THREAD

**Issue by Tebeas** [doitsujin/dxvk#2055]
When i try to run AC Odyssey the game crashes on launch, most log files are completly empty, i tried a lot of things but it just wont work

I Have:

Disabled uplay overlay
Used both the dxig and d3d11 files only as well as all the files to test if it will work
Other things i cant even remember, i checked the issues page and i see a lot of similar posts with no clear answer on how to fix this

I use Windows 10, i know you dont support it, but i heard of cases where DXVK increased fps so it would be great if you would respond

### Software information
AC Odyssey, Borderless Windowed

### System information
- GPU: RTX 2060
- Driver:  466.27
- Wine version: 
- DXVK version: 1.8.1

### Apitrace file(s)
- none

### Log files
- d3d9.log:
- d3d11.log: [ACOdyssey_plus_d3d11.log](https://github.com/doitsujin/dxvk/files/6448683/ACOdyssey_plus_d3d11.log)
- dxgi.log:

**Comment by doitsujin** [comment]
> i know you dont support it

And this is exactly why. Could be caused by literally anything, usually some third-party software that doesn't even have to be actively running in order to cause issues (looking at you, RTSS). And this kind of thing isn't something I can or even want to remotely debug on people's systems all the time.
