### ISSUE TITLE
[Win 10] Any game crahes with dxgi installed

### ISSUE THREAD

**Issue by tima0714** [doitsujin/dxvk#2147]
Hi, i tried to use dxgi with some games, i tried with dx9, 10, and 11 and all these games is crashes. I really don't know why.

### Software information
Games i have tried to run:
Deus ex human revolution
Fallout new vegas
Halo mcc (anticheat diasabled)
Amid evil
### System information
- GPU: GeForce GTX 1660 Super
- Driver: 471.11 Game ready
- Wine version: 
- DXVK version: 1.9

### Log files
- d3d9.log:
- d3d11.log: https://pastebin.com/KzMkfs6Z
- dxgi.log: https://pastebin.com/azzUkH9J

**Comment by doitsujin** [comment]
> I really don't know why.

Neither do I, and this is exactly the reason why I don't want to bother with Windows issues. There's juts nothing we can do here, 90% of the time it's just some broken third-party software getting in the way and the remaining issues are due to games not loading the correct DLLs which cannot be worked around on our end.
