### ISSUE TITLE
[feature-request] setup_dxvk.sh: use $WINE from system environment

### ISSUE THREAD

**Issue by jl452** [doitsujin/dxvk#2193]
replace
> wine="wine"
> wine64="wine64"
> wineboot="wineboot"

to something like
> WINE="${WINE:-wine}"
> WINE64="${WINE}64"

example from Proton-6.13-GE-1/protonfixes/winetricks

**Comment by doitsujin** [comment]
Feel free to submit a PR.

**Comment by Ahmed-E-86** [comment]
```
wine="$WINE"
wine64="${WINE}64"
wineboot="${WINE}boot"
```
This will work with most custom wine builds, but it will not work with Proton or Proton-GE builds because `wineboot` does not exist with these builds, but the script will work without finding `wineboot`. The only remaining issue is if you do not use `WINE=/path_to_wine_binary`, because you will end up with this error:
`64: Not a wine executable. Check your $wine.`

but this issue can be fixed with this script:

```
if [ -z "$WINE" ]; then
   wine="wine"
   wine64="wine64"
   wineboot="wineboot"
fi

if [ -n "$WINE" ]; then
   wine="$WINE"
   wine64="${WINE}64"
   wineboot="${WINE}boot"
fi
```
I tested it, and it works without any issues.

**Comment by Ahmed-E-86** [comment]
> Feel free to submit a PR.

https://github.com/doitsujin/dxvk/pull/2304

**Comment by Ahmed-E-86** [comment]
> Feel free to submit a PR.

https://github.com/doitsujin/dxvk/pull/2305
