### ISSUE TITLE
Allow to use all available threads to compile shaders via dxvk.numCompilerThreads

### ISSUE THREAD

**Issue by tannisroot** [doitsujin/dxvk#2237]
If you have a weak CPU, for instance, a 4 Core Pentium CPU with no hyperthreading, in a game like Overwatch, it can take up to half an hour to compile all the shaders from a state cache with 42000 valid entries.
From my understanding, on such a system, DXVK will only use 2 threads out of available 4, thus unnecessarily increasing the time it takes to compile shaders. Seeing how the game is unplayable during that time anyway, it would make more sense to use all available threads to accomplish the task to get it to the playable state faster.
And unfortunately, to do so via `dxvk.numCompilerThreads =`, you need to know how many threads are available on a given system, which can't be determined very easily via something like a Lutris install script.
So if possible, it would be very nice if `dxvk.numCompilerThreads =` could be set to a value like `-1`, which would make it use all available threads instead of a number determined through a special formula in DXVK.

**Comment by doitsujin** [comment]
This would arguably improve the situation for weak CPUs but would also make the game completely unresponsive for everyone else where shaders *can* otherwise be compiled in the background in a couple of minutes while clicking through menus etc. Using all available threads for compiling is just a bad idea especially on systems with >8 logical cores and CFS kernels.

There's no way to make everyone and every game happy on every system in every situation, and I don't really want to add an Overwatch-specific heuristic. Maybe just ship a patched DXVK with Lutris or something that handles this, but I don't see a good reason to have this upstream when it's really just cucks a different set of users.

**Comment by mirh** [comment]
Can't you just set the shader compiling threads to a lower priority?

**Comment by mirh** [comment]
[I see](https://bugs.winehq.org/show_bug.cgi?id=26549).

**Comment by SveSop** [comment]
Running wineserver with higher/lower thread priority won't achieve what you are aiming for i think.. ref to the link you posted. `STAGING_RT_PRIORITY_SERVER` as i understand it's usage will only make the wineserver process itself run at a different prio/nicelevel, not actually make different threads from windows apps run at different prio's THROUGH wineserver. (Horrible explanation.. i'm not good at this)

Proton got some patches involving things like [https://github.com/rbernon/wine/commits/develop/server/thread.c](https://github.com/rbernon/wine/commits/develop/server/thread.c) but i am not sure if this is just somewhat of an elaboration of the aforementioned PRIORITY_SERVER mechanic...

**Comment by IsaacORP** [comment]
can i change the dxvk.numCompilerThreads = on windows?
