### ISSUE TITLE
Assassin's Creed 1 through Revelations bouncing image issue

### ISSUE THREAD

**Issue by brad86m** [doitsujin/dxvk#2249]
When using DXVK with Assassin's Creed 1 to Revelations, the image bounces around. 2D elements are fine, but anything 3D goes nuts. Tried some setting in the config, but couldn't find one that worked.

https://user-images.githubusercontent.com/84683672/130040661-3ce0321e-fa8c-462d-bd55-0046ee92f0a6.mp4

Log file:
[ACRSP_d3d9.log](https://github.com/doitsujin/dxvk/files/7013141/ACRSP_d3d9.log)

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by brad86m** [comment]
> 
> 
> Please make an apitrace.
> https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

**Comment by brad86m** [comment]
Cannot create a trace file as the games are unable to start when those files are present with the game exe.

**Comment by K0bin** [comment]
I can't reproduce the problem. Either way, please retest with DXVK master.

**Comment by doitsujin** [comment]
Doesn't really look like a graphics issue but rather an input issue?

**Comment by brad86m** [comment]
I have tried the latest master, no change. Tried everything on my end, including running on a different PC. The issue persists.

**Comment by K0bin** [comment]
Unless you manage to produce an apitrace that can reproduce the issue, there's nothing we can do.

FWIW, I had no issues at all making one. But both the apitrace and the game itself worked just fine without that problem.

**Comment by brad86m** [comment]
I'm having this issue with every AC game before Black Flag. The wrapper works great with other older DX9 games. Works fine without it, so there must be some issue with the wrapper, since it wouldn't conflict otherwise.

**Comment by K0bin** [comment]
The log file is completely useless. I need an apitrace.

**Comment by brad86m** [comment]
Damn. I can't generate one as the games refuse to start with it :/

**Comment by K0bin** [comment]
Make sure you disable the Uplay and Steam overlays.

**Comment by brad86m** [comment]
Managed to get apitrace to run with the game, but how do I use DXVK alongside it, since they both have the same dll name ?

**Comment by K0bin** [comment]
You don't need to use DXVK alongside it. Please upload that apitrace.

**Comment by brad86m** [comment]
Done :) I let it go into the gameplay for a few seconds

Compressed and uploaded to MediaFire. Hope that is fine. I do not have access to more premium cloud storage services.

[https://www.mediafire.com/file/6do6yvodfb0mo9c/ACRSP.7z/file](url)

**Comment by K0bin** [comment]
Unfortunately, I can't reproduce the problem with that apitrace either.

**Comment by brad86m** [comment]
Any idea what I should be looking at to try and find the cause of the problem ?

**Comment by K0bin** [comment]
Turn off all overlays and disconnect all controllers and other input devices.

**Comment by brad86m** [comment]
Tried all that, except booting the machine without my mouse, which I will try now.

**Comment by brad86m** [comment]
No good. That's on two different PC's with every single input device and USB device disconnected, other than a keyboard.

Input device can be ruled out.

**Comment by Ryusennin** [comment]
I don't know what your system config is, but I tested AC Brotherhood on my Ryzen + Vega with latest drivers and default DXVK conf file. The game works fine on both Win10 and Win7, I just noted some odd shadow banding here and there.

**Comment by brad86m** [comment]
My system config is I5 2400 / GTX 960 / Win10. And the other computer is a Ryzen 3700x / RTX 3070 / Win 10.

The issue happens with both computers, and considering they are completely different set-ups, the issue can't be isolated to just myself.

**Comment by Ryusennin** [comment]
Just noticed something in your video.

If you look closely at your minimap in the lower right, you can clearly see the map spinning back and forth. It's not a video buffer bug, the camera is actually moving. Somehow it looks more like an input issue. Some driver or software could conflict with the games, even if the device is unplugged.

**Comment by netizener** [comment]
Same bug happening with me, both in Windows 10 (only when using DXVK) as well as Manjaro Linux 21.1.3. I'm using the Ubisoft Connect version of the game (Assassin's Creed 2).
@doitsujin can we please reopen this issue, because it seems to be happening with DXVK even on Windows 10?
I'm using a Geforce 940MX which does support Vulkan.

**Comment by K0bin** [comment]
Doesn't change the fact that we cannot reproduce it though.

**Comment by netizener** [comment]
@K0bin added the dx9 api trace for the windows version. couldn't add the dxvk trace because the trace d3d9.dll replaces the dxvk d3d9.dll, but i've added before and after dxvk traces for a fresh installation of the game.
also added a dxdiag for my system if thats also required.
link : https://github.com/netizener/ac2_trace/releases/tag/1
please ping me if you need any other requirements for this issue to be fixed.

**Comment by K0bin** [comment]
I specifically need an apitrace that has shows bug. I don't think a Windows d3d9 will do that.

**Comment by doitsujin** [comment]
If this is supposed to be our problem then we really need more info here, there **must** be something unique about your system or game configuration since literally no one else seems to have ever had this issue and no one here can reproduce it. What input devices do you have connected to the system? Which fullscreen mode are you using? Anything else that's different from your average desktop PC?

I'm not going to rule out some window message or cursor nonsense going on (although according to the trace, the game doesn't use the cursor APIs), but unless we can reproduce this on our end, we will not be able to fix this.

**Comment by brad86m** [comment]
Has there been any progress on this ? - I have put together a whole new PC since I first opened this issue, and I get the same exact issue on my latest build.

**Comment by K0bin** [comment]
I was never able to reproduce this.

**Comment by K0bin** [comment]
It was mostly about Revelations. That's what was shown in the video in the original post. I tried that and its fine.

**Comment by Blisto91** [comment]
Roger. I will try to give it another shot myself.

**Comment by doitsujin** [comment]
> Has there been any progress on this ?

No, the issue is still unique to your systems.

**Comment by brad86m** [comment]
> > Has there been any progress on this ?
> 
> No, the issue is still unique to your systems.

Unique to a low number of people and their setups, but still an issue nonetheless.
There is a conflict between some hardware/software and dxvk. 

Ignoring it just because it doesn't affect everyone isn't good. Just leads to other issues that get ignored down the line before people move on completely.

**Comment by Blisto91** [comment]
fwiw this issue seems to also happen for some windows users without dxvk.
Try to see if the workaround the devs have posted helps.
https://steamcommunity.com/app/201870/discussions/1/3114770913767276898/

But i'm still gonna try and see if i can reproduce dxvk being a trigger of it on my two setups.

**Comment by K0bin** [comment]
Gonna close this as a game bug. If anyone ever finds out what triggers this, I might look into this again but apparently this also happens without DXVK on some systems.

**Comment by brad86m** [comment]
> fwiw this issue seems to also happen for some windows users without dxvk. Try to see if the workaround the devs have posted helps. https://steamcommunity.com/app/201870/discussions/1/3114770913767276898/
> 
> But i'm still gonna try and see if i can reproduce dxvk being a trigger of it on my two setups.

No issue on my PC builds without DXVK. Only happens one I start using it, which is essential for me see the early game are very CPU intensive, and even a 3700x can't hold 60fps in crowded areas. DXVK takes away that CPU overhead massively, by the looks of things. 

There is a compatibility issue somewhere that is triggered by DXVK. Sadly, with the issue getting closed, it doesn't look like it will get looked into further.

**Comment by Blisto91** [comment]
Did you try the work around anyway to confirm it's the same issue?
Not saying dxvk can't trigger it 🙂

**Comment by brad86m** [comment]
I did indeed. Renaming or deleting the system detection dll doesn't help. Also, Revelations is the only one that uses this dll file. AC1,2, BH do not use it.

**Comment by Blisto91** [comment]
I have tried again to reproduce in assassins creed 1 again both on linux and windows, but i have been unable to.
Setup and repro details:
Nvidia 960, 516.59 driver, no GeForce experience installed (so no overlay), dxvk 1.9.1, launched both through steam and direct through exe, both dx10 & dx9, two monitors connected and main one i tried switching between 165hz and 60, tested ingame at various resolutions and with vsync on and off, only a mouse connected.

I see this thread which might be the same issue for assassins creed II where people have posted stuff that worked for them. If it is the same issue then varoius things seems to do it for people. Tho might be something else.
https://steamcommunity.com/app/33230/discussions/1/3124911622551657021/

**Comment by brad86m** [comment]
I have tried all the common solutions that have been posted in steam and Ubi forum threads. Nothing has worked outside removing DXVK itself, which is obviously not what I want to do as I need it to relieve CPU overhead, which is a major issue in these games.

**Comment by brad86m** [comment]
Okay. Another new AMD PC build for home, and my Intel/Nvidia based system at work still have the same issue. All computers I have tested since originally opening this issue have been using different hardware, peripherals, and different versions of Windows, and drivers. Same result every time.

This not an isolated problem, and affects anyone trying to run DXVK with Assassin's Creed II,BH,REV (and maybe later titles. I haven't tried them) on Windows.

Linux works fine.

**Comment by Blisto91** [comment]
It's hard to look into if we're unable to reproduce it.

I have a new setup now so gonna give it a quick shot. But don't have too high expectations of the devs spending too much time looking into what seems like a game bug that only happens on Windows.

**Comment by K0bin** [comment]
@brad86m We cannot reproduce the issue, so we can't fix it.

**Comment by Blisto91** [comment]
Haven't checked on new setup yet. Will qrite here when I've tried

**Comment by HonScottoSolo** [comment]
#3546 I have found out what the bug was.

**Comment by brad86m** [comment]
> #3546 I have found out what the bug was.

This is NOT the issue. It is still a relevant bug to many people.

**Comment by Samsung466** [comment]
The issue is still there sadly there is a conflict between dxvk and the early AC games for some reason...

**Comment by justdumbgamer** [comment]
Tried Direct3D9On12 wrapper for Direct3D 9, game bouncing same.
https://github.com/elishacloud/dxwrapper

**Comment by anantoarefin** [comment]
Well, I'm facing the Same Issue. The Screen is shaking as shown in the video. For me, it was on Assassin's Creed II. Notes to be taken that I am using Community Edition Remastered Mod. As soon as I remove the dxvk file, the game works perfectly fine. I am using dxvk for the 1st time on this game.

**Comment by Blisto91** [comment]
Windows Apitraces with and without dxvk of Assassin's Creed 2 https://drive.proton.me/urls/VDJ65YJD34#B0t1rvZd84Pg

**Comment by valentyn-l** [comment]
Same is happening on my end for ACII, ACB and ACR on Windows 11. I tried pretty much every combination of setting/fixes but nothing seems to affect this.

**Comment by DoucheCase** [comment]
Hello there.

> I'm not going to rule out some window message or cursor nonsense going on (although according to the trace, the game doesn't use the cursor APIs), but unless we can reproduce this on our end, we will not be able to fix this.

> I have tried again to reproduce in assassins creed 1 again both on linux and windows, but i have been unable to.
Setup and repro details:
Nvidia 960, 516.59 driver, no GeForce experience installed on windows 10 (so no overlay), dxvk 1.9.1, launched both through steam and direct through exe, both dx10 & dx9, two monitors connected and main one i tried switching between 165hz and 60, tested ingame at various resolutions and with vsync on and off, only a mouse connected.

Mr. **Blisto91** previously tried to launch AS1 and everything works for him. On my device, versions dx9 and dx10 also work without problems. But AS2 works like for the author of this thread.

And also considering the words of **doitsujin**, I intend to try different launch parameters via dxwnd. Since for others, the game still launches on Vulkan without problems. I tried disabling the software for my X7 mouse - it did not help. Disabled all input devices in the device manager - it did not help. Now I am trying different input parameters and parameters for the mouse. I am also trying windowed mode.

I think I will not find anything sensible. But the desire to play AS2 without freezes outweighs common sense.

**Comment by DoucheCase** [comment]
Sup gamer fellows.

Today I did a recording in apitrace in native d3d9 ([link to google drive](https://drive.google.com/file/d/17BISc4SEm2-cA-cl22CBWBF15_pt4d_z/view?usp=sharing)). And also spent the whole day recording the Vulcan version via GFXReconstruct and RenderDoc. But apparently it's useless... 

I'm attaching an image with GFXReconstruct parameters. RenderDoc refused to launch the game, possibly because it's 32-bit.
![ac2 vk trace](https://github.com/user-attachments/assets/39059ba0-2ed5-4be7-b72d-cadbb9503696)

Do these actions make sense in the context that this error is not reproducible?

Regards,
Andrew

**Comment by Blisto91** [comment]
We can reproduce it fine on Windows with Nvidia. We just have no idea what is going on with it besides it being some sort of weird game bug that can get triggered.
It happens the same with wined3d and 9on12 when i try to use those on Windows. Only dgvoodoo2 does not seem to trigger it for me.

**Comment by DoucheCase** [comment]
With dgvoodoo2 a strange thing happens on my device. After reinstalling the game and wrap to d3d12 - the camera does not bounce (but the fps is reduced by 2 times). But after switching to d3d11 and again to d3d12 bounces begin.

I can reproduce this (reinstall and wrap to d3d12) if you are interested.

PS. How did you managed to trace dxvk version via apitrace?

**Comment by Blisto91** [comment]
> PS. How did you managed to trace dxvk version via apitrace?

By pointing apitrace with the `APITRACE_FORCE_MODULE_PATH` env var at a folder where i put the dxvk dll
https://github.com/apitrace/apitrace/pull/638

**Comment by DoucheCase** [comment]
It doesn't matter if the authors manage to solve the camera problem in the PC Ezio trilogy, in any case DXVK is a huge and incredibly amazing project.

I wish all the best to the authors involved in the project, as well as those who leave bug reports.

Happy New Year.

Sorry for being off topic in this thread.

**Comment by K0bin** [comment]
That's very nice of you. Let me just say this: we'd love to fix it but at the moment we simply don't know what's causing it.

**Comment by valentyn-l** [comment]
> It doesn't matter if the authors manage to solve the camera problem in the PC Ezio trilogy, in any case DXVK is a huge and incredibly amazing project.
> 
> 
> 
> I wish all the best to the authors involved in the project, as well as those who leave bug reports.
> 
> 
> 
> Happy New Year.
> 
> 
> 
> Sorry for being off topic in this thread.

Indeed. Although if they did manage to fix this issue, it would single-handedly transform the experience of playing the Ezio trilogy on PC. The DX9 rendered implementation in all of these games is poor and stuttery.

**Comment by DoucheCase** [comment]
> > It doesn't matter if the authors manage to solve the camera problem in the PC Ezio trilogy, in any case DXVK is a huge and incredibly amazing project.
> > I wish all the best to the authors involved in the project, as well as those who leave bug reports.
> > Happy New Year.
> > Sorry for being off topic in this thread.
> 
> Indeed. Although if they did manage to fix this issue, it would single-handedly transform the experience of playing the Ezio trilogy on PC. The DX9 rendered implementation in all of these games is poor and stuttery.

This is Ubi's problem and they need to solve it. Maybe they'll make a remaster for the 20th anniversary or maybe not. All we can do is endure the freezes.

**Comment by anantoarefin** [comment]
Well something unexpected happened. I tried the x64 version dll for Assassin's Creed 2 and the screen flicker is gone. But don't know if the dxvk is working or not.

**Comment by Blisto91** [comment]
It isn't working no. The game is 32bit and so need the 32bit DLLs

**Comment by valentyn-l** [comment]
> > Indeed. Although if they did manage to fix this issue, it would single-handedly transform the experience of playing the Ezio trilogy on PC. The DX9 rendered implementation in all of these games is poor and stuttery.
> 
> 
> 
> This is Ubi's problem and they need to solve it. Maybe they'll make a remaster for the 20th anniversary or maybe not. All we can do is endure the freezes.

Does it work under Linux though? Yes, yes it does. 

As such, it should work under Windows too.

[](https://youtu.be/ku_iFMT8fEw?si=xBDSfhC0-6bWCs68)

**Comment by valentyn-l** [comment]
More [evidence](https://www.youtube.com/watch?v=UFbKOUD4FKE&t=611s) that AC: Brotherhood also works under Linux.

As a matter of fact, I installed Linux to try it out myself and there is 0 issues there running either game. I'm sure Revelations is no different.

I am convinced that this is an issue with the camera vectors being scrambled as when you try punch an NPC in DX9 the camera shakes, but it naturally shakes MUCH more intensely under DXVK. 

I also noticed that AC: Brotherhood has less input options under Linux than it does under Windows. Might be a biproduct of Wine emulation, but it could also point to a bug with inputs on Windows.

**Comment by DoucheCase** [comment]
Could you share your config file for AC2 after launching on liunx?
It shoud store here: C:\Users\%USERNAME%\AppData\Roaming\Ubisoft\Assassin's Creed 2

PS. I also going to install linux as I get a hard drive

**Comment by valentyn-l** [comment]
> Could you share your config file for AC2 after launching on liunx? It shoud store here: C:\Users%USERNAME%\AppData\Roaming\Ubisoft\Assassin's Creed 2
> 
> PS. I also going to install linux as I get a hard drive
[ACII ACB Linux config.zip](https://github.com/user-attachments/files/18269765/ACII.ACB.Linux.config.zip)

Going to try running the games with these.

**Comment by valentyn-l** [comment]
Changing the configs did nothing. I also tied forcing various "d3d9.customDeviceId =" and "d3d9.customVendorId =" in dxvk.conf, to no avail.

**Comment by DoucheCase** [comment]
> I also noticed that AC: Brotherhood has less input options under Linux than it does under Windows. Might be a biproduct of Wine emulation, but it could also point to a bug with inputs on Windows.

What you mean? Are you talking about selecting a control type? In your config file I see that the number of input types is the same as mine.

Today I tried to completely remove all input types except keyboard + mouse (2 buttons) and Bluetooth gamepad, but this did not help solve the issue with camera shaking. The fields with the key value for the removed types were equal to "undefiend". I could not completely remove other input types.
![изображение](https://github.com/user-attachments/assets/a6820ccc-bc92-437d-adab-c1fd3634ec68)

**Comment by valentyn-l** [comment]
> > I also noticed that AC: Brotherhood has less input options under Linux than it does under Windows. Might be a biproduct of Wine emulation, but it could also point to a bug with inputs on Windows.
> 
> 
> 
> What you mean? Are you talking about selecting a control type? In your config file I see that the number of input types is the same as mine.
> 
> 
> 
> Today I tried to completely remove all input types except keyboard + mouse (2 buttons) and Bluetooth gamepad, but this did not help solve the issue with camera shaking. The fields with the key value for the removed types were equal to "undefiend". I could not completely remove other input types.
> 
> ![изображение](https://github.com/user-attachments/assets/a6820ccc-bc92-437d-adab-c1fd3634ec68)
> 
> 

I noticed that ACB had 3 input option under Linux, while it had 5 under Windows (extra mouse and keyboard options).

I am testing some other things atm to see if it helps

**Comment by DoucheCase** [comment]
For me, camera shaking is not related to input. I noticed that when using DXVK the boat seems to reset its position. If it was just the camera, the boat would remain motionless.
[AC2 gameplay with DXVK](https://youtu.be/-1G_qQUa6Hc)
[AC2 native gameplay](https://youtu.be/rIhAL1PJxcg)

**Comment by anantoarefin** [comment]
I don't know why The Game does not open now. it closes after showing the Black Full Screen Window. I am using Intro Skip trick.

**Comment by Dhruv-cli** [comment]
Maybe the title should be changed a bit (if it can be, idk if GitHub allows that), because this shaky-camera issue is also present with Assassin's Creed 3 when using DXVK on my PC. My specs are i5-13600K, RTX 3060 12GB, 32GB of DDR5 5200 MT/s RAM, and I thought I should also mention that I'm using a 75 Hz 1080p Dell S2421HN display, if that's helpful in any way. I should also mention that I'm using Nvidia's legacy DSR to downsample the game from 1080p to 4K.

**Comment by K0bin** [comment]
> because this shaky-camera issue is also present with Assassin's Creed 3 when using DXVK on my PC.

@Dhruv-cli Are you sure about that? This issue keeps getting weirder. 
What makes this even more curious is that Assassins Creed 3 uses D3D11 unlike Assassins Creed 2, Brotherhood and Revelations. So the bouncing camera would have to be something deep in the DXVK code which is unlikely with this kind off issue or it's some outside influence.

**Comment by Dhruv-cli** [comment]
Yes, I am sure (and yes, I am of course talking about the original version of the game and not the "Remastered" version). Revelations also suffered from this same issue on my PC, but that was fixed by just deleting or renaming the systemdetection.dll file, although I didn't test DXVK on Revelations. I tested it out with this game in particular because PCGamingWiki suggested it and went down a rabbit hole to try and figure out what is causing this with this game in particular. I have looked around the web trying to find ways to force DX10 in this game since that should technically be supported according to the minimum requirements specs, and PCGamingWiki recomended it. I should mention that this issue starts right as you boot up the game, that is to say that it is present even in the main menu before you even start the game. I don't know if I should post external links here, but I have also tried some Windows 10 SDK thing which had a program called dxcpl.exe to try and force DX10 but that didn't help either, at least not according to RTSS since it still shows D3D11 alongside the FPS.

**Comment by Dhruv-cli** [comment]
I don't know how, but I forgot to mention that I'm using a fairly rare edition of Windows 10 with which I'm playing AC3, it is Windows 10 Enterprise IoT LTSC 2021 (v21H2, build 19044.xxxx). That being said though, I don't think even that should be causing this issue, as in [this video](https://www.youtube.com/watch?v=iyCrx2kREmQ), the guy is also using the same version that I'm using and his game seems to be running just fine.

**Comment by Dhruv-cli** [comment]
I can't upload my video on this issue/thread. It is telling me:-

**Comment by Dhruv-cli** [comment]
Please check out the following links for attached videos:-

Here's the game with DXVK v2.2 (which is the most recent version that was available at the time when the aforementioned video was published: https://drive.google.com/file/d/1NbHvISr1lsaAe0jVKIf9Z0vsh0BBc-fC/view?usp=sharing

Here's the game with latest version of DXVK v2.5.3: https://drive.google.com/file/d/1ViRI13-Sp_ecIDBNYwDdfx3I3kCBS1V-/view?usp=sharing

As you can see, while this problem still persisted in the older version of DXVK, at least on my system, it is much worse in the latest version.

**Comment by AkiraJkr** [comment]
Assassin's Creed 2.

Observing the problem individually when the camera starts bouncing--Yes, it is **some kind** of input issue with DXVK vs this game. But the funniest thing about this is--completely getting the game rid of inputs doesn't work, at all.
I managed(if only briefly since this game is finicky to get working with dxvk) to get Special K working with dxvk x dxgi interop, and used the Input Management to test this out.
Videos down below.
https://drive.google.com/file/d/1tgyq2Pg0o2fQAiV0l0OgUTqVbv-sBVJM/view?usp=sharing
https://drive.google.com/file/d/19pWPCrQZxLbonoPK0qZHUaua_AqS8Cv_/view?usp=sharing

**Comment by K0bin** [comment]
@Dhruv-cli This has nothing to do with this issue here. Please open a separate issue.

**Comment by K0bin** [comment]
I played around with this again. I tried Assassin's Creed 2 in particular (because I still had that installed).

It still works perfectly fine with DXVK and despite experimenting with a few things, I simply do not have this bug.

**Comment by DoucheCase** [comment]
> I played around with this again. I tried Assassin's Creed 2 in particular (because I still had that installed).
> 
> It still works perfectly fine with DXVK and despite experimenting with a few things, I simply do not have this bug.

does the version of installed directx 9 matter? and does its installation matter?

**Comment by K0bin** [comment]
> does the version of installed directx 9 matter? and does its installation matter?

There is no such thing. On Windows D3D9 is a system component and DXVK basically replaced that for a game when you install it.

**Comment by valentyn-l** [comment]
> I played around with this again. I tried Assassin's Creed 2 in particular (because I still had that installed).
> 
> It still works perfectly fine with DXVK and despite experimenting with a few things, I simply do not have this bug.

What's your Windows version? Also, it might be useful to look at what other software is installed on your system as it might be causing this glitch on other people's systems, including mine. Since Wine in Linux emulates a barebones version of Windows, it really does raise the question of what component is causing this. Perhaps a VS redistributable package?

**Comment by K0bin** [comment]
I didn't use Windows. I tried it on Linux.

**Comment by valentyn-l** [comment]
> I didn't use Windows. I tried it on Linux.

Lmao. It obviously doesn't have that issue on Linux!

We are talking about Windows. This issue has only crept up on Windows afaik.

**Comment by K0bin** [comment]
Someone mentioned they also hit it on Linux.

**Comment by Dhruv-cli** [comment]
If it is useful at all in any way, I did check out AC3 Remastered, and that game doesn't seem to have any of these screen shaking problems, at least on my PC.

> > [@Dhruv-cli](https://github.com/Dhruv-cli) That water problem has nothing to do with this issue here. Please open a separate issue.
> 
> I'm sorry about that, but this is actually more of a problem with my video showcase. I didn't showcase it correctly, it would start shaking the screen heavily when I go in a close-corner area or do any of the naval missions in the game. I did however showcase that, in the earlier version 2.2, the main menu wasn't shaking but in the newer version, even the main menu is shaking heavily.

**Comment by Anathemix** [comment]
> What makes this even more crazy is that it also happens with Assassin's Creed 3 which unlike AC2 - Revelations uses D3D11, so there's a lot of code that's different compared to whats executed when you run the earlier games with DXVK. It just shares the lower levels of DXVK and bugs there wouldn't lead to problems like this one.

So, after reading this topic, I have reproduced the issue in "Revelations" addon and also even in Assassin's Creed 3 (and I guess that "Brotherhood" addon could be in this list too, did not tried it).
Obviously, this bug caused by Ubisoft engine (at least on Windows and in several their games), independent of the render type or DXVK version.

BTW, I noticed several funny features of the bug: when Ezio beats peaceful people with fists, the camera gets INSANE shaking for a moment! It is as if a shake multiplier is being triggered. **Thereby, I guess, it's something related to camera effects.**
One more notice it's the interface of AC2 with DXVK enabled. All its elements stay flat, but only radar icons are trembling. WTF!?
At last, I'm also using ReShade addon that is running and working well in all of these games, without any similar problems. It also runs with DXVK altogether and shows almost all depth buffers with the same trembling.

So, If my guess is true, the solution of this issue could be disabling/adjusting camera effects in the game engine. But how we can do it? Maybe somewhere exists a mod with useful tweaks for AC series...

**Comment by AnantoArafin** [comment]
> > What makes this even more crazy is that it also happens with Assassin's Creed 3 which unlike AC2 - Revelations uses D3D11, so there's a lot of code that's different compared to whats executed when you run the earlier games with DXVK. It just shares the lower levels of DXVK and bugs there wouldn't lead to problems like this one.
> 
> So, after reading this topic, I have reproduced the issue in "Revelations" addon and also even in Assassin's Creed 3 (and I guess that "Brotherhood" addon could be in this list too, did not tried it). Obviously, this bug caused by Ubisoft engine (at least on Windows and in several their games), independent of the render type or DXVK version.
> 
> BTW, I noticed several funny features of the bug: when Ezio beats peaceful people with fists, the camera gets INSANE shaking for a moment! It is as if a shake multiplier is being triggered. **Thereby, I guess, it's something related to camera effects.** One more notice it's the interface of AC2 with DXVK enabled. All its elements stay flat, but only radar icons are trembling. WTF!? At last, I'm also using ReShade addon that is running and working well in all of these games, without any similar problems. It also runs with DXVK altogether and shows almost all depth buffers with the same trembling.
> 
> So, If my guess is true, the solution of this issue could be disabling/adjusting camera effects in the game engine. But how we can do it? Maybe somewhere exists a mod with useful tweaks for AC series...

Good to know that its Games Engine problem and not any other issue hopefully.
Would you like to try some renowned forks of DXVk to see of those works properly. On the other hand they are based on the dxvk so don't know for sure.

- https://gitlab.com/Ph42oN/dxvk-gplasync/-/releases (Use case when Official dxvk stutters)

Lagacy DXVK (For old Gpu's)
- https://github.com/pythonlover02/DXVK-Sarek/releases
- https://github.com/doitsujin/dxvk/tree/v1.10.3
- https://github.com/Sporif/dxvk-async/tree/1.10.3

DXVK.conf lines
d3d9.maxFrameLatency = 1
d3d9.presentInterval = 1
d3d9.numBackBuffers = 3

DXVK.conf lines (if using DXVK gplasnyc or async)
dxvk.enableAsync = true
dxvk.gplAsyncCache = true

DXVK.conf lines (Might speed up shader compilation)
dxvk.numAsyncThreads = 4
dxvk.numCompilerThreads = 4

**Comment by Mrblubb** [comment]
I can confirm the issue still persists on AC Brotherhood I installed yesterday. Even the main Title Screen shakes where you have to press enter. Would be nice if it gets fixed.

**Comment by K0bin** [comment]
> Would be nice if it gets fixed.

It doesn't happen on Linux and we don't have a clue why it happens on Windows.
The games camera logic is broken. It's a game bug that DXVK somehow triggers.

**Comment by Mrblubb** [comment]
Is it confirmed ? I think its something else as it happens on the title screen where you see AC Brotherhood. So it has to be some other bug.

**Comment by DoucheCase** [comment]
> Is it confirmed ? I think its something else as it happens on the title screen where you see AC Brotherhood. So it has to be some other bug.

Mate, don't bother dxvk developers. Better ask ubi what happens with camera.

**Comment by Mrblubb** [comment]
I guess better play with dx9 as game is old and ubi is not the same we used to know

**Comment by K0bin** [comment]
> Is it confirmed ? I think its something else as it happens on the title screen where you see AC Brotherhood. So it has to be some other bug.

It is confirmed that the game passes us a camera matrix that does those weird jumps. The UI is not impacted. It's something that we have no influence over, the game just passes us a bunch of numbers and those happen to be a broken camera matrix.

Besides that, it doesn't happen on Linux and that's basically the only thing that matters for DXVK.

**Comment by Mrblubb** [comment]
Hmm. Was this always a bug ? I mean are there any older dxvk versions that work with this game without this bug ?

**Comment by K0bin** [comment]
I have no idea and I have wasted too much time on this issue already.
If someone figures something out, I'd be happy to take a look but until then I'm not planning to mess with AC with DXVK on Windows again.

**Comment by doitsujin** [comment]
Removed comment above. Daily reminder that we **do not support piracy** or any sort of cracked game versions for reasons that I hopefully don't need to explain.

Anyway, it's not like we don't want to fix the problem, but nobody understands what's going on and everything points to this being a game bug.

**Comment by hartapfel** [comment]
Hey guys, I'm just adding to this thread. I also tried using DXVK for AC Brotherhood and I also have the exact same camera flickering issue. And it's already visible in the main menu as someone mentioned.
