### ISSUE TITLE
AC Odyssey: Dust & Fog-like effects with a white or black "glow" during nighttime or in dark interiors.

### ISSUE THREAD

**Issue by JMD13** [doitsujin/dxvk#2326]
Some dust, smoke/fog type effects like from fires or footsteps have a white "glow"  or are completely black when the environment is dark (during night or inside caves and dark interiors).

### Software information
AC Odyssey, High Preset with Low Antialiasing and Medium Clouds.

### System information
- GPU: rx 470 4gb
- Driver: 21.10.1
- Wine version: none im on windows 10 21H1
- DXVK version: 1.9.2

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/7305214/ACOdyssey_dxgi.log)
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/7305215/ACOdyssey_d3d11.log)

**Comment by Ryusennin** [comment]
I sent a detailed bug report to AMD a few weeks ago with a link to this discussion, but so far didn't get any feedback.

Curious that the issue seems to happen on native Win11 as well. On Win10 + DXVK, the situation has become worse with every recent Radeon driver. The white and black glows happen at night everywhere there are particles of dust, especially around the mountains of Sparta. It's unplayable.

![Assassin's Creed Odyssey_2021 12 06-18 27](https://user-images.githubusercontent.com/9519544/145328337-f646d0df-f4b1-4f7e-ae4a-f4bf384540f9.png)

**Comment by Ryusennin** [comment]
9 months after the last working Radeon driver (21.5.2), I am happy to report that Odyssey finally works _again_ with DXVK 😭

You need the newest 22.2.1 beta driver, which introduces support for Vulkan 1.3. Confirmed to work on Win10 (no issue with Win7, since Radeon 21.5.2 was conveniently the last official driver for that OS).
