### ISSUE TITLE
Positive feedback about an interesting side effect of the vsync feature

### ISSUE THREAD

**Issue by Deus-nsf** [doitsujin/dxvk#2372]
Both dxgi.syncInterval and d3d9.presentInterval once set to 2, will as the doc suggests, double the frames so for example for a 144Hz monitor if a game runs at 63 FPS it will output 126 FPS to the monitor (the game will be internally locked at 72 FPS for 144 FPS max to the display of course).

This is VERY good, especially in an Adaptive Sync situation, because even if the game runs bad in some situations, dropping to let's say 35 FPS, then the monitor will recieve 70 FPS and not trigger the low framerate compensation (LFC) that can introduce stuttering, and so the frequency of the monitor will stay higher at all times, giving better framepacing (because of no LFC), and clarity in motion (because modern panels are terrible at low refreshrates).

I love this and for complex games that are designed to run at low framerates (40-80) this is a huge improvement.
I have been using this even on Windows on some games to great effect for the games that can run with the DXVK dlls.

**Comment by Ryusennin** [comment]
Never had any issue with LFC. In which games did you notice stutter?

**Comment by RSF-Deus** [comment]
Every game which will trigger LFC will stutter as many tunes as LFC is truggered. 
If it is rarely, then it's just a few frame drops here and there. 
But there are many examples, like CPU bound games, where the 1% low framerates often goes below 50 FPS in spikes, and in this case, each spike will trigger a full frame of stutter because of LFC triggering in and out, making 2 frames that stutters.
And if the CPU is stressed, it is stutter land to the point where disabling Adaptive Sync is a better experience! 
Kingdom Come Deliverance is such a game, but basically any heavy sim that will stress the CPU will have this problem. 
Present interval 2 from DXVK helps with this issue quite a bit, changing the VRR range helps too but I don't know how to do that and keep it after restart on Linux like with CRU on Windows.
