### ISSUE TITLE
Resident Evil Revelations 2 (287290) stutters like hell

### ISSUE THREAD

**Issue by kassindornelles** [doitsujin/dxvk#2453]
the game has some severe stutters the whole time, it goes from a survival horror to a pure horror piece of videogame because of that. :frog:

### Software information
Resident Evil Revelations 2, Highest settings

### System information
- CPU: Ryzen 2400G
- GPU: RX 560D 4GB
- Driver: mesa 21.3.4
- Wine version: 7.0 RC6
- DXVK version: v1.9.3-9-ga268de51

### Apitrace file(s)
- DXVK APITRACE: (https://drive.google.com/file/d/1KKQ8YGRkv_gFXPK5UzSxmM_PUFuh-93M/view?usp=sharing)

### Log files
- d3d9.log: [rerev2_d3d9.log](https://github.com/doitsujin/dxvk/files/7925783/rerev2_d3d9.log)

**Comment by K0bin** [comment]
Might be related to #2084

**Comment by kassindornelles** [comment]
Note: same engine as RE0,RE1 remake
so might be related yes

**Comment by K0bin** [comment]
I sent Kassin a DLL to with direct buffer mapping mode disabled and he confirmed that it fixes the issue. So it is indeed the same problem as #2084.

**Comment by kassindornelles** [comment]
with that magic DLL the game runs smoothly, better than it ever runned on WIndows natively, that's pure magic and i'll play the game comfortably for the first time in my life, thank you kobin

**Comment by Storm3000** [comment]
> I sent Kassin a DLL to with direct buffer mapping mode disabled and he confirmed that it fixes the issue. So it is indeed the same problem as #2084.

Can you please send me that file to fix the stuttering? My game is stuttering a lot, and even more using dxvk.

**Comment by K0bin** [comment]
The fix was merged. Just get the latest build of DXVK.

**Comment by Storm3000** [comment]
I tried using the latest DXVK version. It seems working fine for a while, but the game still stutters a lot constantly. I've been playing 2 hours now and each new scenario begins to stuttering. Most of the time happens with the flashlight turned on, when I shoot an enemy, some explosion occurs or when I enter to a new room.

**Comment by Blisto91** [comment]
Sounds like regular shader stutter 👀

**Comment by Storm3000** [comment]
Yes and no. If I play the same episode again using dxvk, the game works almost just fine, I'd say even better than the vanilla version. But the stuttering appears here and there occasionally, mostly when I shoot an enemy, opening a door or any explosion occurs. Do I need to play all the game with dxvk to compile the shaders and fix the stuttering? Isn't any way to compile all shaders completely the first time I play it?

Also, I don't see any dxvk_cache file into the game's root. Is that normal?

**Comment by Blisto91** [comment]
> Do I need to play all the game with dxvk to compile the shaders and fix the stuttering?

To an extend yes since dxvk can't know before it encounters them the shaders that can be compiled into the cache.
Steam shader pre caching should help with some games. But i don't know the details of how well it works between different GPU's, drivers and game updates. Or how often the caches that steam provides are updated.

> Also, I don't see any dxvk_cache file into the game's root. Is that normal?

If you have steam shader pre cache enabled then yes that is normal. The cache is instead located in `~/.steam/steam/steamapps/shadercache/` and then the appID of the game. Along with driver caches.
If you turned off shader pre caching a cache file should appear in the games root folder or next to the exe in a sub folder yes.
If more complete caches are avaliable it might help https://github.com/begin-theadventure/dxvk-caches/tree/main/dxvk-caches But i'm not totally sure about that since i don't know technical details.

> Isn't any way to compile all shaders completely the first time I play it?

Good news on that front is that recently on the dxvk master branch there have been ongoing work into solving, or helping alot, this issue for a lot of games. With it, depending on how the game handles it, alot of the shaders should be possible to compile before seeing them directly in the game. Like loading screens or in the main menu. Pre built caches could probably also be provided for that.
Tho at the moment only the nvidia beta vulkan driver supports the extension required for it.
