### ISSUE TITLE
Is it possible to make sure that the cache in the game is not reset after restarting from the desktop?

### ISSUE THREAD

**Issue by Krovok** [doitsujin/dxvk#2482]
Hello.The fact is that almost all games on Vulcan slow down a lot, but if you play the game again, there are no brakes, but after re-entering the game, some brakes come back and some don't, is it possible to fix it? Tested on all versions of DXVK from 1.7.1 to 1.9.4.

Software information
In almost all games.

 System information
- GPU: GeForce GTX 1060 6GB
- Driver: 511.23.0
- Wine version: Windows 10 64bit
- DXVK version: 1.9.4, 1.9.3, 1.9.2, 1.7.3 1.7.1  (same behavior on all versions)

**Comment by K0bin** [comment]
Shader caches are managed by the driver and aren't reset when you restart. I don't understand what exactly you're asking for.

**Comment by Krovok** [comment]
In order for the game to stop slowing down with the volcano, it needs to be completed completely, but it's worth leaving the game and coming back, as some brakes come back.

**Comment by doitsujin** [comment]
Not sure which cache you're on about, shader caches are already persistent but obviously any other data stored in RAM gets lost when closing the game.

**Comment by SveSop** [comment]
@Krovok The NVIDIA driver uses a cache (driver controlled), that has a certain limit by default. This can cause the cache to be overwritten and possibly cause stutters if restarting the game, especially if playing more than just 1 game.

This can be controlled to a certain degree with some env variables: [https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/openglenvvariables.html](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/openglenvvariables.html)
Look under the _OpenGL Shader Disk Cache_ section.
You could perhaps improve the situation by setting 1 cache folder for each game you play - `__GL_SHADER_DISK_CACHE_PATH=/home/yourname/caches/thegame`

This way the nvidia shader is not being overwritten each time you play a different game or whatnot. DXVK handles its own cache, so that should not be a problem.
