### ISSUE TITLE
corrupted size vs. prev_size with Nvidia 495+ and DXVK 1.9.3+

### ISSUE THREAD

**Issue by Loacoon1** [doitsujin/dxvk#2504]
Star Citizen works very well with DXVK, except is some precise situations.
If using Nvidia 470.x, it works with basically any version of DXVK.
With Nvidia 495.x, it doesn't work with any DXVK.
With Nvidia 510.x if works with DXVK 1.9.2 and prior. But not with DXVK 1.9.3+.
Only one line seems relevant in the log attached : corrupted size vs. prev_size

We tried every game or Wine setting with the LUG with no difference except for one : 
When changing __GL_THREADED_OPTIMIZATIONS to 0 the error line changes to : malloc(): invalid next size (unsorted)
We are not sure if these error messages are related or two completely different errors.

### Software information
Star Citizen.

### System information
- GPU: RTX 2070
- Driver: 510.47.03
- Wine version: 7.1
- DXVK version: 1.9.3+

[log SC.txt](https://github.com/doitsujin/dxvk/files/8099055/log.SC.txt)

**Comment by doitsujin** [comment]
I'm not seeing any DXVK messges in that log, did you disable logging or does it crash before even calling into any of our code? Are you using the native Vulkan renderer perhaps (if that's even a thing yet)?

This sounds like an extremely painful issue since Star Citizen is not something I can test locally, and even if I could, this sounds like some sort of memory corruption that bleeds into the Linux side or happens within the Nvidia driver itself, and problems like that are exceptionally hard to debug. This could be caused by literally *anything* as well, including the driver, the game itself, or DXVK.

Couple of things you can do:
- try to run the game with Vulkan validation layers enabled and post a full log, to see if we're doing anything obviously wrong
- try to bisect the issue on 510.x to see which change between 1.9.2 and 1.9.3 broke it on these drivers

Would also be interesting if the game still works on AMD drivers.

**Comment by Loacoon1** [comment]
> I'm not seeing any DXVK messges in that log, did you disable logging or does it crash before even calling into any of our code? Are you using the native Vulkan renderer perhaps (if that's even a thing yet)?

No it's not a thing yet and no logging isn't disabled.
> 
> Couple of things you can do:
> * try to bisect the issue on 510.x to see which change between 1.9.2 and 1.9.3 broke it on these drivers

Someone in the LUG did it and says that this commit is the culprit : https://github.com/doitsujin/dxvk/commit/86148ec070628f5a89fbb0a91603bae2ce89529a

> * try to run the game through Valgrind and see if it complains about buffer overflows etc

I'm lacking time but I'll try to find a moment to do it.
 
> Would also be interesting if the game still works on AMD drivers.
Yes it does. And yes we think that the NV driver isn't innocent there. But we also think that DXVK does something 
specific to NV cards that triggers this crash (see the commit potentially responsible).

**Comment by doitsujin** [comment]
The code that was added quite literally doesn't do anything except enable some Vulkan extensions, it doesn't change DXVK's behaviour in any way at all as long as DLSS is not used.

Does https://github.com/doitsujin/dxvk/tree/sc-test help?

**Comment by doesthisusername** [comment]
Yes, it fixes it. I'm at 5/5 successful launches (A Hat in Time).

**Comment by doesthisusername** [comment]
Commenting just the `devExtensions.nvxBinaryImport.setMode(DxvkExtMode::Optional);` in the `if (enableCudaInterop)` block also works.

**Comment by Loacoon1** [comment]
> The code that was added quite literally doesn't do anything except enable some Vulkan extensions, it doesn't change DXVK's behaviour in any way at all as long as DLSS is not used.

Our thought is that the commit might do something that uncovers a Nvidia driver bug.

**Comment by doitsujin** [comment]
Yeah, but the point that I don't quite get is... why the heck does this only happen in specific games that don't even use DLSS?

**Comment by doesthisusername** [comment]
Yeah, it seems a bit strange. I looked up what `nvxBinaryImport` is, and it looks like it's a Vulkan extension that "allows applications to import CuBIN binaries and execute them."
`strings HatinTimeGame.exe | grep -i cuda` has one result, `?enableCudaAcceleration@Compressor@nvtt@@QEAAX_N@Z`. That might be a clue? I don't have other crashing games to look at though.

**Comment by RealTheSunCat** [comment]
Is it possible for me to manually apply this fix to Proton, before it gets merged?
I'm running into the same A Hat in Time crashes with Proton Experimental, and running AHiT with this fix applied seems to fix the crash, though with no Steam features (since I'm not launching through Steam to test it).

**Comment by doesthisusername** [comment]
@RealTheSunCat yeah, if you build Proton from source you can comment out that line in the DXVK submodule and `make install` it to Steam, that's what I'm doing. You can also compile just DXVK with the fix and overwrite Proton Experimental's DXVK files with the output, but then Steam's gonna replace those files every time it checks them since they're modified.

**Comment by TLATER** [comment]
@doitsujin would you accept a PR to put disabling that behind an environment variable? It's clearly misbehavior on the GPU side, but it would be nice to enable people who aren't capable of manually building dxvk to use more recent versions again.

I'm also assuming someone has flagged this to nvidia by now?

**Comment by gnusenpai** [comment]
I have been maintaining a DXVK build with the workaround on my [fork](https://github.com/gnusenpai/dxvk) that has been working for the Star Citizen LUG for some time now, if that might be interesting to anyone here.

**Comment by Blisto91** [comment]
Could any of you recheck on the newly released 520.56.06 Nvidia driver?

**Comment by char32** [comment]
@Blisto91 Just tested it with Star Citizen.
Unfortunately still the same problem with 520.56.06 (non-open version) and a RTX3060 by using dxvk v1.10.3.

**Comment by Nix-id** [comment]
have same problem with Star Citizen.
work with <= dxvk-1.9.2

RTX3080
Driver Version: 520.56.06

**Comment by Blisto91** [comment]
Yes a driver fix from Nvidia is needed afaik.

**Comment by SeongGino** [comment]
FWIW, can confirm that this issue is still affecting 525.60.11 (RTX 3060 Ti).

At least for AHIT, I made a semi-custom Proton version that uses symlinked files from whatever the latest Proton-GE version is (using Arch AUR's `proton-ge-custom-bin` package as my GE install), just with the relevant DXVK files replaced from @gnusenpai's fork, and the game boots consistently.

**Comment by tuantran1632001** [comment]
Have there any news about this? Currently facing the same issue with Watch Dogs 2. I tried to downgrade DXVK to 1.9.2, but it is still happening. Do I need to downgrade NVIDIA driver too?

**Comment by Blisto91** [comment]
@TheBill2001 Not yet besides that Nvidia devs are notified of the issue.

**Comment by Blisto91** [comment]
535 drivers have reached stable. Not every fix usually makes it to the release notes, so might be worth a try.

**Comment by SeongGino** [comment]
Gonna knock on wood as I say this, but I *think* this might be resolved in the current drivers?
Using 535.86.05, and tested with both Proton-GE and Experimental; launched it like eight consecutive times and it seems to consistently launch. But I can only say this with regards to A Hat In Time for now. Someone else advise for Star Citizen if they can?

**Comment by Gigas002** [comment]
Thanks for reporting this. Though I can't test Star Citizen, A Hat in Time indeed works fine for me too now

**Comment by Blisto91** [comment]
@Loacoon1 are you able to give this a spin in Star Citizen with the latest Nvidia drivers? 🙂

**Comment by Blisto91** [comment]
@Loacoon1 Friendly ping
