### ISSUE TITLE
The Evil Within 2 Texture square

### ISSUE THREAD

**Issue by Phazdelta** [doitsujin/dxvk#2540]
i have strange Bug Texture square everywhere i have AMD GPU 6900XT use the last 1.10 DXVK in win 11

![Sans titre](https://user-images.githubusercontent.com/101491081/158125657-c2c020ab-8147-43b9-8ae0-d2814ac1e2a9.png)

**Comment by dante3732** [comment]
![evilwithin_2023_04_02_14_20_25_151](https://user-images.githubusercontent.com/66036249/229352710-2a57b2b3-99c4-42f2-b93c-9816271909fd.png)
I have a similar one on the clothes in The  Evil Within 1 on VEGA 64.

**Comment by mbriar** [comment]
This never got fixed on windows vulkan drivers, amdvlk or amdgpu-pro. There is only a workaround in place on radv. Just don't use DXVK on windows for these games.

2 Apr 2023, 14:27 by ***@***.***:

**Comment by doitsujin** [comment]
FWIW you can work around this by disabling anisotropy via dxvk.conf, but then textures will look like arse, so yeah.

We literally cannot fix this on our end.

**Comment by Blisto91** [comment]
For amdvlk one could probably make a issue at their GitHub repository and maybe they'd be able to do something about it, since on Linux at least to be considered a good gaming driver there's a expectance of it working decently with both dxvk and vkd3d-proton.
On Windows (outside of some Intel Arc cases and to a certain extent Nvidia RTX Remix) it's not realistic to expect the driver devs to care or do any extra work for a third party translation library that doesn't even officially aim to be used on that OS. Which is totally fair imo. In these cases, where driver assistance is required, one should just use the native game on Windows.

**Comment by Blisto91** [comment]
Still shows here. Checked amdvlk

**Comment by Blisto91** [comment]
Made a amdvlk issue https://github.com/GPUOpen-Drivers/AMDVLK/issues/345

**Comment by Blisto91** [comment]
Issue have been fixed in Linux amdvlk 2024.Q1.1
It may (or may not. Nothing i control) make it to the Windows drivers also.

**Comment by Blisto91** [comment]
Issue is fixed in the [24.2.1 Windows driver release](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-24-2-1-helldivers-2)
