### ISSUE TITLE
can't get it to run in split second in windows 10

### ISSUE THREAD

**Issue by xSpecialFoodx** [doitsujin/dxvk#2554]
no matter where i put the dlls, i've tried in the root of the game, the directx folder of it, nothing works.

**Comment by doitsujin** [comment]
Just don't use it then.

If it just doesn't work at all on Windows it's almost always an issue with the game either not loading all the required DLLs or something on your system that's interfering / fucked up and not an actual bug that we could fix.

**Comment by xSpecialFoodx** [comment]
![תמונה](https://user-images.githubusercontent.com/78694958/160581514-6a570b16-0023-4616-abbd-90cadda97ba1.png)

**Comment by K0bin** [comment]
What are you trying to tell us with that?

**Comment by xSpecialFoodx** [comment]
![תמונה](https://user-images.githubusercontent.com/78694958/160584091-0e048a0d-c959-48c2-be1a-56925010ddc1.png)

**Comment by K0bin** [comment]
Okay so you did name the game. Congratulations. That means you've only left out the rest of the basic stuff that the issue template asked you to provide.

**Comment by xSpecialFoodx** [comment]
That means you guys dont read.

**Comment by Iglu47** [comment]
Probably we are talking about this game: https://store.steampowered.com/app/297860/ https://www.protondb.com/app/297860/
This is the 32-bit game (flag Large Address Aware is not set in exe file). Also seems the game directly depends only on `d3d9.dll` and `d3dx9_41.dll` and there are no renderer options - it's the dx9 game.

Since the bug on Windows has not yet been discribed (not even the text of the error window or screenshot), it looks like the best advice is to make sure `x32/d3d9.dll` from dxvk is being used.

It looks like the game on Proton has no problem starting with dxvk at least (I tried proton-5.0 with manually updated dxvk).

<details><summary>screenshot on Proton</summary>
<p>

![297860](https://user-images.githubusercontent.com/25866099/160662516-37ebdd30-faf4-4d67-b218-26bc68345e26.png)

</p>
</details>

offtopic: also the game has a developer/engine limit of 30 fps - could there be any practical reason to use dxvk on windows?

**Comment by xSpecialFoodx** [comment]
> Probably we are talking about this game: https://store.steampowered.com/app/297860/ https://www.protondb.com/app/297860/ This is the 32-bit game (flag Large Address Aware is not set in exe file). Also seems the game directly depends only on `d3d9.dll` and `d3dx9_41.dll` and there are no renderer options - it's the dx9 game.
> 
> Since the bug on Windows has not yet been discribed (not even the text of the error window or screenshot), it looks like the best advice is to make sure `x32/d3d9.dll` from dxvk is being used.
> 
> It looks like the game on Proton has no problem starting with dxvk at least (I tried proton-5.0 with manually updated dxvk).
> screenshot on Proton
> 
> offtopic: also the game has a developer/engine limit of 30 fps - could there be any practical reason to use dxvk on windows?

vulkan is more reliable than directx, i managed to run it with dxvk eventually, was a stupid bug i had.
