### ISSUE TITLE
ME3Tweaks Mod Manager doesn't render UI correctly

### ISSUE THREAD

**Issue by SuperSamus** [doitsujin/dxvk#2732]
ME3Tweaks Mod Manager, the mod manager for the Mass Effect saga, has problems rendering the UI with DXVK: it's completely black, but when moving the mouse in certain parts, sometimes the part of the UI the mouse is pointing at will briefly flash.

### Software information
The program can be downloaded here: https://github.com/ME3Tweaks/ME3TweaksModManager/releases/download/7.0.6.124/ME3TweaksModManagerExtractor_7.0.6.124.exe.
It needs to be executed to install it, then you can just launch the extracted file to reproduce the issue. 
(The latest version of the program doesn't work on Wine yet: [here](https://bugs.winehq.org/show_bug.cgi?id=53379), and [here](https://github.com/ME3Tweaks/ME3TweaksModManager/issues/299)).

### System information
- GPU: AMD Vega 6 (Ryzen 4500U)
- Driver: Mesa 22.1.1 (RADV)
- Wine version: 7.13
- DXVK version: 1.10.2

### Apitrace file(s)
The program just has to be opened to reproduce the issue, so the trace is small.
[ME3TweaksModManager.trace.zip](https://github.com/doitsujin/dxvk/files/9135564/ME3TweaksModManager.trace.zip) (Taken with WineD3D)

### Log files
[ME3TweaksModManager_d3d9.log](https://github.com/doitsujin/dxvk/files/9135594/ME3TweaksModManager_d3d9.log)

**Comment by mirh** [comment]
I don't think a .NET 5 application would rely on d3d9. 
If any, it's more likely that the problem may be with .NET 5 itself or WPF imo.

**Comment by Blisto91** [comment]
No it's because dxvk doesn't implement partial presentation and is a somewhat common problem with some game launchers as an example.
It can usually be worked around by setting `d3d9.shaderModel = 1` for the launcher which have been done in the past. That also works here.
But there are some cases where it isn't a desired workaround they might fall back on software rendering and become sluggish or maybe they launch from a temporary folder with a generic name where a config option wont catch them.

**Comment by jarrard** [comment]
> It can usually be worked around by setting `d3d9.shaderModel = 1` for the launcher which have been done in the past. That also works here.

This seems to work. Nice little solution for these mod managers and launchers.
