### ISSUE TITLE
YS Origin fps drops spikes in some areas 

### ISSUE THREAD

**Issue by Alejandro9509** [doitsujin/dxvk#2750]
Hello guys, in the YS Origin game in certain areas it is not very smooth even though it goes to 60 fps, since it has certain peaks in some areas , with WineD3D it works without problems, with DXVK only this problem occurs.

Here I link some videos and image 

![imagen](https://user-images.githubusercontent.com/103089262/180627261-44fb187b-6300-4d61-aa12-e0f6b78ea3bc.png)

DXVK: 
https://youtu.be/N6KvkuCskxc

WineD3D: 
https://youtu.be/7iMbyPyXwFU

YS: Origin 

### System information
- GPU: GTX 1060 6gb 
- Driver: 515.49.10 Vulkan beta drivers 
- Wine version:  Proton Experimental 
- DXVK version: 1.10.1, 1.10.2 and latest master 

### Apitrace file(s)
- https://drive.google.com/file/d/1SmKE46rGePpDxlWAgBy_-P7fm_Esm8UQ/view?usp=sharing

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Maybe try `d3d9.maxFrameLatency = 1` via the [config file](https://github.com/doitsujin/dxvk/wiki/Configuration) and play around with vsync if the game allows that. `DXVK_FRAME_RATE=60` might also help if you're using a high refresh rate display.

This is one of those presentation issues that we have little control over, not too uncommon with (poorly) FPS-limited games.

**Comment by Alejandro9509** [comment]
@doitsujin  With that option (d3d9.maxFrameLatency = 1)  in dxvk.conf the problem was completely fixed! Thank you!

**Comment by Blisto91** [comment]
Are you able to provide a save game of a area with the issue?

**Comment by Alejandro9509** [comment]
> Are you able to provide a save game of a area with the issue?

Sure.

This game does not have [Steam Auto-Cloud](https://partner.steamgames.com/doc/features/cloud#steam_auto-cloud) configured, which likely means save files are in [Steam Install]/userdata/{Steam3AccountID}/207350/ folder

in my case is 
/home/alejandro/.steam/steam/userdata/302435149/207350/

Here: 
[207350.zip](https://github.com/doitsujin/dxvk/files/9176224/207350.zip)

**Comment by Blisto91** [comment]
So i do notice there is something similar in the same spot yes. But only when i set my monitors refresh rate to 120 and turn on the games vsync. If i set the monitor to 60 i don't see anything. Neither if i turn off vsync or cap with dxvk framerate option.
And the stuff i do see is very minor and not nearly as bad as in your screenshot. This is with a amd R9 380 so maybe nvidia or something else is just acting worse for you :thinking: 

But good the config option works for you :slightly_smiling_face:

**Comment by Alejandro9509** [comment]
> So i do notice there is something similar in the same spot yes. But only when i set my monitors refresh rate to 120 and turn on the games vsync. If i set the monitor to 60 i don't see anything. Neither if i turn off vsync or cap with dxvk framerate option. And the stuff i do see is very minor and not nearly as bad as in your screenshot. This is with a amd R9 380 so maybe nvidia or something else is just acting worse for you thinking My gpu is also only at 22% there at 120fps.
> 
> But good the config option works for you slightly_smiling_face

its so weid, i have a 60hz monitor too, even with Vsync on or off, still happening, just with d3d9.maxFrameLatency = 1 fixed the issue.. 

I don't know if it's a problem with the KDE compositor  I didn't disable it, but it would still be interesting to set the game to 60fps and with the default option.

**Comment by Blisto91** [comment]
I have kde too. Tried both wayland and x11. Haven't toyed with the compositor either.
When i have time i'll try on the nvidia setup i also have access to and see how it behaves there.

**Comment by doitsujin** [comment]
Might just be an issue with presentation and the game's own FPS limiter running completely out of sync. Again, we've seen this before, part of the reason is that we present from one of our worker threads but don't usually synchronize right after unless the app's requested frame latency requires it, and the option kind of just works around that.

**Comment by Blisto91** [comment]
Okay i was testing some other stuff with dxvk on the nvidia setup (this was on windows) and decided to check this out.
I do see that the issue is much worse here and i recreate the same as you by either setting dxvk fps to 60 or refresh rate to 60. The option does indeed rid it.
I see the same at 165 refresh rate (vsync limited fps) but to a lesser degree. Here the option doesn't rid it fully but does lessen it. Probably ties together with what doitsujin said above.
The thing about the dxvk hud reporting 100% on nvidia seems to just be when vsync is enabled and isn't the actual gpu usage as windows system monitor reports in the low 10's and i dont hear the fan spinning up.

**Comment by sfjuocekr** [comment]
> Okay i was testing some other stuff with dxvk on the nvidia setup (this was on windows) and decided to check this out. I do see that the issue is much worse here and i recreate the same as you by either setting dxvk fps to 60 or refresh rate to 60. The option does indeed rid it. I see the same at 165 refresh rate (vsync limited fps) but to a lesser degree. Here the option doesn't rid it fully but does lessen it. Probably ties together with what doitsujin said above. The thing about the dxvk hud reporting 100% on nvidia seems to just be when vsync is enabled and isn't the actual gpu usage as windows system monitor reports in the low 10's and i dont hear the fan spinning up.

I've observed the same thing with vsync on, when a game hits the refresh rate the DXVK HUD will display 100% GPU usage when in fact it is just chilling at 50%.

**Comment by kellerman** [comment]
I have a very similar issue and also only setting maxFrameLatency to 1 helps. On KDE this isn't necessary, but on XFCE or Openbox WM there are lag spikes when GPU usage has reached 100%. Compositors turned off.
Nvidia GTX1660 with latest drivers on arch.
I had this issue on both some DXVK games (The Forest) and native Vulkan games (Valheim, Veloren). For DXVK there is this fix, but for native Vulkan games, for example, Valheim, the issue is there and the only way to fix them is to play on KDE. When the frame rate is limited and GPU doesnt reach 100%, then there is no lag spike.
Or using Gamescope fixes this, but this method introduces quite a bit of input lag.
