### ISSUE TITLE
Games crash on proton-experimental when using DXVK_FILTER_DEVICE_NAME

### ISSUE THREAD

**Issue by Zeioth** [doitsujin/dxvk#2868]
I'm experiencing this issue after upgrading to proton-experimental, or proton-ge 7.30 (7.26 works fine).

When I launch any game with the parameter:

    DXVK_FILTER_DEVICE_NAME="AMD Radeon RX 6700 XT" %command%

the game crashes. If I either disable the parameter, or I go back to protonge 7.26, the games work fine. Did you guys touched something related to this parameter? How could I provide you more info to debug this? Thank you.

**Comment by doitsujin** [comment]
We haven't changed anything. I don't know why changing Proton versions would break anything here.

Anyway, `DXVK_FILTER_DEVICE_NAME` ***ONLY*** works if the name you enter matches what your Vulkan driver returns, and if the driver in question also supports the feature set required by DXVK. Since you're probably trying to use AMDVLK or the proprietary driver, make sure to use the latest versions for Vulkan 1.3 support.

I also don't know which DXVK versions the respective proton-ge versions are shipping so I can't even tell you if an outdated driver would even be the issue here.

**Comment by Blisto91** [comment]
Yes as Doitsujin said make sure your drivers are up to date. Proton experimental and any GE version from 27 and up have bumped them. So I'm guessing this is that. 22.0 being the minimum for mesa radv now.
Remember that steam flatpak includes its own drivers if you use that.
If you want some more specifics then you need to post a dxvk log from a crashing game.

**Comment by Zeioth** [comment]
@Blisto91 was right on the money, I needed 'mesa-git' from AUR instead of 'mesa' from arch repos this time. It seems I got overconfident about the freshness of the packages just for being using arch lol. Thank you so much guys.

**Comment by Blisto91** [comment]
Regular mesa (radv) from the arch repos should work. I use that myself. 
mesa-git installs everything in one package so you most likely had something that wasn't up to date in a individual package. Or something was semi broken, who knows.

But glad you got it working
