### ISSUE TITLE
[d3d9] The Ship(2400) uses up all virtual memory and GPU memory and then crash

### ISSUE THREAD

**Issue by zzhiyi** [doitsujin/dxvk#2893]
After launch, the game gradually uses up virtual memory and GPU memory and then crashes, both on Proton 7.0 and on Windows 11. Even though the game is 32bit, it manages to use up 8G dedicated GPU memory and 8G shared GPU memory. And finally, running out of GPU memory, the game crashes. On Wine, the virtual memory limit is hit first and crashes. With native d3d9 on Windows or wined3d on Proton 7.0-4, the game runs normally. On Proton, you need to turn off the fullscreen hack first to get around its bugs.

### Software information
The Ship (SteamID: 2400)

### System information
- GPU: AMD RX5500 8G
- Driver: 30.0.15021.11005(AMD driver on Windows)
- Wine version: Wine 7.0
- DXVK version: 1.10.3

### Apitrace file(s)
[ship_d3d9_trace.zip](https://github.com/doitsujin/dxvk/files/9504077/ship_d3d9_trace.zip)

### Log files
- d3d9.log:[ship_d3d9.log](https://github.com/doitsujin/dxvk/files/9504074/ship_d3d9.log)

**Comment by K0bin** [comment]
Please try it with a DXVK config file like this:

`d3d9.memoryTrackTest = True`

**Comment by zzhiyi** [comment]
After using "d3d9.memoryTrackTest = True" the game can run correctly. What's weird though, I can't reproduce this bug after even turning on this option once. Now with "d3d9.memoryTrackTest = False" or no dxvk.conf, the game doesn't crash any more. I have to delete the game directory and reinstall the game to reproduce this. With DXVK master, the bug still persists.

**Comment by K0bin** [comment]
Some games create D9D textures until that fails to determine the amount of available VRAM.

The game probably does this once and stores the result somewhere.

D3D9 normally doesn't fail texture creation because that breaks texture mods for example. The option enables that. IIRC Microsoft has changed that behavior a couple of times and gotten a lot of backlash for breaking mods. I don't remember what they ended up with in the end.
