### ISSUE TITLE
Windows - Not able to run Assassin's Creed Origins; can't detect driver

### ISSUE THREAD

**Issue by adcanvedknightrepear** [doitsujin/dxvk#2906]
I've seen plenty of posts about the message displayed in game about unsupported driver being used, but this is different. I get the message on the loading splash screen before the game starts, saying that I don't have a video driver installed, or am using an unsupported video card. Haven't seen anyone with this issue specifically, and it seems like nearly everywhere I look DXVK runs perfectly fine with Origins.  I had just got done playing Odyssey and it worked perfectly fine with no issues at all. Attaching the created logs along with the error message.

[ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/9541491/ACOrigins_d3d11.log)
[ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/9541492/ACOrigins_dxgi.log)
![acoerror](https://user-images.githubusercontent.com/113266339/189504038-0acf9ff1-5682-4d30-861f-e794176e160d.jpg)

**Comment by Blisto91** [comment]
I think it might be because of your Intel iGPU.
Could maybe look like it is interfering. You could try to set the environment variable (not dxvk config file) so dxvk will only see your Nvidia GPU https://github.com/doitsujin/dxvk#device-filter
I think setting `DXVK_FILTER_DEVICE_NAME` to `NVIDIA GeForce GTX 1070` should work. Tho i have never used it before.

**Comment by doitsujin** [comment]
According to the log, the game successfully creates a device on the Nvidia GPU and then fails on what is presumably the Intel one, so yeah, setting `DXVK_FILTER_DEVICE_NAME` to `NVIDIA` should fix things.

**Comment by adcanvedknightrepear** [comment]
That was exactly it, works perfectly now. Thanks!
