### ISSUE TITLE
"New Vulkan extensions are not yet required" means ...

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#2963]
Hello.
Thanks for reading my topic.
In current version 1.10.3 has the information :
This is a minor maintenance release for an upcoming Proton release. New Vulkan extensions are not yet required.

New Vulkan extensions means video cards with driver having Vulkan 1.12 not will be compatible ?
Thanks for your reply.

**Comment by Blisto91** [comment]
Hello.
Yes from dxvk 2.0.0 (current master) vulkan 1.3 will be required. Some vulkan extensions have been made mandatory which bumps the minimum driver requirment. You can see supported drivers here https://github.com/doitsujin/dxvk/wiki/Driver-support

The 1.10.x versions will be the last ones that are backwards compatible. [The 1.10.x branch](https://github.com/doitsujin/dxvk/commits/1.10.x) have received a few backports from  master since the release of 1.10.3, but after 2.0.0 releases i don't think anymore legacy version will come out.
