### ISSUE TITLE
dxvk crash on mesa 22.2rc1 archlinux

### ISSUE THREAD

**Issue by vfioexperte** [doitsujin/dxvk#2991]
My system archlinux with mesa 22.2rc1.
dxvk crashed on start.
vkcube test working.

### System information
- GPU:Amd rx vega 64 and rx 580
- Driver: mesa 3d 22.2rc1
- Wine version: Proton custome ge 7rc37
- DXVK version: 10.0.3 async patched

### Apitrace file(s)
https://github.com/vfioexperte/wine_hardened_script/raw/master/Valley.trace

For instructions on how to use apitrace, see: ![dxvk_carshed_unigne_Valley_benchamrks](https://user-images.githubusercontent.com/62846024/195954505-f52accbf-614d-4543-9107-58a109ed3059.png)

### Log files
https://bugs.archlinux.org/task/76209

**Comment by Blisto91** [comment]
I'm sorry but maybe i'm misunderstanding something. Why are you making a bug report here and not at the mesa issue tracker.

**Comment by K0bin** [comment]
This is missing DXVK logs and the apitrace is broken unfortunately. 

I checked the Vulkaninfo output files you uploaded to the Arch issue and it looks like the working one only lists your iGPU and not the discrete one for whatever reason. Either way, I'm pretty sure this is a setup issue rather than a DXVK bug. I also have absolutely no idea about LXC containers so I can't help you with that.

**Comment by vfioexperte** [comment]
bug is fixed with 2x pc  restart.
