### ISSUE TITLE
Dungeon Siege 2 invisible mouse cursor

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3020]
In Dungeon Siege 2 the mouse cursor is invisible with dxvk. Work with wined3d.
Haven't found a config option yet that affects it. 

### Software information
Dungeon Siege 2

### System information
- GPU: R9 380
- Driver: days old mesa-git
- Wine version: Wine-GE 7-32
- DXVK version: master, 1.10.3 & 1.5

### Apitrace file(s)
https://mega.nz/file/5wwW0BRK#zpXHk6UPV-wQJKSa6zAg6yjGVgsNJxZwkHUxJaclMjM
Reproduces in the trace

### Log files
[DungeonSiege2_d3d9.log](https://github.com/doitsujin/dxvk/files/9904906/DungeonSiege2_d3d9.log)

**Comment by Blisto91** [comment]
As @DadSchoorse point out this is probably the line of interest :grin: 
```
warn:  D3D9DeviceEx::SetCursorProperties: Software cursor not implemented.
```

**Comment by WinterSnowfall** [comment]
Apparently this is a problem [on more recent versions of Windows as well](https://steamcommunity.com/app/39200/discussions/0/846963165410032177/?ctp=3). Have you tried [this fix](https://community.pcgamingwiki.com/files/file/1321-dungeon-siege-2-mouse-cursor-fix/)? Alternatively, I see people have also got it working using fullscreen=false + setting their fullscreen rez as launch parameters (aka poor man's borderless fullscreen).

**Comment by Blisto91** [comment]
I have not tried that 😱

**Comment by Blisto91** [comment]
> Apparently this is a problem [on more recent versions of Windows as well](https://steamcommunity.com/app/39200/discussions/0/846963165410032177/?ctp=3). Have you tried [this fix](https://community.pcgamingwiki.com/files/file/1321-dungeon-siege-2-mouse-cursor-fix/)? Alternatively, I see people have also got it working using fullscreen=false + setting their fullscreen rez as launch parameters (aka poor man's borderless fullscreen).

Didn't help when launching the one called `DungeonSiege2_steam.exe` provided with the fix (which was same size as gog exe and only one that could launch game)

**Comment by WinterSnowfall** [comment]
> But yes cursor appears when not in fullscreen

Software cursor in fullscreen memes probably... saw the same kind of behavior with Age of Mythology & dxvk, but luckily there's a built-in config hack (in the game's own config files) to enable hardware cursor on Nvidia. It just doesn't apply it automatically to anything newer than a GeForce 3 (lol)... but it can be enabled manually.

**Comment by Blisto91** [comment]
See https://github.com/AlpyneDreams/d8vk/issues/202 for another game that needs software cursor. Don't think there is a need for a separate issue.

**Comment by GenesisFR** [comment]
So I tried to use dxvk on Windows to fix the missing mouse cursor issue out of curiosity (I already know other ways to make it visible), however the cursor shows up for a split second at times and I can't for the life of me figure out why my game is zoomed in on the main menu no matter which resolution I use.

I even tried to lower my desktop resolution to 1024x768 as the game's main menu uses that as a fixed resolution but the cursor is still barely showing up, therefore the game is unplayable.

Has anyone ever managed to make it run on Windows?

As I said, it's just out of curiousity therefore not something important. For now I advise people to use wineD3D or hex-edited executables.

**Comment by WinterSnowfall** [comment]
> Has anyone ever managed to make it run on Windows?

I don't recall if @Blisto91 tested it on Windows, but since the software cursor implementation is very much OS agnostic, I'd expect it to work just as well as it does on Linux.

That being said, perhaps `dxvk.allowFse = True` is something to try.

**Comment by GenesisFR** [comment]
I tried `dxvk.allowFse = True` but that didn't make a difference. After closer inspection, the cursor actually stays locked in the top left corner, regardless of everything I try.

**Comment by WinterSnowfall** [comment]
> I tried `dxvk.allowFse = True` but that didn't make a difference. After closer inspection, the cursor actually stays locked in the top left corner, regardless of everything I try.

@Blisto91 has graciously helped to reproduce what you are seeing on Windows and I think I know what the problem is. At least I have come up with a rather crude fix that seems to make the cursor work just fine. I'll have to think about how it can be fixed more elegantly, and we should have something functional even on Windows for the next release. Thanks for bringing it up!

**Comment by GenesisFR** [comment]
I tested v2.6 on Windows again and it works fine on DS2! However, when trying it on the expansion Broken World, it crashes at the end of the loading, whether it's when starting a new game or loading an existing one :(.

I tried with and without `dxvk.allowFse = true` and even had a friend try it on his computer with the same result.

The default log isn't really helpful. Any way to make it more verbose?

[DungeonSiege2_d3d9.log](https://github.com/user-attachments/files/19244784/DungeonSiege2_d3d9.log)

**Comment by Blisto91** [comment]
@GenesisFR Does it work with 2.5.3?
Make a new issue and if you can make a apitrace. Just follow the instructions here https://github.com/doitsujin/dxvk/wiki/Using-Apitrace and get past the part that usually crashes with dxvk.

**Comment by WinterSnowfall** [comment]
As Blisto said, it's extremely unlikely the crash is related to the software cursor problems described on this issue, so please raise a new one and follow the issue template.

**Comment by GenesisFR** [comment]
> [@GenesisFR](https://github.com/GenesisFR) Does it work with 2.5.3? Make a new issue and if you can make a apitrace. Just follow the instructions here https://github.com/doitsujin/dxvk/wiki/Using-Apitrace and get past the part that usually crashes with dxvk.

I don't know since the cursor was bugged in 2.5.3 so I couldn't navigate menus as you can see in my previous messages above. I'll create an API trace and create a new issue then.

**Comment by GenesisFR** [comment]
I guess I'm gonna need help about that.

How am I supposed to load a game if I'm not using DXVK but the d3d9.dll from apitrace? I don't have a cursor anymore. Do I run the game windowed to work around it and get the cursor back? Why would I do that if I'm not using DXVK anymore? Don't you need a stack trace when it crashes or something? Unless there's a way to use both at the same time that I'm not understanding.

I also tried to use `apitrace.exe trace -a d3d9 path\to\DungeonSiege2.exe` while using DXVK, it does run the game but it's not creating any trace which I guess is normal.

Only way I got a trace working was to use an hex-edited DungeonSiege2.exe to get the cursor back in fullscreen to be able to load my save, but then that means it's not using the d3d9.dll from DXVK and therefore doesn't crash.

My question is, am I supposed to somehow reproduce the same crash while using apitrace? Or do I just run the game windowed and get past the part that crashes then ALT+F4.

**Comment by WinterSnowfall** [comment]
> Only way I got a trace working was to use an hex-edited DungeonSiege2.exe to get the cursor back in fullscreen to be able to load my save, but then that means it's not using the d3d9.dll from DXVK and therefore doesn't crash.

That's the trace we need. I'll play it back with dxvk, it **will** then hopefully crash somewhere and we can determine what the problem is.

So just create a new issue and attach that trace. I'll take it from there :wink:.

**Comment by GenesisFR** [comment]
Alrighty then, done.

https://github.com/doitsujin/dxvk/issues/4767

**Comment by RobinS0220** [comment]
Hi, is this still open? I searched all over the internet and found this site, so I quickly signed up to be able to post here and see if anyone could help me with the invisible cursor problem in Dungeon Siege II.

My girlfriend and I would like to play this game together, but we have a problem on her laptop that is preventing us from continuing, namely the disappearing cursor problem on version 2.2 (GOG version). 
Is there anyone who could please help us with this? from what I read, I think you somehow figured out how to make it work, but I don't understand half of what I read, so I would need some help.


The reason we are using 2.2 is because the multiplayer feature was disabled in version 2.3 for reasons I am not aware of, and only with 2.2 could I get it to work and play on Gameranger, but now we have a new problem and that is the cursor disappearing whenever we start the game.     There are some workarounds I know of but it doesn't work on her side, whenever I run it in windowed mode it only works at a resolution of 800x600 which is very tiny on her screen and you can't make the window bigger or change the resolution of the game or else the game crashes.   

I am also in lack of time as in a few days I will be forced to abandon this because of work and I won't have access to her laptop... so if anyone has the know how and don't mind helping out a stranger in need, we'd appreciate it, thank you.

**Comment by Blisto91** [comment]
If you want to give dxvk a go (this project) then from this archive try to drop `d3d9.dll` from the x32 folder next to the games exe. https://github.com/doitsujin/dxvk/releases/download/v2.6/dxvk-2.6.tar.gz
Note that this requires recent ish Vulkan support from the laptops GPU + drivers and so may not work if it is old. 
To remove dxvk again just delete the `d3d9.dll`

**Comment by RobinS0220** [comment]
Hello and thanks for the quick support.  

I did as @Blisto91 said and was excited when I saw the cursor in the main menu, but shortly after the game loads, a small tab pops up on the screen and if I remember correctly, it says "Gathering Data Exception" now right after this happens, the game quits and no matter what resolution I set it to, it won't continue from that point forward.   

I am guessing, this is thanks to Poor Vulkan support, as @WinterSnowfall stated, perhaps ?  the GPU is a Integrated card by Intel, Intel® UHD Graphics for 10th Gen Intel® Processors        https://www.intel.com/content/www/us/en/products/sku/195436/intel-core-i510210u-processor-6m-cache-up-to-4-20-ghz/specifications.html

thanks!

**Comment by GenesisFR** [comment]
Did you even try the hex-edited executable? Also the main menu is always hardcoded in 1024x768. Once you are in-game, it will use the resolution you specified.

**Comment by RobinS0220** [comment]
@GenesisFR I am not sure what a hex-edited executable is.   Do you mean the executable that @WinterSnowfall recommended? 

Just to clarify a few things, the original version of the game is V2.3 (GOG), which works out of the box, except multiplayer which is greyed out, so in order to use the multiplayer feature, we are forced to revert to V2.2, which enables multiplayer and combined with, Gameranger, we should be able to connect and play over the internet.  The main problem is that on my partner's side, once I run V2.2, the cursor isn't visible, where as on mine it is and works just right, even though my machine is older with a less recent version of Windows, but we both essentially run Windows 10.

**Comment by GenesisFR** [comment]
Yes, that executable. Define "less recent version of Windows". From what I know, the cursor is missing only from Win10 onwards and is always visible in windowed mode.
