### ISSUE TITLE
release tarballs are missing include/spirv, include/vulkan and include/native/directx/

### ISSUE THREAD

**Issue by stefson** [doitsujin/dxvk#3059]
hey there, I just wanted to build dxvk-2.0 from source and got this result:

```
Target machine cpu family: x86
Target machine cpu: i686
Library d3d9 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_47 found: YES
Program i686-w64-mingw32-windres found: YES

../dxvk-2.0/meson.build:124:0: ERROR: Include dir ./include/vulkan/include does not exist.

```

The folder is in the tarball, but its empty. Same goes for spirv and directx header folders. Do you think its possible to fix that? 

here is the meson config log: [meson-log.txt.gz](https://github.com/doitsujin/dxvk/files/9996871/meson-log.txt.gz)

thanks

**Comment by Blisto91** [comment]
Hello.
The source code is fetched automatically by GitHub and doesn't seem to care about submodules even tho it has been requested for multiple years by now.
See also
https://github.com/doitsujin/dxvk/issues/3048

There might we convoluted ways around it like some CI. But haven't looked into it much.

**Comment by stefson** [comment]
It was really great to see some sort of complete tarball release. At the moment I'm not even sure how to repack this properly locally, even if I wanted to.

**Comment by mbriar** [comment]
What's the problem with just using `git clone --recursive` to obtain the source and then checking-out the v2.0 tag?

**Comment by stefson** [comment]
yeah, you can just stop to push out the broken source tarballs then.

**Comment by mbriar** [comment]
As mentioned in the other, already linked, issue about this, the broken source tarballs are auto-generated by github.

**Comment by Joshua-Ashton** [comment]
https://github.com/doitsujin/dxvk/issues/3048

**Comment by pchome** [comment]
Not a bug, IMHO
Users want everything to be bundled, but distro package maintainers usually don't want/need sources for packages that already present in system, especially if an project build and statically link some outdated versions with security flaws.

Also, i think github can't just turn a switch and start packaging submodules, because this will change behaviour of some projects build systems if they find bundled sources.

As compromise developers could provide separate source archive with all submodules included.

**Comment by eli-schwartz** [comment]
> Users want everything to be bundled, but distro package maintainers usually don't want/need sources for packages that already present in system, especially if an project build and statically link some outdated versions with security flaws.

Not sure what this means since dxvk doesn't support system versions of these headers whether installed or not.

It's not a question about distros and bundling, merely a question about whether it's at all possible to successfully configure the build without git.

It's trivial to upload tarballs that can be used without git installed: `meson dist --no-tests`.

That's the same thing, more or less, that people did before github (though it might be called `make dist` / `make distcheck`).

**Comment by pchome** [comment]
@eli-schwartz 
> Not sure what this means since dxvk doesn't support system versions of these headers whether installed or not.

It's about "github bug" tag, "broken source tarballs" and projects using submodules on github in general. Not about dxvk in particular.
