### ISSUE TITLE
`wineboot -u` does not uninstall dxvk

### ISSUE THREAD

**Issue by wael444** [doitsujin/dxvk#3106]
i don't know, this is self-explanitory.

after setting the DLL overrides with `WINEDLLOVERRIDES`, and installing the DLLs into the correct directory, testing a application, restoring DLLS with `wineboot -u`, but dxvk is still there.

is this a design decision? does 'restoring DLLs' not remove the original overridden dlls?

**Comment by Blisto91** [comment]
The -u in wineboot stands for update. So it will update your current wine prefix if a newer one (or different i guess) is installed. It should also restore any wine dll's that are missing which is why you must delete the dxvk ones first as it won't touch the replaced dll's. If it did it would also screw with any other dll's replaced with native Windows versions trough winetricks as an example.

**Comment by wael444** [comment]
> why you must delete the dxvk ones first as it won't touch the replaced dll's

Thanks!

**Comment by Blisto91** [comment]
Note that it also doesn't touch the dll overrides so those also have to be removed. Which can be done through winecfg or [through CLI by editing the wine registry ](https://github.com/doitsujin/dxvk/pull/3097#issuecomment-1328255443)
