### ISSUE TITLE
[regression] Ubisoft Connect overlay notification stuck on screen

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3146]
It seems there is a issue with the overlay notification/popup for Ubisoft Connect on Proton experimental (haven't tested elsewhere). I first became aware of it from [GamingOnLinux's Fenyx Rising Steam Deck review](https://youtu.be/mb1ykoXyuJg?t=163) and while i was testing some other stuff in this game i looked into it a bit more.

I've bisected the issue to start with commit https://github.com/doitsujin/dxvk/commit/482a7e433bd0214372d7049218d51ea3a76052dd and it makes it so the overlay notification stays stuck on screen even after the dot countdown where it's supposed to go away. Commits prior to the one above it works fine.

<details>
  <summary>Screenshot taken from GamingOnLinux video</summary>

![Screenshot_20221223_222844](https://user-images.githubusercontent.com/47954800/209407058-2d389202-3daf-43d7-84e8-9a2cbd045771.png)
</details>

### Software information
Ubisoft Connect overlay tested in Immortals Fenyx Rising

### System information
- GPU: R9 380X
- Driver: 22.3.1
- Wine version: Proton experimental & bleeding edge 
- DXVK version: https://github.com/doitsujin/dxvk/commit/482a7e433bd0214372d7049218d51ea3a76052dd and later

The same issue is also present on Steam Deck

### Log files
Fenyx Rising proton log with the issue present.
[steam-2221920.log](https://github.com/doitsujin/dxvk/files/10297381/steam-2221920.log)

Ubiosofts own overlay log.
[overlay_log.txt](https://github.com/doitsujin/dxvk/files/10297383/overlay_log.txt)

**Comment by kakra** [comment]
This is mostly a problem on Steam Deck only where I cannot press Shift+F2 to get to the overlay menu. After doing that and closing the menu, the notification is gone. I never thought about this being a bug but rather an annoying way of Ubisoft to promote their own connect overlay. Usually, on PC, I just press Shift+F2, then close the overlay, and the notification is gone, and it stays gone even on the next start of the game (countdown properly works then). Not so on the Steam Deck, tho, because there's no such thing as Shift+F2 unless I connected a keyboard (which I didn't).

**Comment by qinlili23333** [comment]
Ubi is using annoying way to force users show theri fxxking overlay. If u don't need notifications and overlay, just disable it in Ubisoft Conncet. Their overlay is even buggy on Windows.
PS: Ubi recently finally gave an option to disable ads after game.

**Comment by doitsujin** [comment]
Well the problem here is that DXVK dynamically loads the Vulkan loader DLL on demand rather than linking against it at build time. This isn't an issue for any overlay that uses a Vulkan layer, but breaks applications that decide to hook the loader for whatever reason.

Really annoying but we're going to have to revert the change for non-native builds.

**Comment by Blisto91** [comment]
Fixed by commit https://github.com/doitsujin/dxvk/commit/4d0d455895fb0066dd7eba611f1dc50273f0e17f

**Comment by Ryusennin** [comment]
Although that fix only works for Linux (as mentioned in the 2.1 release notes), I have found a simple workaround to make the popup unstuck on Windows. Temporarily switching from fullscreen to borderless (or vice versa) is enough to refresh the screen and remove the nagging notification. However you have to do this every time you launch your game.
