### ISSUE TITLE
dxvk installed correctly but game does not open only shows in task maneger

### ISSUE THREAD

**Issue by davipinhati** [doitsujin/dxvk#3151]
i never got dxvk to work on my windows pc in 95% of the games i tested, only one to work was evil west that does not takes advantage that much of dxvk. when ever i install dxvk the game dont open and dont give error message, it just says it is open in task maneger and no icon is show on taskbar, this happens on most games on my pc whit dxvk. my windows is installed in one partition of the c drive and the games are intalled in other partition, is this a problem for dxvk compatibility?

my pc is 

 Operating System: Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                 Language: Portuguese (Regional Setting: Portuguese)
      System Manufacturer: To Be Filled By O.E.M.
             System Model: B450M Steel Legend
                     BIOS: P4.30 (type: UEFI)
                Processor: AMD Ryzen 5 3600 6-Core Processor               (12 CPUs), ~3.6GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16308MB RAM
                Page File: 10634MB used, 18984MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.2075 64bit Unicode

**Comment by K0bin** [comment]
There's a reason why Windows is unsupported. These kinds of issues happen and there's nothing we can do about it.

**Comment by lolcatw** [comment]
he got called out lol

https://boards.4channel.org/g/thread/90897595

**Comment by Blisto91** [comment]
Hello.

The general gist is that while dxvk maybe work most of the time on Windows there are sometimes issues that can be specific to the OS either because of driver differences, game specific quirks (some game only load the dll's from the Windows system folders) or other setup specifics. 
The official dxvk version is mainly focused to be used together with Linux Wine and so Windows (and Mac i guess) are not considered to be officially supported. That doesn't mean that Windows issues don't sometimes get solved, but unless they also affect Linux or are relatively minor changes they are not a primary focus. It is not about hating Windows or anything like that.

It is recommended to read through the Windows section in the wiki as it contains the general things to try when one is having trouble using dxvk on windows. https://github.com/doitsujin/dxvk/wiki/Windows
Making sure drivers are updated and no overlays are interfering is usually the first thing to try.


@davipinhati 
When you make a issue make sure to fill out the required info from the issue template which includes stuff such as dxvk version used and logs from a broken game.

**Comment by K0bin** [comment]
Not that I care what some idiot on 4chan thinks but this isn't just a matter of us refusing to support Windows. Like I said, there's simply nothing we can do about it.
