### ISSUE TITLE
[Feature Request] Perform shader compilation on performance cores instead of all threads

### ISSUE THREAD

**Issue by Silent-Remux** [doitsujin/dxvk#3213]
Would be nice if the compiler could run on the performance cores (rather than all including efficiency cores) of chips like the 13700K, 13900K etc. Should help reduce any hitching with games/engines that requires just-in-time compiling of shaders like Unreal Engine 4.

**Comment by doitsujin** [comment]
Scheduling stuff to specific threads isn't really up to DXVK.

You could manually pin the entire game to just P-Cores if that's a concern, but in general doing anything from the DXVK side here isn't a good idea since catering to one workload is going to regress another, in this case we'd just basically break well-behaved games that compile shaders in the background.

**Comment by mirh** [comment]
Wouldn't that be detrimental to like most games given the changes you shipped in 2.0 with background ahead-of-time compilation (on supported software and hardware)?
