### ISSUE TITLE
Exagear

### ISSUE THREAD

**Issue by klark231** [doitsujin/dxvk#3221]
can you make it work without dri3. unfortunately exagear doesnt have support for dri3. im willing to donate money if you can make it work. most android uses vulkan 1.1. i can ask the community to donate too for you. any help would be appreciated.

**Comment by mbriar** [comment]
Android games don't use D3D and DXVK doesn't interact with dri3. You are in the wrong place.

**Comment by klark231** [comment]
> Android games don't use D3D and DXVK doesn't interact with dri3. You are in the wrong place.

no. If you know exagear. its a vm for android. lets you run wine. able to play x86 games. WineD3D helps a little bit with the fps. we are able to acquire hardware acceleration with kgsl turnip zink xlib. but it would be far more better if dxvk works.

**Comment by doitsujin** [comment]
DXVK 1.10.3 uses Vulkan 1.1 if that's a restriction you have. We don't do anything with DRI directly though so that requirement must be coming from elsewhere.

But also - please don't just waltz in and expect everyone to know instantly what Exagear is, and no, we won't support anything Android-related.
