### ISSUE TITLE
Zusi 3 (1040730) has broken cab images

### ISSUE THREAD

**Issue by besentv** [doitsujin/dxvk#3250]
Rendering of cabs in the simulator is broken on DXVK (works in WineD3D) .

![](https://cdn.discordapp.com/attachments/839201855145902093/1073336562517037146/image.png)

### Software information
Zusi 3 (1040730) - defaults

### System information
- GPU: Nvidia 1660ti
- Driver: 528.85
- Wine version: 7 and 8 (Proton 7 and 8-alpha)
- DXVK version: 2.1

### Apitrace file(s)
https://drive.google.com/file/d/1aApV8a9l5xFtqHEe8EyGdkAJvLOrxDhN/view?usp=share_link

### Log files
- d3d9.log: [ZusiSim.64_d3d9.log](https://github.com/doitsujin/dxvk/files/10716697/ZusiSim.64_d3d9.log)

**Comment by besentv** [comment]
Added apitrace

**Comment by Blisto91** [comment]
It's beautiful. Well made. (I haven't watched it yet)

**Comment by besentv** [comment]
Watch out for possible STDs ;))

**Comment by kassindornelles** [comment]
Keep the environment professional please.

**Comment by kassindornelles** [comment]
:forg:

**Comment by besentv** [comment]
:frog: :pregnant_woman:

**Comment by Blisto91** [comment]
`d3d9.noExplicitFrontBuffer = True` appears to work around this issue.
Waiting for feedback from Josh like https://github.com/doitsujin/dxvk/issues/3250 before a potential PR is made.

**Comment by w-flo** [comment]
Zusi was my initial motivation to introduce the noExplicitFrontBuffer config and it was [enabled automatically for the old exe name.](https://github.com/doitsujin/dxvk/commit/ba41a5219ae69753b4c7106bed99d310a5b28e01) The issue is that there is now a new default exe filename, "ZusiSim.64.exe" (the old 32 bit executable "ZusiSim.exe" still exists though).

I think we should just add the new exe filename to the list of automatic config settings. It has worked well for Zusi users and people researching this issue are adding dxvk.conf to enable the setting anyway. If there is a better solution for this in the future to make the swapchain behavior the same as in Windows (old backbuffer contents stay intact in windowed mode even when using DISCARD swap effect), the setting can be dropped for ZusiSim*.exe.

**Comment by ACH1980** [comment]
I saw the option to add this config manually by creating a `dxvk.exe` with the content below. But I'm not sure where to place it. The person who wrote this tip said she doesn't know exactly, but thinks it must go into the directory where the "ZusuSum.64.exe" is located, but that didn't worked for me. Do you know where I should place it?
