### ISSUE TITLE
[Feature Request] DXVK_HUD Opacity

### ISSUE THREAD

**Issue by Silent-Remux** [doitsujin/dxvk#3371]
Would like to be able to set either max nits of overlay or overlay transparency/opacity to 50% to avoid burning my oled if possible?

**Comment by doitsujin** [comment]
Is this in an HDR context or just plain old SDR?

**Comment by Silent-Remux** [comment]
> Is this in an HDR context or just plain old SDR? We're currently hardcoding the HDR brightness to 203 nits which could easily be changed, not sure how to make this work better for SDR without making it look weird.

I was asking about SDR but a user customizeable option would be nice, preferably I would cap to to about 80-100nits if I had the ability.

**Comment by WinterSnowfall** [comment]
@Silent-Remux Are the below what you were looking for?

<details>
<summary>100% HUD Opacity</summary>

![100Opaque](https://github.com/doitsujin/dxvk/assets/6306593/491bf798-b3d5-4b98-994d-5eec8d9e5878)

</details>
<details>
<summary>50% HUD Opacity</summary>

![50Opaque](https://github.com/doitsujin/dxvk/assets/6306593/e63aa79b-f333-4603-8886-bc6c26505cd1)

</details>

As I note, I never had burn-in issues due to the HUD and am mostly using an OLED, but can see how the frametime chart especially (if it's a constant block of green over long periods) could cause issues. That being said, I don't get why anyone would play for hours with the hud enabled, but let me know if this seems fine to you and I'll PR something (will make hud opaqueness configurable, of course).
