### ISSUE TITLE
Persona 5 is unable to start.

### ISSUE THREAD

**Issue by ShadowLite1** [doitsujin/dxvk#3385]
### Software information
Persona 5 Royal

### System information
- GPU: RTX A2000
- Driver: 531.68
- DXVK version: 2.1
<img width="224" alt="Capture" src="https://user-images.githubusercontent.com/13987781/235445631-1c619e8c-5144-4741-9241-c6fdd42812d8.PNG">

**Comment by ShadowLite1** [comment]
[P5R_d3d11.log](https://github.com/doitsujin/dxvk/files/11367500/P5R_d3d11.log)

**Comment by Blisto91** [comment]
This line here means it's not picking up dxvk's `dxgi.dll`.
```
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
```

If you've put it next to the exe same as the d3d11 dll then it likely means the game directly looks at the one in the Windows system directory and there is nothing that can be done from dxvk's side.

**Comment by K0bin** [comment]
More info here: https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by FyiurAmron** [comment]
FWIW, the solution I used (and which did wonders) was to rename `dxgi.dll` to `dxgj.dll` and to change the imported DLL name accordingly in `d3d11.dll` (DXVK's one, not the system's :) - indeed, by looking at the logs it came to me as obvious that the DXVK's `dxgi.dll` is not even loaded, because DXVK's `d3d11.dll` tries to load system's one.

YMMV, but it really helps on Windows.

**Comment by skwelks** [comment]
> The solution I used (and which did wonders) was to copy DXVK's `dxgi.dll` to `dxgj.dll` also and to change the imported DLL name accordingly in `d3d11.dll` (DXVK's one, not the system's :) - indeed, by looking at the logs it came to me as obvious that the DXVK's `dxgi.dll` is not even loaded, because DXVK's `d3d11.dll` tries to load system's one (dxgi's logs were empty). Sometimes you'll need to also change the import in the game's exes/dlls, sometimes not.

Sorry to reply after so long, but can you elaborate on what you did to fix it? I renamed dxgi.dll to dxgj.dll, and in d3d11.dll I used HxD to change dxgi to dxgj, but now instead of saying "doesn't meet minimum system requirements" the game just crashes instantly on launch. No log files are generated, and I'm really not sure what I'm doing wrong.
