### ISSUE TITLE
[d3d9] Artificial Academy 2 male semi transparent body explosion.

### ISSUE THREAD

**Issue by Arkblade2015** [doitsujin/dxvk#3553]
If "Render 2" is enabled in the game settings, the semi-transparent male body (silhouette) will explode in love scenes.
The following creature-like silhouette should properly take the form of a man.
![2023_0706_1055_10573](https://github.com/doitsujin/dxvk/assets/11951625/86d92422-142f-4c9f-96e0-acb92b0774ef)

### Software information
Artificial Academy 2 (with AA Unlimited)

### System information
- CPU: i7 6700
- GPU: Nvidia GeForce GTX 1070
- Driver: 536.40
- DXVK version: 2.2

### Apitrace file(s)
https://drive.google.com/file/d/1HhFYKG4x86RVCBBjc2ya5a5wZ9gLKQzy/view?usp=sharing
**Caution! this include heavy nswf content.**

**Comment by Arkblade2015** [comment]
log update. sorry wrong log.

**Comment by Blisto91** [comment]
@Arkblade2015 Could you add a disclaimer above the apitrace link that it contains nsfw sexual content? Not that i personally mind, but just so no one gets caught off guard.


I can reproduce the issue when replaying the trace both with dxvk on Windows and on Linux with radv.
It happens at the end where you will see the silhouette of the man is almost a big blueish blob instead of a human figure.
Below are a couple of censored screenshots taken on Windows with and without dxvk so it's easier to compare. 

<details>
  <summary>Screenshots (SFW)</summary>

dxvk
![windows-dxvk](https://github.com/doitsujin/dxvk/assets/47954800/1f1d0b8b-59f5-430e-9cf3-c51df7ffa273)

Native
![windows-native](https://github.com/doitsujin/dxvk/assets/47954800/7f583b86-5c7c-49c6-b889-b89971feec66)
</details>

**Comment by Arkblade2015** [comment]
I am very sorry.
I will add a note of caution.

**Comment by Blisto91** [comment]
Fixed by commit https://github.com/doitsujin/dxvk/commit/7f1e52703d921e957057e21a02079619f05d8f67
