### ISSUE TITLE
Supreme Commander & Forged Alliance resolution problems

### ISSUE THREAD

**Issue by SissiHermanni** [doitsujin/dxvk#3692]
I play Supreme Commander and it's standalone expansion Forged Alliance with lower resolution than my native monitor resolution. Game is running with 1360x768 resolution and monitor's native display resolution is 3840x2160.

After exiting game, resolution doesn't switch back to native display resolution and instead stays in 1369x768 resolution. This problem didn't exist with Wine's VKD3D and only started to appearing after switching to DXVK.  

### Software information
Supreme Commander
Supreme Commander: Forged Alliance
Resolution: 1360x768

### System information
- GPU: GTX 1070
- Driver: Nvidia 535.113.01
- Wine version: 8.17
- DXVK version: 2.3

**Comment by WinterSnowfall** [comment]
@SissiHermanni Reverting to your desktop resolution should work fine with any reasonably recent version of Wine/Wine Staging. I am on Wine Stating 9.17 at the moment and it behaves correctly at least.

It was never a DXVK problem per se, anyway, because as long as the game doesn't resize the swapchain before exit your compositor won't do it on its own.
