### ISSUE TITLE
Have problems installing with DXGI ?

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#3721]
Thanks for reading my topic.
I see DXVK default install comand is "without dxgi".
If installing "with dxgi" does problems ? If yes what problem can happen ? Why the default is "without dxgi" ?

Have an nice night.

**Comment by Blisto91** [comment]
Hello. Which install command are you referring to? 

In general you should always install with dxgi. I'm not sure installing without is much supportee with latest versions

**Comment by Augusto7743** [comment]
Hello. All good with you ?
I use ./setup_dxvk.sh install -with-d3d10 -with-dxgi
However as in docs the command is "./setup_dxvk.sh install -with-d3d10 -without-dxgi" need information if is or not better install dxgi, but seeing your reply is better installing it.
Have an nice friday !!!!

**Comment by Blisto91** [comment]
Ah I see.
With the old setup script (isn't part of the repository anymore) the default install command `setup_dxvk.sh install` should include dxgi. The options shown behind `install` are just extra options to modify the default.

Pre 2.0 this also included the ` -with-d3d10` option which instructed the script to also install the `d3d10.dll` and `d3d10_1.dll` helper libraries. I'd recommend also leaving that out as those implementations were never complete and might cause issues if leftover when then switching to the new dxvk versions. They were removed in 2.0 since they were never used much in practice and it's recommended to use the ones shipped with Wine or Windows.
The main Direct3D implementation resides in `d3d10core.dll` which was always installed with the script.

Hope this clears things up a bit. Have a nice weekend.

**Comment by Augusto7743** [comment]
You are saying for not install using -with-d3d10 ?
I use DXVK version 1.10.3 being last version for Kepler.
Thus being the better install command is
./setup_dxvk.sh install -without-d3d10 -with-dxgi

I not understand if running Visual Pinball in WINE use D3D9 or D3D10. However using DXVK run more faster and some graphics errors are fixed.

**Comment by Blisto91** [comment]
>You are saying for not install using -with-d3d10

Yes
Just running `./setup_dxvk.sh install` should be fine. That already included dxgi and not the extra d3d10 helper libraries.
Direct3D games are supported still even with the default

**Comment by Augusto7743** [comment]
Using the command
./setup_dxvk.sh install
Not any others D3D10 files are installed ?
Well ... WINE D3D10 implementation has some issues. I had an understand DXVK D3D10 run better without issues.

VKD3D Proton have both D3D10 and 12 ?

In others words ... I only want run WINE using D3D9, 10, 11 and 12 with less or without issues.
Trying run Visual Pinball using WINE D3D implementation have graphics errors and crashes too.
With DXVK run without problems.

**Comment by Blisto91** [comment]
As said the d3d10 option is only for the files d3d10.dll and d3d10_1.dll. They are separate helper libraries and dxvk works fine together with the Windows and Wine ones (baring any bugs). The actual Direct3D implementation is in d3d10core.dll which the option does not influence.
It's just the naming convention is just a bit weird compared to the other ones.

> VKD3D Proton have both D3D10 and 12 ?

vkd3d-proton is only d3d12

**Comment by Augusto7743** [comment]
Thanks very much.
