### ISSUE TITLE
[d3d9] WITCH ON THE HOLY NIGHT crashes with dxvk

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3746]
Originally reported in the Proton issue

[WITCH ON THE HOLY NIGHT](https://store.steampowered.com/app/2052410/WITCH_ON_THE_HOLY_NIGHT/) crashes before main menu when using dxvk. Wined3d gets to main menu fine.

### Software information
[WITCH ON THE HOLY NIGHT](https://store.steampowered.com/app/2052410/WITCH_ON_THE_HOLY_NIGHT/)
Default settings

### System information
- GPU: RX 6800
- Driver: mesa main
- Wine version: Proton Experimental
- DXVK version: Tested d9vk 0.13f, dxvk 1.6 and master.

### Apitrace file(s)
https://drive.proton.me/urls/6MPF4PDP68#wZwExr3HYZl8
Will also crash when replayed with dxvk

### Log files
[steam-2052410.log](https://github.com/doitsujin/dxvk/files/13677191/steam-2052410.log)

**Comment by WinterSnowfall** [comment]
I had a look at the trace Blisto shared. The game seems to be doing incredibly dubious things. 

It creates a texture, uses it for a bit (meaning it has a non-zero refcount), calls IDirect3DTexture9::Release() at some point and gets a 0 refcount, meaning dxvk legitimately destroys the object... but then the game calls IDirect3DTexture9::Release() *again* and somehow expects that to work... but of course calling anything on a destroyed object will make it crash *surprised pikachu face*.

No idea how this would work on native or WineD3D. Also no idea on how to fix this sort of thing.

**Comment by Blisto91** [comment]
It does not seem to crash with Proton 7.0-6 no. :eyes: 
Will check on Windows with dxvk here later thanks.

**Comment by WinterSnowfall** [comment]
> [...] so I don't think this bug is necessarily caused by DXVK. 

@R1kaB3rN The issue is the game relies on "use after free" to work properly. Apparently this somehow works on native (meaning Windows)...

As I mentioned before, a clean fix will be rather hard to implement. If you want I can share a build that works, but what it basically does is to never release textures, which is like allowing a racoon to rummage through your trash for any of the older stuff you've thrown out by never emptying your bin - meaning not exactly a good idea. I expect the game will eventually run out of address space in this scenario, but it does indeed get it working.

> [It advertises DirectX11](https://store.steampowered.com/app/2052410/WITCH_ON_THE_HOLY_NIGHT/) as the minimum and recommended system setting, but when using DXVK, the D3D9 to Vulkan translation occurs instead of D3D11. I don't know if D3D11 is used on Windows for this game, but if it is then this could possibly be a DXVK bug? Though this is probably just a mistake from the publisher/devs

Game requirements and the graphics API that they use are very commonly different. There's no direct correlation between the two. If dxvk reports D3D9, that is because the game code is creating a D3D9 device. The behavior will be the same regardless of OS, because again, it's game code that we're talking about here.

**Comment by gofman** [comment]
Yes, it relies on properly supporting use after free, not just with extra d3d resource release (which crashes first usually) but with some other game memory objects game allocates and frees directly too. The issue with texture extra release can be confirmed on Windows by enabling heap debug flag FLG_HEAP_ENABLE_FREE_CHECK in NtGlobalFlag for game exe (e. g., using gflags.exe program from Windows SDK), with that enabled it crashes in the same place on Windows.

This should hopefully work better in Proton Experimental [bleeding-edge] which got a bit of use after free support improvements.

**Comment by Blisto91** [comment]
Not a dxvk issue afterall. Thanks gofman!
