### ISSUE TITLE
[Crashes]FINAL FANTASY XV WINDOWS EDITION for Microsoft Store

### ISSUE THREAD

**Issue by DDXDB** [doitsujin/dxvk#3774]
The game crashes at the beginning and seems to match DLL loads dxgi.dll from System32 in Common issues, is there a workaround

### Software information
FINAL FANTASY XV WINDOWS EDITION for Microsoft Store

### System information
- GPU:ARC A770
- Driver:31.0.101.5084
- Wine version:NA
- DXVK version:2.3

### Apitrace file(s)
No generated file

### Log files
No generated file

**Comment by Blisto91** [comment]
If the game wants to load from the Windows system folder then from the perspective of dxvk there is no workaround as this is not an issue on Linux with Wine.

To force an application to load a local dll you'd probably have to modify it's exe or use some tool that will do it for you via injection or otherwise (don't know what it's called). I suspect no one here has much, if any, experience with that so google is probably better.
Obviously I'll advise not to try any of the sort on games that uses any form of anti cheat which would be at your own risk.

**Comment by Blisto91** [comment]
In regards to this game specifically then at least using the Steam version i don't see an immediate indication that it force loads any of the dlls from the system folder. Testing with a RX 6800 on Windows i just doesn't start with 2.3 but starts with 2.2

**Comment by DDXDB** [comment]
> In regards to this game specifically then at least using the Steam version i don't see an immediate indication that it force loads any of the dlls from the system folder. Testing with a RX 6800 on Windows i just doesn't start with 2.3 but starts with 2.2.
> 
> The Windows store version might behave differently of course

For one detail, I was using the file obtained after using UWPDumper
The game cannot be started directly from ffxv_u.exe inside the folder, showing that multiple DLLS are missing, but can be started using the shortcut in the Start menu, will launch an additional RuntimeBroker.exe, which is located in System32, whether relevant.
