### ISSUE TITLE
[d3d9] Codename: Panzers, Phase Two permanent queue sync

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3783]
Game has a permanent queue sync that is interesting to check out.

<details>
  <summary>Queue sync</summary>
  
![Screenshot_20240103_202942](https://github.com/doitsujin/dxvk/assets/47954800/792e3eae-dcd4-423d-a472-43742d8c1e21)
</details>

Interestingly running the game with `d3d9.allowDirectBufferMapping = False` ups the queue sync number to high double digits
<details>
  <summary>With d3d9.allowDirectBufferMapping=False</summary>
  
![Screenshot_20240103_203113](https://github.com/doitsujin/dxvk/assets/47954800/526fcfa3-3e17-46fd-8566-f95ee0f6e9e5)
</details>

Extra note that `d3d9.cachedDynamicBuffers = True` helps CPU bound performance quite nicely in this game but the queue sync is still there.
<details>
  <summary>with d3d9.cachedDynamicBuffers=True</summary>
  
![Screenshot_20240103_203309](https://github.com/doitsujin/dxvk/assets/47954800/8ed5db2e-67ea-4fe3-a033-d537a57fd6b6)
</details>

### Software information
Codename: Panzers, Phase Two

### System information
- GPU: RX 6800
- Driver: mesa main
- Wine version: Proton Bleeding Edge
- DXVK version: master

### Apitrace file(s)
https://drive.proton.me/urls/96BWD685T4#fpUpd5rLvNL7

### Log files
[PANZERS_Phase_2_d3d9.log](https://github.com/doitsujin/dxvk/files/13822696/PANZERS_Phase_2_d3d9.log)

**Comment by K0bin** [comment]
The game creates a render target and Locks it every frame. It doesn't actually use the render target for anything, at least in the apitrace.
Because it's a render target we have to assume the resource was written by the GPU, so in every lock call we end up waiting for the previous one.

Fixing this would require doing significantly more tracking, which isn't worth it. Besides that, the game always waits for an operation in the previous frame, so it's not that bad and has the side effect that it cuts down the latency.
