### ISSUE TITLE
[Feature request] Only list recognized config options under Effective configuration

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3788]
When making issue https://github.com/doitsujin/dxvk/issues/3767 i had missed that it was a simple spelling mistake since i just skimmed that the correct config was applied. 
It would be a nice tweak to only list recognized options below `Effective configuration:` like so.
```
info:  Found built-in config:
info:    d3d9.maxFrameRate = 60
info:    d3d9.frogFilter = True
info:  Effective configuration:
info:    d3d9.maxFrameRate = 60
```
One could also expand on to that and explicitly point out any unrecognized entries.
```
info:  Found built-in config:
info:    d3d9.maxFrameRate = 60
info:    d3d9.frogFilter = True
info:  Unknown config options:
info:    d3d9.frogFilter = True
info:  Effective configuration:
info:    d3d9.maxFrameRate = 60
```

**Comment by doitsujin** [comment]
As discussed on DIscord, the problem here is that the config system doesn't have a centralized place where all the options are defined. This is by design, basically a trade-off to allow more flexibility in exchange for the opportunity to fuck things up.

Honestly I don't think that one spelling error was a big deal, if in doubt you could just copy the actual names from the respective `*_options.cpp` or the sample `dxvk.conf`, but we also should really have caught this in the review.

**Comment by Blisto91** [comment]
The error was just an example that made me think about it in regards to my own testing and other peoples configs. 
Personally i would still consider it a nice to have but it also isn't the biggest deal especially if the work involved isn't minor, so closing as rejected (which is fine).
