### ISSUE TITLE
Assassins Creed Syndicate: Crashes with DXVK

### ISSUE THREAD

**Issue by an0therus3r** [doitsujin/dxvk#3826]
I installed AC Syndicate, and it seems the game is being CPU/GPU bottlenecked on my system (a lot of ubisoft titles are due to its poor optimisation for a lot of pc's) and as a result only 50% of the gpu is being used. So I basically depend on Vulkan to run AC games, but when it comes to Syndicate after following the DXVK steps as i always have, the game reached the splash screen with the ac logo, but then when the application is meant to open up it just closes the splash screen and never loads any application. I tried multiple versions of DXVK, including Async because it was a solution in another thread i found. I found a version of dxvk called "DXVK-MASTER" which i assumed fixed it, because it actually loaded the app and went into the menu, but it also crashed right when you press "continue" or if its a new save immediately. I'm on windows, and I know its not exactly supported, but most AC games i've tried so far including unity runs amazingly on vulkan, so i'm confused why syndicate would break. Any help is appreciated! 

### Software information
Assassins Creed: SYNDICATE V1.51

### System information
- GPU: Intel Iris XE
- Driver: 31.0.101.5081
- Wine version: 
- DXVK version: Latest 2.3

### Log files
Please attach Proton or Wine logs as a text file:

[ACS_dxgi.log](https://github.com/doitsujin/dxvk/files/14122824/ACS_dxgi.log)
[ACS_d3d11.log](https://github.com/doitsujin/dxvk/files/14122825/ACS_d3d11.log)

**Comment by Blisto91** [comment]
> warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter

This line indicates that the game might be trying to use Windows own dxgi in the system folders (Don't replace that with dxvk as you will wreck your system) and not dxvks next to the exe. The dxgi log is also empty

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/wiki/Windows#dll-loading-issues

**Comment by an0therus3r** [comment]
alright i see! thanks

**Comment by Ryusennin** [comment]
I'm not sure if this is directly relevant to your issue, but since January 28, DXVK suddenly stopped working on my Win10 Ryzen + Radeon system. I spent the last few days scratching my head as to what could have changed in the meantime.

Finally, thanks to a similar topic at PCSX2, I learnt that Microsoft recently pushed a silent install of their dreadful [url=https://apps.microsoft.com/detail/9NQPSL29BFFF]OpenCL, OpenGL & Vulkan Compatibility Pack[/url]. It's an obsolete fallback solution for people without modern drivers.

That recent Vulkan pack update seems to activate Microsoft's VulkanOn12 API, which happens to break DXVK as well as a lot of native Vulkan games and apps. Games will start and crash without any warning, and the logs are empty.

I fixed my issue by uninstalling the Compatibility Pack in Start > Settings > Apps. Hope this helps!

**Comment by Khimari** [comment]
> I'm not sure if this is directly relevant to your issue, but since January 28, DXVK suddenly stopped working on my Win10 Ryzen + Radeon system. I spent the last few days scratching my head as to what could have changed in the meantime.
> 
> Finally, thanks to similar topics on Reddit, I learnt that Microsoft recently pushed a silent install of their dreadful [OpenCL, OpenGL & Vulkan Compatibility Pack](https://apps.microsoft.com/detail/9NQPSL29BFFF). It's an obsolete fallback solution for people without modern drivers.
> 
> That recent Vulkan pack update seems to activate Microsoft's VulkanOn12 API, which happens to break DXVK as well as a lot of native Vulkan games and apps. Games will start and crash without any warning, and the logs are empty.
> 
> I fixed my issue by uninstalling the Compatibility Pack in Start > Settings > Apps. Hope this helps!

Oh my god thank you! This fixed all the issues of DXVK not working on all DX11 games! Lifesaver! Should be pinned for WIN users!

**Comment by Blisto91** [comment]
It has been noted in the Windows wiki section https://github.com/doitsujin/dxvk/wiki/Windows#dozen
