### ISSUE TITLE
FarCry Primal low perfomance Win 10 x64 Nvidia DX11

### ISSUE THREAD

**Issue by 7AllenWalker7** [doitsujin/dxvk#3848]
Hello, is there a way to get similar performance from Vulkan to Windows 10 as DX 11 native?

### Software information
FarCry Primal, max settings, 3440x1440 144 hz

### System information
- RTX 4070 Super
- 551.23
- i7-9700K
- latest dev https://github.com/doitsujin/dxvk/commit/ab3593185f45971977b956323c0a60f66f9f35e7

### Apitrace file(s)
https://mega.nz/file/9GgwxByJ#SHompHfJfHS-fQOGThVREP5J9iK2731iXDwynB-xoMQ

### Log files
![photo_5345943732203148169_w](https://github.com/doitsujin/dxvk/assets/43685084/9857dbd2-9249-43a8-a1bd-0fbc5e4f303e)
![photo_5345943732203148162_w](https://github.com/doitsujin/dxvk/assets/43685084/593cb98f-3751-4b16-a072-f9c545b7c982)

**Comment by Blisto91** [comment]
Is it the same FPS compared to 2.3 stable?

**Comment by 7AllenWalker7** [comment]
it s native dx11 vs vulkan dxvk

**Comment by Blisto91** [comment]
How does master dxvk compare to dxvk 2.3

**Comment by 7AllenWalker7** [comment]
2.3 have more fps.
Here log and screen

[FCPrimal_d3d11.log](https://github.com/doitsujin/dxvk/files/14220199/FCPrimal_d3d11.log)
[FCPrimal_dxgi.log](https://github.com/doitsujin/dxvk/files/14220200/FCPrimal_dxgi.log)
![photo_5345943732203148428_w](https://github.com/doitsujin/dxvk/assets/43685084/40cc98a4-0452-45a9-b76c-21343b163951)

**Comment by Blisto91** [comment]
I think this game doesn't like not having a working Nvapi library when running on Nvidia, which will be the case on Windows. E.g. it might be aggressively trying to load the Nvapi library when it sees a Nvapi GPU.

Normally Nvidia GPUs are hidden and shown as AMD by default in d3d10 and d3d11 to work around these issues, but some of the Far Cry games have internal logic thats differs depending on GPU vendor. These differences can cause visual issues in some areas in the game if there is a mismatch between what the game expects from a vendor and what the driver does.
So the tldr is this is one of the games where we don't hide the fact we are running on Nvidia to work around visual issues, but the game will then have a performance drop if Nvapi isn't working. There isn't a dxvk compatible Nvapi implementation on Windows.

I assume when using master dxvk if you make a file called `dxvk.conf` next to the exe and insert `dxgi.hideNvidiaGpu = True` the performance should improve.

The visual issues caused by the above in this game are not as bad as some of the other Far Cry games afaik because it mostly presents itself on buildings afaik which this game doesn't have alot of. 
If later in the game when you start making buildings in your village if you notice dark or bright squares on buildings or objects in your village you could try to spoof the vendor to being Intel with `dxgi.customVendorId = 8086`. I don't know if this helps though.

**Comment by 7AllenWalker7** [comment]
Thanks, I try this.
