### ISSUE TITLE
Add control to move HUD to other screen corners

### ISSUE THREAD

**Issue by KayTaneJupiter** [doitsujin/dxvk#3855]
Suggested feature: Add control to move HUD to other screen corners. The top-left is very commonly used by games and the DXVK HUD placed there makes both the game information and HUD unreadable.

**Comment by WinterSnowfall** [comment]
The dxvk HUD is mainly aimed at helping with debugging and development, not as a general purpose HUD.

However, you can configure it so that it displays only the information you need and also set its opacity, if it being fully opaque gets too much in the way (granted that it can, especially at lower resolutions).

If that's still not enough for your purposes, I recommend giving MangoHud a go.

**Comment by doitsujin** [comment]
We use different screen corners for different things these days, and I don't really want to spend too much time on this. Mangohud exists after all and displays all the non-debug things that ours would show anyway.
