### ISSUE TITLE
The Witcher 3 DXVK Corruption Issue

### ISSUE THREAD

**Issue by K3nPinBowling** [doitsujin/dxvk#4042]
Happens on Windows 11 with a 6800XT running the latest 24.5.1 drivers. The game is pretty much unplayable in this state. See [video](https://youtu.be/m6S1NSZp94I), issue is apparent in the homescreen and most noticeable at the 23 second mark.

Game Version 4.04. Tested using DX11 API running DXVK Async 2.0 (also tried GPL 2.3.1). Tried both fullscreen and borderless fullscreen.

Just wondering if this could be a new version issue as none of the other games I have tested have this issue.

**Comment by K0bin** [comment]
We generally don't support Windows as a platform for DXVK. Similarly, we don't support the async fork of DXVK.

The game is known to work perfectly fine on RADV or Nvidia GPUs, so what you're seeing there is almost certainly a driver bug.

**Comment by Blisto91** [comment]
This is very likely to be a driver issue.

That said testing both regular dxvk, async and gplasync (the latter two aren't supported here) on my zen 4 iGPU and RX 7900 xtx with Linux amdvlk 2024.Q1.3 and 2024.Q2.1 i have not been able to reproduce

**Comment by doitsujin** [comment]
I don't know if the current AMD driver exposes GPL for DXVK yet, but if it does, you might want to try the current `master` branch (builds can be found [here](https://github.com/doitsujin/dxvk/actions?query=branch%3Amaster+)). We've fixed some genuine bugs that were causing problems on AMD's implementation, but there hasn't been a release since.
