### ISSUE TITLE
[d3d11] Zenless Zone Zero Zooting Ze VRAM

### ISSUE THREAD

**Issue by cybik** [doitsujin/dxvk#4118]
Zenless Zone Zero (not a Steam-published game but hey) seems to be suffering from a VRAM leak. Whether it's from upstream or a DXVK quirk, I can't be sure, but Windows players seem to be unaffected, or at least affected far more slowly. Comparatively, there have been numerous reports of both AMD/ATI *and* nVidia users getting game crashes 30 minutes to an hour into a gameplay session. I myself have been suffering these slowdowns, so much so that at the mere HINT of frames being dropped, I close the game and restart it to be able to play another relatively stable bout of 30 minutes.

Before anyone wonders about the issue title, I was trying to go for maximum alliteration. Basically, ZZZ is "oversubscribing" the VRAM and it seems as if it's assuming more memory is available than there is. Could be due to some DX11 APIs related to resource loading that have implementation quirks, i dunno. 

### Software information
*Game:* Zenless Zone Zero
*Type:* ARPG (Gacha, F2P - can be installed without paying)
*Core Engine:* Unity 2019.4.40 (ultra-customized, most likely)
*Settings:* High on everything. (No ultra available)
*Resolution:* 3840x1600 (ultrawide 21:9)

### System information
- GPU: RTX 3080 10gb
- Driver: 555.58.02
- Wine version: GE-Proton 9-10
- DXVK version: `2.3.1-120-gfe9c---`
- Desktop: KDE5 on Wayland

### Apitrace file(s)
- None for now

### Log files
- Proton logfile of a run that had a slowdown at the end: [steam-18233669865720250368.log](https://gist.github.com/cybik/939c506fe1937e8023a3bc422f700123)

**Comment by doitsujin** [comment]
Unity Engine games are kinda known to load all resources into VRAM regardless of the GPU in use, this is generally not a leak. DXVK's memory management also cannot be improved due to some fundamental design flaws.

**Comment by cybik** [comment]
Fair point, but usually DXVK itself doesn't come close to the VRAM limit. For that matter, the game looks like it's averaging at 5.5~gb (for now), with occasional peaks that then go down after a bit (when they're not crashing the system). I'm guessing that everything else running in the background (composition, accelerated desktop, etc) takes precious resources away from DXVK, but still.

Is there an obvious way to limit the total allowed vidmem heap that I'm missing, or is this another one of these "can't be solved unless/until the dev stops being rude to memory" issues (which, per your statement, it certainly might be)?

**Comment by RyuKay24** [comment]
Me neither, blows up to 60% of my vram on my 3070ti xd so 8gig gpu's are out of the question.

**Comment by kamikaze211** [comment]
By setting DXVK_CONFIG="dxgi.emulateUMA = True" can fix this issue.
Seems that Windows version game uses UMA as default.

**Comment by cybik** [comment]
That option did little for me, @kamikaze211.

***However***, update 1.1 actually stabilized the game, by and large. Seems that DXVK may have "merely" exacerbated issues present for Windows players.

Closing for now.

**Comment by SysError99** [comment]
This is very interesting.

I have a theory after reading the statement that the game tend to use a lot of video memory than usual. I do think that the game may just use this tactic to "optimise" the game instead of manually managing memory manually. So tried every single way to "lie" to the game that I'm starving VRAM with every DXVK configs I could think of

```
DXVK_HUD=memory DXVK_CONFIG="dxgi.emulateUMA = True; dxgi.maxDeviceMemory = 2; dxgi.maxSharedMemory = 0; d3d11.zeroWorkgroupMemory = True; dxvk.halveNvidiaHVVHeap = True;" %command%
```

I don't know which options do make a difference, but after this, the game now tries to be very, very conservative on VRAM usage instead lol. It always kicked off to full VRAM usage before.

![An image of a game that runs fine with lower RAM usage](https://github.com/user-attachments/assets/2cacd077-da07-4e8b-acc0-8169d7a46cc3)

Be warned, these launch options cause significantly more stutter than usual, but it no longer runs out of video memory.

**Comment by cybik** [comment]
> This is very interesting.
> 
> [...]
>
> ```
> DXVK_HUD=memory DXVK_CONFIG="dxgi.emulateUMA = True; dxgi.maxDeviceMemory = 2; dxgi.maxSharedMemory = 0; d3d11.zeroWorkgroupMemory = True; dxvk.halveNvidiaHVVHeap = True;" %command%
> ```

Very interesting indeed. With that config - and the fact that 1.1 also drove down the OOM issues quite a bit on my RTX3080 - the memory overuse SEEMS to be getting mitigated QUITE A BIT. I've not broken 8gb total in my validation, whereas booting into the game, warping to Scott Outpost and merely walking into the tent gets me to 8gb+ total VRAM (5.ish GB to ZZZ alone).

VERY nice find, @SysError99. Much appreciated.

**Comment by K0bin** [comment]
Heads up: we're gonna remove that option in the next version.

**Comment by cybik** [comment]
> Heads up: we're gonna remove that option in the next version.

which one? nVidia HVV heap or ZeroWorkgroup?

**Comment by SysError99** [comment]
I got a conclusion, there's two options that need to be set in order to lie the game (at least, on my machine), `dxgi.enableUMA`, and `dxgi.maxDeviceMemory`. The `dxgi.maxDeviceMemory` can be set to any low value but zero, and the game now behaves properly with low memory graphics cards.

```
DXVK_HUD=memory DXVK_CONFIG="dxgi.emulateUMA = True; dxgi.maxDeviceMemory = 1;" %command%
```

Yes..., the option that happened to be removed in further versions (https://github.com/doitsujin/dxvk/commit/eb8d1885bde916b3476229a9220952ad0f639ff9) happens to be the option that's crucial for this workaround to work...

---

I did surf the `dxgi_adapter.cpp` a little bit, it seems like this is all that the option `dxgi.emulateUMA` does.

```cpp
if ((m_adapter->isLinkedToDGPU() && deviceProp.deviceType == VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU) || 
    options->emulateUMA) {
    sharedMemory = std::max(sharedMemory, deviceMemory);
    deviceMemory = 512ull << 20;
}
```

The `deviceMemory` must be set to anything in absurd value in order to get it working (in this case, `512 << 20` or `536870912`). So I did try to set the `maxDeviceMemory` to an absurd value, but this code section blocked me away to do it...

```cpp
// Some games are silly and need their memory limited
if (options->maxDeviceMemory > 0
 && options->maxDeviceMemory < deviceMemory)
    deviceMemory = options->maxDeviceMemory;

if (options->maxSharedMemory > 0
 && options->maxSharedMemory < sharedMemory)
    sharedMemory = options->maxSharedMemory;
```

I think we just need to remove true max memory limit to allow its users to freely set any values into it. We just need to warn them that it can be risky and may crash their machine, like below.

```cpp
// Some games are silly and need their memory limited
if (options->maxDeviceMemory > 0)
    deviceMemory = options->maxDeviceMemory;

if (options->maxSharedMemory > 0)
    sharedMemory = options->maxSharedMemory;
```

**Comment by SysError99** [comment]
Never freaking mind, I read the code thoroughly again, and all I need to do is to set both `maxDeviceMemory` and `maxSharedMemory` to the lowest possible lol.

```
DXVK_HUD=memory DXVK_CONFIG="dxgi.maxSharedMemory = 1; dxgi.maxDeviceMemory = 1;" %command%
```

Case closed!

**Comment by Blisto91** [comment]
> The deviceMemory must be set to anything in absurd value in order to get it working (in this case, 512 << 20 or 536870912), and the sharedMemory must be very low value.

The in code value is in bytes which why the number is so big. `deviceMemory = 512ull << 20;`  is just 512MB.

[In the 2.4 release](https://github.com/doitsujin/dxvk/blob/02d8fa593b45390a72d1bc43bc5ddb46d7ee469f/src/dxgi/dxgi_adapter.cpp#L347) the only thing the `dxgi.enableUMA` option does is the equivilant of setting `dxgi.maxDeviceMemory` to 128 and `dxgi.maxSharedMemory` to the amount of vram you GPU has.
Now as you showed above the exact numbers changed a but on master before the option got pulled but the concept is more or less the same.


While i was typing this i see you figured out it wasn't a high number anyway. 
The reason setting something like `dxgi.maxDeviceMemory` to a low number is that you are telling the game that you have less vram than you actually have (1 being 1MB) and if the game cares about that it might try and be more careful with it's usage.
When i tested it ingame it seems like it might be more aggressive in freeing vram again instead of keeping it around. Also maybe pulling less in to it to begin with? Not completely sure.
