### ISSUE TITLE
Further usage of Github for dxvk?

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#418]
In light of MS buying GIthub, is it good for dxvk to continue using it? MS have expressed quite aggressive view on copyrightability of APIs in the past. Would moving somewhere else be beneficial?

**Comment by ssorgatem** [comment]
While Microsoft's history certainly doesn't show much promise... I think it may be a tad bit too early to make any decision.

But I think it'd be in every project's best interest not to have GitHub for granted.

**Comment by shmerl** [comment]
Not sure if making the decision after something happens is a good outcome either :) Above I was referring to [this](https://www.zdnet.com/article/microsoft-teaming-up-with-oracle-against-google-in-java-case/).

**Comment by ZachBacon** [comment]
I believe it wouldn't be in Microsoft's best interest to be honest anything big etc would probably cause an uproar. but that's my opinion on the matters.
But if there's still concern, one could mirror the repo to say gitlab and keep GitHub for now until there's some issue, this way there is always a backup.

**Comment by shmerl** [comment]
This isn't really a discussion of what is hypothetically in MS interests or not, but rather about what's best for the project in the light of documented legal position of MS on these matters.

**Comment by doitsujin** [comment]
For now I have no immediate plans of migrating to a different platform, although I'll certainly do so if there are any signs that I won't be able to continue using Github in the future. Right now that's just not the case.

I'd suggest to just calm down and see what happens in the coming months. DXVK doesn't *depend* on Github in any way, so migrating the project should be easy in case it does actually become necessary, but right now I don't actually think it's a good idea.

Locking this thread because I don't want it to turn into any sort of discussion that doesn't belong here, but I'll keep it visible for now in case similar questions arise.
