### ISSUE TITLE
Error spam in d3d11 log for Magic the Gathering Arena

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#425]
Magic the Gathering Arena works but throws out a bunch of errors in the d3d11 log. I haven't tested in-game yet as they still haven't sent the access key for my account.

### Software information
Magic the Gathering Arena
Low

### System information
- GPU: GTX 960
- Driver: 396.24.02
- Wine version: Staging 3.9
- DXVK version: e35cbf8

### Apitrace file(s)
- Put a link here

### Log files
- [MTGA_d3d11.log](https://github.com/doitsujin/dxvk/files/2082379/MTGA_d3d11.log)

- [MTGA_dxgi.log](https://github.com/doitsujin/dxvk/files/2082380/MTGA_dxgi.log)

**Comment by doitsujin** [comment]
Most of those errors aren't really bugs in DXVK and won't be fixed.

`err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10/14`
These are part of D3D 11.2, which DXVK does not support. The game should expect these queries to fail because this is unsupported on older Windows versions as well.

`err:   D3D11: Unsupported format: 4294967295`
Game bug. `4294967295` is *not* a valid format and cannot be used for anything, so querying support for this format enum will fail.

`err:   D3D11: Unsupported format: 107`
This is a YUV format which is currently not supported in DXVK. This is the only message that could potentially be problematic, but seeing that it queries even invalid enum values I don't think this is actually going to be an issue.
