### ISSUE TITLE
Once Human crashes on character creation/opening inventory

### ISSUE THREAD

**Issue by shelterx** [doitsujin/dxvk#4304]
Once Human crashes on character creation/opening inventory
Seems to work in DX12 (vkd3d-proton) mode but not DX11 however I'm not very far into the game because of current issues.

- GPU: Nvidia RTX 4070
- Driver: 560.35.03 (also tried Dev 550.40.75)
- Wine version: proton-cachyos (based on proton experimental) Apparently proton-8 used to work, but doesn't anymore.
- DXVK version: https://github.com/doitsujin/dxvk/commit/e6f89062f5a5af96c4ae28d2ac441e54fbe94068

Valve Proton issue report:
https://github.com/ValveSoftware/Proton/issues/7888

[steam-2139460.log.gz](https://github.com/user-attachments/files/17178939/steam-2139460.log.gz)

**Comment by mbriar** [comment]
Lost of d3dcompiler log spam (which isn't part of DXVK). Try installing native `d3dcompiler_47` with winetricks/protontricks.

**Comment by Blisto91** [comment]
Yes when I poked shortly at this a few days ago it seemed to be a d3dcompiler issue

**Comment by shelterx** [comment]
Interesting, yes installing d3dcompiler_47 helped.
I'll leave the issue open for a while in case I run into something.

**Comment by K0bin** [comment]
Just reopen it, if you run into other problems.

**Comment by Orin-Alchemical-3D** [comment]
I can tell you for certain that d3dcompiler_47 does not fix this.   It does clean logs up some and helps with a couple messed up textures.   The issue goes much deeper.   This game used to work 100% on Proton 7, but since a recent update you can no longer run on anything lower than Proton 9, and its a stutter/lockup fest ever since.   Load keeps falling off the GPU and everything.   We have been trying everything under the sun to get this fixed but seems to be a more advanced problem than most of the users can overcome.

**Comment by shelterx** [comment]
It did fix the crash in character screen /  inventory, which this issue was about. The performance issues are something else.
