### ISSUE TITLE
Compiling latest dxvk with -march=native (znver2) causes games to crash

### ISSUE THREAD

**Issue by ghost** [doitsujin/dxvk#4447]
compile commands:
```
meson setup --cross-file build-win64.txt --buildtype release \
--prefix /mnt/gitdisk/root/dxvk --libdir lib64 --bindir bin64 build64 \
-Dc_args="-march=native -pipe" -Dc_link_args="-march=native -pipe" \
-Dcpp_args="-march=native -pipe" -Dcpp_link_args="-march=native -pipe" \
-Dstrip=true \
&& ninja -C build64/ install

meson setup --cross-file build-win32.txt --buildtype release \
--prefix /mnt/gitdisk/root/dxvk --libdir lib32 --bindir bin32 build32 \
-Dc_args="-march=native -pipe" -Dc_link_args="-march=native -pipe" \
-Dcpp_args="-march=native -pipe" -Dcpp_link_args="-march=native -pipe" \
-Dstrip=true \
&& ninja -C build32/ install
```

test environment:
I recreated Proton Experimental bleeding edge's folder structure in /Steam/compatibilitytools.d/ and symlinked all files sans dxvk dlls.
Games tested: Arma 3 for 64bit and Company of Heroes 1 for 32bit. Arma 3 makes it to the splash screen then crashes. CoH pops up it's crash report mailer.

-march=x86-64-v3 also fails. -march=x86-64-v2 works with reduced performance. compiling without custom flags works fine. My cpu is AMD zen2 3500x
I skimmed the discussion about how adding newer instruction sets does nothing basicly. So no biggie I suppose.
Hopefully I'm not being an idiot again.

**Comment by WinterSnowfall** [comment]
Sounds like a compiler bug? That being said, why not simply add `-march=native` in dxvk's Meson script instead of `-msse3` and friends? You'd still want the sse math among other things that are already in there.

Also note `-march=native` can be rather problematic in this day and age when (as an example) disabling your E cores may expose instructions specific to your P cores. And indeed, I have tested this myself a while back (worked for me at least), but it brings little if any benefit.

**Comment by Blisto91** [comment]
What error does the games crash with in log?

**Comment by doitsujin** [comment]
Can repro, got a crash with `0x006ffffd515001 d3d11+0xc5001: vmovdqa %ymm0, 0x40(%rsp)`

This pretty much proves that there has to be some sort of stack alignment issue *somewhere*. I'm not entirely sure what's going on here, stack alignment is 16 and not 32 so this kind of code should never be emitted, and we don't really use `alignas(≥32)` on anything that's stack-allocated either...

**Comment by doitsujin** [comment]
Still looks like a compiler issue though and it doesn't look like it's possible to work around that, short of not allowing the use of `ymm` registers (i.e. no avx, not sure if there's a way to only allow 128-bit AVX).

**Comment by ViNi-Arco** [comment]
If you want DXVK with AVX, you'll need to build with MSVC or Clang+Mingw, GCC+Mingw needs a special [patch](https://github.com/msys2/MINGW-packages/blob/190473836580d4ceede97c1bcd7a49758afb9313/mingw-w64-gcc/0200-add-m-no-align-vector-insn-option-for-i386.patch), and the compiler aligning to 32 may be due to AVX 256 znver2

**Comment by ViNi-Arco** [comment]
> Used openSUSE's Build Service to produce a patched Mingw

Very good 😊, I see you've used the [patch](https://build.opensuse.org/projects/home:DunningKruger:devel/packages/mingw32-gcc/files/dxvkavx-fixed.patch?expand=1) and are using the new flag, if you're going to try Graphite optimizations I recommend building against isl 0.25, in my tests it's more consistent than 0.26

**Comment by ventureoo** [comment]
A small note for those who face the same issue: rebuild mingw with `-mno-align-vector-insn` patch is not necessary, this issue is fixed by adding flag `-mpreferred-stack-boundary=2` for 32-bit DXVK DLLs, at least tested in CoH, without it the game indeed crashes with `-march=native`. By adding this flag in Wine's upstream, many similar game crashing issues when using AVX have been also fixed:

 https://gitlab.winehq.org/wine/wine/-/commit/4b458775bb8c9492ac859cfd167c5f54f245dec1
