### ISSUE TITLE
Deprecation of most DXVK_* environment variables

### ISSUE THREAD

**Issue by doitsujin** [doitsujin/dxvk#538]
With the next release, support for most DXVK environment variables **will be removed** in favour of a per-game configuration file as described on the [Wiki](https://github.com/doitsujin/dxvk/wiki/Configuration), which offers the same options as well as some new ones. This change is already implemented in the current `master` branch.

The following environment variables, which sometimes need to be set in order to run a game, will **no longer be available**:
- `DXVK_FAKE_DX10_SUPPORT`
- `DXVK_CUSTOM_VENDOR_ID`
- `DXVK_CUSTOM_DEVICE_ID`
- `DXVK_FEATURE_LEVEL`

**If you know a game which requires one of these environment variables to be set, and is not listed [here](https://github.com/doitsujin/dxvk/blob/master/src/util/config/config.cpp#L13) yet, please let me know in the comments.**

The goal is to enable the required options by default and improve out-of-the-box compatibility with those games, which should make life for e.g. Lutris users and maintainers a bit easier.

The following environment variables **will not be removed** and can safely be used in the future:
- `DXVK_LOG_LEVEL`
- `DXVK_HUD`

**Comment by pchome** [comment]
> The following environment variables will not be removed and can safely be used in the future

Why not to use them in config as well?

I'm using "Steam" prefix with this variables set to whole prefix in `q4wine` settings. All games launched from steam acquires this settings, but sometimes one of a game need to be debugged/adjusted, than steam need to be restarted.

With per app config  `DXVK_LOG_LEVEL` (an other) only config file will require to be changed. Ideally it's good to have all of them in per-app config file.

> If you know a game which requires one of these environment variables to be set, and is not listed here yet, please let me know in the comments.

JustCause2.exe : `dxgi.fakeDx10Support` (for `DXUP`).

**Comment by gort818** [comment]
Sleeping Dogs Definitive Edition needs DXVK_FAKE_DX10_SUPPORT

**Comment by doitsujin** [comment]
@gort818 What's the exact exe name for that game?

**Comment by gort818** [comment]
@doitsujin It should be sdhdship.exe

**Comment by mrdeathjr28** [comment]
https://github.com/doitsujin/dxvk/issues/538#issuecomment-411542456

As gort818 shows sleeping dogs still needed DXVK_FAKE_DX10_SUPPORT and others case grandia II anniversary edition, age of mythologies extended edition

Maybe can allow DXVK_FAKE_DX10_SUPPORT for now until dxvk games databasee grow up more (lack of many games)

**Comment by Guy1524** [comment]
What about DXVK_FEATURE_LEVEL?

**Comment by doitsujin** [comment]
@mrdeathjr28 I need the exact exe names for those games, just the name of the games doesn't help.

**Comment by thirdeyefunction** [comment]
@doitsujin 

HKShip.exe for original Sleeping Dogs and
sdhdship.exe for the definitive edition (they both require it)

**Comment by mrdeathjr28** [comment]
https://github.com/doitsujin/dxvk/issues/538#issuecomment-411578928

I dont know what problem have with your setup both here runs without problem, tested around 2hr 30min

https://www.youtube.com/watch?v=5I6Pd3Jmzo8

System Specs Used in Test

Xubuntu 18.04 x64 - Kernel 4.15.0-22 generic (ubuntu mainline) - 

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz + CoolerMaster Hyper T4

MEMORY: 8GB DDR4 2400mhz (4x2) Mushkin (dual channel: 37.5 gb/s)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

**Comment by doitsujin** [comment]
@mrdeathjr28 what do you mean? I don't understand that sentence.

**Comment by mrdeathjr28** [comment]
@doitsujin 

Is more simple leave actual DXVK_FAKE_DX10_SUPPORT than build DX10 game database

**Comment by doitsujin** [comment]
But the workaround is still there? I just want to have it enabled for all games that need it by default so that users don't have to mess around with it.

**Comment by mrdeathjr28** [comment]
@doitsujin 

The Intention is good but environment variable prevent build game database (less work for you)

With variable the user can decide if need activate or not (however DXVK_FAKE_DX10_SUPPORT must stay as default or until DXUP stay integrated in DXVK)

**Comment by pchome** [comment]
You can find actual game exe name via https://steamdb.info/search/

* Set `App Type` to `Game`
* Enter game name
* Click on actual app id
* Select Configuration tab

e.g. https://steamdb.info/app/330390/config/

**Comment by sputniktr02** [comment]
S.T.A.L.K.E.R Call of Pripyat also needs DXVK_FAKE_DX10_SUPPORT. Game exe is: **xrEngine.exe**

**Comment by doitsujin** [comment]
Thanks for the entries so far. I will add them all at once shortly before tagging the next release.

**Comment by yoshimo** [comment]
in addition to Wow.exe you should include WowB.exe and WowT.exe as well.
B stands for Beta and T for the "Public TEST Realm" executables where people participate in the testing of upcoming content.

**Comment by SveSop** [comment]
As i am not particularly fan of "default enabled" stuff, MY opinion would be to remove ALL default "in-compiled-options" and make the config file pick up options based on .exe name (like is done in the source).

This way, dxvk could include the config in some default location (inside the dxvk install folder), unless overridden by the `DXVK_CONFIG_FILE=` env variable.

Why? Cos its a lot easier to open that "default-installed-config" file and look at new default settings as they get updated vs. reading commit-messages or actual source. Having default settings hard-coded in the source is not the most elegant way of doing this.

What about this approach:
IF env-variable set -> use spesified conf
IF .conf located in game .exe folder -> use game .exe folder .conf
Else Use default included .conf in dxvk-install-folder.

That way, you would still be able to include "out-of-the-box" working settings, AND users can choose to tweak themselves.

Yeah, as i said, i am aware that the .conf overrides the hard-coded settings, but keeping track of the different defaults is harder. 

Example: Lets say i played WoW beta. Before the included fix, i had to use my own config, as WowB.exe was not hard-coded. Since i dont read source every day, i keep using my config. Then someone finds out some NEW setting that is needed to gain 20 fps in WowB.exe, and hard-codes this in the source, but i miss reading that 1 commit, and thus keeps using my custom .conf.

Just an idea :) Im all about "customer choice" while KISS :)

**Comment by doitsujin** [comment]
@SveSop that would **require** a config file to be present, which is incredibly bad news for anyone setting it up with Lutris or winetricks.

**Comment by doitsujin** [comment]
Another thing to keep in mind is that some of these hacks are meant to be removed anway, That includes the "fake D3D10" toggle - I already have a (highly experimental) [d3d10](https://github.com/doitsujin/dxvk/tree/d3d10) branch up and as soon as it is ready to be mainlined, the option will be removed entirely, including the default entries.

**Comment by doitsujin** [comment]
0.65 is out and should include all the apps you reported (see commit 6e74db4c6f069201dca857fe3847bf44f3ea87bc).

**Comment by sputniktr02** [comment]
Just here to report that S.T.A.L.K.E.R Call of Pripyat does not work by default. I had to create dxvk.conf file beside **Stalker-COP.exe** and override **dxgi.fakeDx10Support = True**. Perhaps **xrEngine.exe** should also be added in the commit. I think **Stalker-COP.exe** is acting like a launcher for the **xrEngine.exe** which is what process monitor shows as the game process.

**Comment by SveSop** [comment]
@doitsujin I see there could be problems where the default .conf file is missing or otherwise placed in a wrong position.

Ill just have to browse through [https://github.com/doitsujin/dxvk/blob/master/src/util/config/config.cpp](url) too try to keep up :P

**Comment by abenson** [comment]
**Raft.exe** needs `DXVK_FAKE_DX10_SUPPORT`

**Comment by doitsujin** [comment]
No, it doesn't, unless you're running outdated dxvk versions.

**Comment by SveSop** [comment]
@abenson 
[https://github.com/doitsujin/dxvk/commit/7fa6dddc9ee30a58cc073e44fe9d11ea49d3a3ed](https://github.com/doitsujin/dxvk/commit/7fa6dddc9ee30a58cc073e44fe9d11ea49d3a3ed)

**Comment by SveSop** [comment]
@abenson 
Depending on how you install DXVK (using script, or doing it manually), you could check that your wineprefix have the following dll-overrides:
```
d3d10
d3d10_1
d3d10core
d3dcompiler_43
d3d11
dxgi
```
They should all be set to "native". 

I'm only asking this, cos you might (as i am) be setting this up manually, and with a new build where the DXVK_DAKE_DX10_SUPPORT is removed, DX10 is provided by the respective .dll's and is needed for those games that need dx10 support of sorts :) (Especially since it worked before)
