### ISSUE TITLE
Tom Clancy's: The Division 

### ISSUE THREAD

**Issue by tr37ion** [doitsujin/dxvk#545]
I finally got The Division working. It's so awesome @doitsujin thanks for all your work.

I'm running:
CPU: Ryzen 2700
GPU: Nvidia GTX 1070 
Nvidia: 396.45
Wine: 3.13 Staging (latest ArchLinux wine-staging)
DXVK: 0.62

There is a small issue with playing videos and the game itself. Maybe it is just because of shader compiling on the first start - not sure, but I just want to let you know, that every time the following info log is shown, the game stutters/hangs:

```
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1080
```

Sometimes there is an additional msg:

```
[0811/171637.219:WARNING:PushPullFIFO.cpp(182)] PushPullFIFO: underflow while pulling (underflowCount=1, availableFrames=0, requestedFrames=480, fifoLength=12288)
```

If there is a chance to fix this, this would be nice. Possibly it is just a small issue

**Comment by doitsujin** [comment]
The swap chain message only pops up when the game actually has to re-create the Vulkan swap chain, either because it enables/disables Vsync, changes the color format, or resizes the window. This **is** a somewhat expensive operation, but cannot be avoided

Not sure what the other message means or where it even comes from, but it's not related to dxvk.

Anyway, whatever the issue is, I can't do anything about it, especially with this little information given.
