### ISSUE TITLE
DXVK uses scissors larger than the framebuffer

### ISSUE THREAD

**Issue by jekstrand** [doitsujin/dxvk#585]
I just found this happening in Batman: Arkham City.  I don't know that it's causing any problems but it is in violation of the spec.  In section 25.3, the Vulkan spec says:

> It is legal for offset.x + extent.width or offset.y + extent.height to exceed the dimensions of the framebuffer

But DXVK likes to use 32767x32767 scissors on 1920x1024 framebuffers.  It's possible this is the app doing something wrong and DXVK just passing it through but I don't really know.

**Comment by ZeroFault** [comment]
I'm confused. The thing you quoted  says it is **_legal_** to have scissors exceed the framebuffer dimensions.

**Comment by jekstrand** [comment]
I'm sorry.  I've read that line dozens of times and aparently misread it dozens of times. :(  Sorry for the noise.

**Comment by doitsujin** [comment]
I think *effectively disable* in this context just means that even if it is performed by the hardware, no fragments will be discarded. I think RADV just clamps the scissor rectangle multiple *anyway* before submitting it to the hardware, e.g. to make sure it doesn't exceed the viewport.

Setting it to the framebuffer size just means doing more work than necessary, since the framebuffer size is not known when the scissor is set on the d3d side, so we'd have to clamp it in the state tracker.
