### ISSUE TITLE
AMD RADV Just Cause 3 Flickering Textures

### ISSUE THREAD

**Issue by Alexander88207** [doitsujin/dxvk#613]
Last Update: 11.13.2018

OS: Arch-Linux 64-Bit
CPU: AMD FX 8350
GPU: AMD RX 570
GPU Driver: 4.4 OpenGL Mesa 18.2.4 
Wine: 3.19
Apitrace: Can not be apitraced!
Video: https://www.youtube.com/watch?v=gyWrp4kFAc0
Mesa Bug Report: https://bugs.freedesktop.org/show_bug.cgi?id=107822
Happends with AMDVLK too? : not confirmed (Will be updated later)

**Comment by doitsujin** [comment]
Apitrace?

**Comment by CrackedCrafterz** [comment]
what do you mean with that?

**Comment by doitsujin** [comment]
I'm asking for an apitrace so that I can actually look into the problem.

Please don't file a bug report if you can't provide **any** info. "Later" is not something I can work with.

**Comment by CrackedCrafterz** [comment]
Okay i understand

**Comment by doitsujin** [comment]
Also, which Mesa version are you running? You only posted your GPU and LLVM version.

**Comment by CrackedCrafterz** [comment]
18.6.1 i know 18.7.1 and LLVM 8 is on arch available but i dont want to use unstable branches.

**Comment by CrackedCrafterz** [comment]
So I have now added all the necessary information.

**Comment by Tk-Glitch** [comment]
Mesa 18.1 and llvm 6 won't cut it.

**Comment by doitsujin** [comment]
If you use wine-staging, please disable `nvapi` and `nvapi64` in winecfg. There were issues with that before.

**Comment by CrackedCrafterz** [comment]
I now updated the post with Apitrace. Unfortunately it was not possible to enter the game through this DLL ´ ś I have maximum 3FPS and the game crashes in the loading screen.

**Comment by CrackedCrafterz** [comment]
And found out something?

**Comment by Veelhiem** [comment]
I'm also having this issue. I'm running llvm-svn and mesa-git (both built 12/Sep/18) on Arch Linux. Hardware: RX 580, Ryzen 5 1600, 16GB RAM. I am using the amdgpu open source driver.

The game crashes when the apitrace dlls are installed, not sure if this is normal. The link to the trace is Google Drive because I cant upload it straight to github. [apitrace download](https://drive.google.com/file/d/1-5_fruwV4vT9JQ87STui_QWkvd_mSvhV/view?usp=sharing)

**Comment by doitsujin** [comment]
By the way, have you guys disabled `nvapi` and `nvapi64` in winecfg?

**Comment by Veelhiem** [comment]
Yes I have, just tried again and it didn't seem to change anything. The textures still flicker like crazy in the main menu and in game.

**Comment by doitsujin** [comment]
No idea then. Can't reproduce with the apitrace that works.

**Comment by CrackedCrafterz** [comment]
For me the game works with Apitrace only with 1FPS but it works. But is it helpful with DXVK? because here is written "Dont use DXVK and Apitrace together"

**Comment by doitsujin** [comment]
My issue is that I don't see the bug with the apitrace you already posted. If you can record one that actually shows the issue, please go ahead.

Using DXVK with Apitrace together *may* be fine in this case.

**Comment by C0rn3j** [comment]
I'm going to piggyback off here since I also can't get the apitrace for the same game.

The water doesn't render at all when viewed from above, inside view works. (Nvidia 396.54.09, DXVK 0.90, wine-staging 3.19 (git))

![2018-10-31_10-16-16](https://user-images.githubusercontent.com/1641362/47778829-f75e8600-dcf7-11e8-9fe8-c3e0f7eb7bd6.png)

Trying to put the DLLs in the game folder makes it crash after a few seconds just like for other people in this thread.

Trying to make it launch without DXVK makes the game crash without even loading the main window.

Is there anything I can do at this point to properly report the issue?

**Comment by CrackedCrafterz** [comment]
> **EDIT: NVM - disabling nvenc and nvcuda solves the issue - [#379 (comment)](https://github.com/doitsujin/dxvk/issues/379#issuecomment-392371155)**
> 
> I'm going to piggyback off here since I also can't get the apitrace for the same game.
> 
> The water doesn't render at all when viewed from above, inside view works. (Nvidia 396.54.09, DXVK 0.90, wine-staging 3.19 (git))
> 
> ![2018-10-31_10-16-16](https://user-images.githubusercontent.com/1641362/47778829-f75e8600-dcf7-11e8-9fe8-c3e0f7eb7bd6.png)
> 
> Trying to put the DLLs in the game folder makes it crash after a few seconds just like for other people in this thread.
> 
> Trying to make it launch without DXVK makes the game crash without even loading the main window.
> 
> Is there anything I can do at this point to properly report the issue?

nvapi, nvapi64, nvenc and nvcuda must be disabled in winecfg

**Comment by RarogCmex** [comment]
Mesa 18.3.0_rc2 + llvm-7.0.0. nvapi, nvapi64, nvenc and nvcuda are off.
Issue still having...

**Comment by doitsujin** [comment]
Well I can't do anything about it because I have no way to reproduce it.

**Comment by debianxfce** [comment]
Windows users have the flickering problem too so it is a game problem.
https://steamcommunity.com/app/225540/discussions/0/485623406960295918/
https://steamcommunity.com/app/225540/discussions/0/487877107140165216/

**Comment by Alexander88207** [comment]
> Windows users have the flickering problem too so it is a game problem.
> https://steamcommunity.com/app/225540/discussions/0/485623406960295918/
> https://steamcommunity.com/app/225540/discussions/0/487877107140165216/

my knowledge, it was with the latest wine version fixed.

**Comment by RarogCmex** [comment]
Couldn't get the apitrace: game freezes. Here is the launch log:
[start.log](https://github.com/doitsujin/dxvk/files/2783693/start.log)

**Comment by RarogCmex** [comment]
Here is the log of apitrace try with vulkan debug enabled:
[start.log](https://github.com/doitsujin/dxvk/files/2783754/start.log)

**Comment by RarogCmex** [comment]
Here is the log without apitrace but with vulkan layers and dxvk debug enabled:
[JustCause3_dxgi.log](https://github.com/doitsujin/dxvk/files/2783794/JustCause3_dxgi.log)
[JustCause3_d3d11.log](https://github.com/doitsujin/dxvk/files/2783795/JustCause3_d3d11.log)
[start.log](https://github.com/doitsujin/dxvk/files/2783796/start.log)

**Comment by doitsujin** [comment]
Log files aren't useful to debug this problem *at all*. I need an apitrace to reproduce the problem.

**Comment by debianxfce** [comment]
> > Windows users have the flickering problem too so it is a game problem.
> > https://steamcommunity.com/app/225540/discussions/0/485623406960295918/
> > https://steamcommunity.com/app/225540/discussions/0/487877107140165216/
> 
> my knowledge, it was with the latest wine version fixed.

Those two links are from windows users, so small flickering is a game problem.  Setting nvapi, nvapi64, nvenc and nvcuda off does not have effect with Mesa drivers. The game runs as good as in windows so play it.

**Comment by jcfrosty** [comment]
https://github.com/ValveSoftware/Proton/issues/1295

So issues are occurring with Tokyo Xanadu eX+ as well.  Everything ran perfectly with DXVK 1.0.X but ever since proton updated to DXVK to v1.1.1. The game flickers and is unplayable. the HUD is solid, the pause screen/menu works fine, the game start menu works great. Its just the game play portion that flickers black constantly.

Is there anyway I could help pin point the regression?

Thanks,
Frosty

**Comment by Alexander88207** [comment]
Im closing this bug now because I'm not interested in the game anymore and I'm sure nothing will change here.
