### ISSUE TITLE
Support MacOS via Vulkan Portability

### ISSUE THREAD

**Issue by kvark** [doitsujin/dxvk#634]
Vulkan isn't natively available on MacOS, but it's becoming more accessible as a user-space layer. It would be great to have the corresponding Meson configuration setup, build instructions, and eventually CI coverage.

**Comment by kvark** [comment]
@cdavis5e - would you have something to share in this regard? Given your continuous work to chop through the dxvk/vkd3d blockers on MoltenVK, you probably have some sort of a playground setup.

**Comment by doitsujin** [comment]
I cannot support that platform. If you need Mac support, someone who actually uses one has to provide support.

**Comment by Leopard1907** [comment]
FYI , texture swizzling resolved on gfx layer.

https://github.com/RPCS3/rpcs3/pull/4996

At least worked around for RPCS3 on MacOS.

But , i rather his focus on DXVK only. Not on Mac. So Philip shouldn't make adjustments , people should adjust their layers to DXVK.

**Comment by K0bin** [comment]
They work around the lack of swizzle support by doing that manually on the cpu and in shaders,

While that could be done for DXVK, the missing shader stages are the biggest problem.

**Comment by Leopard1907** [comment]
I agree , that's why i said Philip shouldn't make workarounds.

It is an open source project , people can make adjustments on their forks etc.

If Philip involves with MacOS that would also mean he would have to consider MacOS situation on every step.

**Comment by Guy1524** [comment]
@kvark yes, the VKx discord is good place where DXVK development is discussed

https://discord.gg/wHBTezH

**Comment by doitsujin** [comment]
Texture swizzles are crucial to implement a number of texture formats (the most common one being `A8_UNORM`). That's something MoltenVK should try to emulate on their end if possible.

DXVK already emulates swizzles for render targets since Vulkan doesn't support that, but that's effectively a zero-cost emulation since the render target formats are known at the time shaders are compiled. For sampled textures this would be *much* harder to support.

Another thing is extensions - does MoltenVK implement all the extensions that DXVK currently depends on? If not, there are going to be more issues. And the upcoming transform feedback EXT will probably make things worse. I just don't see full D3D11 support happen on Mac OS X, as nice as it would be.

**Comment by Guy1524** [comment]
Looking through MoltenVK source, here's the list of supported extensions:

VK_MVK_moltenvk;
VK_MVK_macos_surface;
VK_MVK_ios_surface;
VK_KHR_surface;
VK_KHR_swapchain;
VK_KHR_maintenance1;
VK_IMG_format_pvrtc;
VK_AMD_negative_viewport_height;
VK_KHR_shader_draw_parameters;
VK_KHR_get_physical_device_properties2;
VK_KHR_push_descriptor;
VK_KHR_descriptor_update_template;

**Comment by K0bin** [comment]
More information in here: https://github.com/KhronosGroup/MoltenVK/issues/203

**Comment by kvark** [comment]
@doitsujin Vulkan Portability != MoltenVK. I represent [gfx-portability](https://github.com/gfx-rs/portability). I'd appreciate if we discuss this in a more general sense of Metal limitations instead of MoltenVK implementation  details.

> Texture swizzles are crucial to implement a number of texture formats (the most common one being A8_UNORM). 

That got me curious as well, since D3D11 doesn't have swizzling. You must be requiring a limited set of swizzles to cover formats that are in D3D11 but missing from Vulkan, and we might be able to provide them. For example, `A8Unorm` is [already a supported swizzle](https://github.com/gfx-rs/gfx/blob/e7b3ede00cdaef91eff588694eac7c610fd0d136/src/backend/metal/src/conversions.rs#L148). Is there a list of formats+swizzle combinations for us to work on?

In terms of extensions, there is indeed still work to do, but it's not the end of the world.

> And the upcoming transform feedback EXT will probably make things worse.

I don't think it's worse. TF via vertex stage should be fairly trivial in Metal. TF via geometry shader / tessellation is more of a problem for those shader stages not supported natively by Metal, not as much of a problem for TF specifically.

**Comment by doitsujin** [comment]
> Is there a list of formats+swizzle combinations for us to work on?

(R,G,B,1) might be useful for some RGBX formats where the 'X' component is ignored.

> TF via geometry shader / tessellation is more of a problem for those shader stages not supported natively by Metal

Transform feedback via geometry shaders is the only thing that is supported in D3D11. It's annoying to emulate because it may require a compaction pass when vertices are conditionally emitted, but if Metal doesn't support geometry shaders, you'll probably have to do that anyway.

**Comment by doitsujin** [comment]
Your GPU is too old, it doesn't support D3D11.

**Comment by Hello71** [comment]
In fact it does. You can see at https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Features_Overview that Evergreen and Northern Islands class cards support D3D feature level 11_0. Also, TW3 runs fine in Windows (well, renders properly. can't turn the settings up beyond medium otherwise the fps goes to shit). I want to run it under Linux because the AMD drivers are unmaintained and don't even properly support dual monitor.

**Comment by doitsujin** [comment]
Well, you only said "TeraScale", which also includes pre-D3D11 GPUs, I couldn't know that you *actually* meant something else. Why not just name your GPU to avoid confusion?

Anyway, I don't see how gfx-rs is supposed to help you when there is no Vulkan support for your GPU, or what this has to do with Mac OS X.

**Comment by Hello71** [comment]
gfx-rs apparently supports rendering to opengl, although I'm not totally sure how that works.
