### ISSUE TITLE
Question about new transform feedback support: Metro LL still gets "Rasterized stream not supported"..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#698]
Hi,
with a quick test on 0.9.0+ new NV drivers I see Unity Adam demo is rendering correctly finally!!
and Metro LL launches now without:
d3d11.fakeStreamOutSupport = True

but in MetroLL_d3d11.log

errors *before* were:
```
err:   D3D11: CreateGeometryShaderWithStreamOutput:
  Transform feedback not supoorted by device
```
now are:

> err:   D3D11: CreateGeometryShaderWithStreamOutput: Rasterized stream not supported

so question "Rasterized stream not supported" is because VK ext. limitations or DXVK limitation?
thanks..

**Comment by shmerl** [comment]
Are you using patched Wine? Wine upstream didn't catch up to it yet.

**Comment by doitsujin** [comment]
Simultaneous stream output and rasterization is currently not supported in DXVK. The Vulkan extension allows it, but it's somewhat painful to implement, and I wasn't aware of any game that needs it.

Given that both versions of Last Light have native Linux support I'm not sure if I really care though. Was this with the original version of the game or with the Redux version?

**Comment by oscarbg** [comment]
@shmerl using patched Wine..
@doitsujin original version.. not really a problem, as you say Redux versions have native Linux binaries..
any way good to know Vulkan ext. supports simultaneous stream output and rasterization anyway..
Closing..

**Comment by mrdeathjr28** [comment]
Toukiden Kiwami show this:

err:   D3D11: CreateGeometryShaderWithStreamOutput: Rasterized stream not supported

**Comment by psy-q** [comment]
Nioh shows this as well.

**Comment by doitsujin** [comment]
They might *show* it, but I haven't seen a single game which actually requires the rasterization so far (it's not very useful anyway since it only supports points, not triangles). Apps can specify a rasterized stream but then choose not bind any render targets.

**Comment by psy-q** [comment]
Ah, thank you for clarifying. That's rather odd behavior from the games' side, then. I'll keep my hopes up for Nioh one day :)

**Comment by doitsujin** [comment]
afaik Nioh is being held back by wine issues.

**Comment by Scorpion2185** [comment]
I had the same error while playing Dead or Alive 6. 
https://github.com/ValveSoftware/Proton/issues/2420 
It seems that is this error that prevent me to play, other people can (except the story mode). 
`err:   D3D11: CreateGeometryShaderWithStreamOutput: Rasterized stream not supported`

**Comment by doitsujin** [comment]
> It seems that is this error that prevent me to play, other people can (except the story mode).

No, it isn't.

**Comment by Scorpion2185** [comment]
Why can't I play then?

**Comment by doitsujin** [comment]
Don't know?

**Comment by ap4y** [comment]
@doitsujin now that nioh semi-works I noticed weird issues with transparency effects and was wondering if it's related to stream rasterization? Mostly happens when things fade in/out, for example for the guardian spirit in the main menu when you press "Continue". I tried to capture it but it's not extremely obvious:

![2019-05-04-145451_3360x2560_scrot](https://user-images.githubusercontent.com/673861/57173048-3921e200-6e7d-11e9-928b-e0002aa784d1.png)

Basically transparent objects have a strange dot pattern on them. I don't have access to windows so I scanned through youtube videos and didn't notice it in [this video](https://www.youtube.com/watch?time_continue=321&v=49CZDxP8yNE):
 
![2019-05-04-150441_3360x2560_scrot](https://user-images.githubusercontent.com/673861/57173093-0af0d200-6e7e-11e9-9f2d-4ee46e446176.png)

Sorry if it's not the right place to post, please let me know if it will be better to track this as a separate issue.

**Comment by doitsujin** [comment]
No it's not related. If you think this is a bug, please record an apitrace and **then** open a new issue.

**Comment by psy-q** [comment]
@ap4y The effect is also there on Windows. There is a similar one when e.g. a door or other solid object is between your character and the camera, the closer it is the more it dissolves into dots.

**Comment by ap4y** [comment]
@psy-q ok, thanks for confirming that. it's not a big deal, just looks weird.
