### ISSUE TITLE
Skyrim: Special Edition Updated [21/1/2018]

### ISSUE THREAD

**Issue by mandruis** [doitsujin/dxvk#7]
# Software information

Skyrim: Special Edition using the lowest graphics settings with no aa or msaa the game starts perfectly but when you try to continue or create a new game you get a black screen
# System information

    Distro: Antergos
    GPU: R9 390
    Driver: Mesa git
    Wine version: wine-staging-2.21

# Apitrace file(s)

    From @skry https://mega.nz/#!lUdRGYZL!M9S5PdqZXGYaxuKaBlrwDZDsu26VrG4l1H92pgQ1N90

Log files
[d3d11.log](https://github.com/doitsujin/dxvk/files/1649984/d3d11.log)
[dxgi.log](https://github.com/doitsujin/dxvk/files/1649985/dxgi.log)

**Comment by XenonPK** [comment]
Similar results with Witcher 3 & Saints Row IV

**Comment by skry** [comment]
Without dxvk overrides Skyrim SE does not launch at all. With dxvk overrides, Skyrim SE main menu loads and loading a save works. Graphics in main menu and loading screen are OK. When loaded game should start I get black screen with environmental audio looping in background. Game does not seem to accept input or otherwise work. Wine staging 2.21, Mesa 17.3.2 and RX480.

[:/mnt … Skyrim Special Edition] $ cat d3d11.log 
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11Query: Unsupported query type 0
warn:  D3D11Query: Unsupported query type 0
warn:  D3D11Query: Unsupported query type 0
warn:  D3D11Query: Unsupported query type 3
warn:  D3D11Query: Unsupported query type 3
warn:  D3D11Query: Unsupported query type 3
warn:  D3D11Query: Unsupported query type 3
warn:  D3D11Query: Unsupported query type 3
warn:  D3D11Query: Unsupported query type 3
warn:  D3D11RasterizerState: Depth clamp not properly supported
err:   D3D11RasterizerState: Antialiased lines not supported
warn:  D3D11Query::GetData: Stub

[:/mnt … Skyrim Special Edition] $ cat dxgi.log
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled device extensions:
info:    VK_AMD_rasterization_order
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxgiFactory::MakeWindowAssociation: Ignoring flags
warn:  DxgiDevice::SetMaximumFrameLatency: Stub
info:  DxgiPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_MAILBOX_KHR
  Buffer size:  2560x1440
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT

**Comment by doitsujin** [comment]
Can you create a D3D11 apitrace so that I can test locally? The logs indicate that the game requires queries which aren't implemented yet, but most applications complaining about queries at least manage to render something.

**Comment by skry** [comment]
@doitsujin Unfortunately game stops (displays loading screen for few seconds before crashing) while loading when using apitrace:

warn:debugstr:OutputDebugStringA "apitrace: tracing to Z:\\mnt\\userhdd\\WinePrefixes\\skyrim\\drive_c\\Program Files\\Steam\\steamapps\\common\\Skyrim Special Edition\\SkyrimSE.2.trace\n"
apitrace: tracing to Z:\mnt\userhdd\WinePrefixes\skyrim\drive_c\Program Files\Steam\steamapps\common\Skyrim Special Edition\SkyrimSE.2.trace
warn:debugstr:OutputDebugStringA "error: unavailable function CreateDXGIFactory\n"
error: unavailable function CreateDXGIFactory

I launched it like this: wine apitrace-msvc/x64/bin/apitrace.exe trace --api dxgi -v ./SkyrimSE.exe
Trace file it creates is useless. Just let me know if I can do something differently or something else that would help.

**Comment by doitsujin** [comment]
@skry Some people reported that they had more success getting apitrace to work on Wine 3.0 compared to 2.21. In any case, make sure *not* to use DXVK when recording it.

**Comment by nairaner** [comment]
@skry DXGIFactory was commited to wine master after 3.0 release, so you can either compile master to see how it works or wait for wine 3.1

**Comment by doitsujin** [comment]
Thanks, the trace gives me something to work with.

**Comment by doitsujin** [comment]
To give you an update, the apitrace actually renders correctly for me, although the performance is absolutely abysmal for some reason. I've identified a potential issue with how the game uses depth buffers though.

If you are using mesa-git, please check the driver support page on the Wiki. Also, be aware that the shader compiler in mesa-git is insanely slow at the moment. I'm having similar issues with Homefront and Tomb Raider where compiling a single Vulkan pipeline can take up to eight seconds, compared to a few milliseconds with mesa 17.3.2. Not sure why this happens.

**Comment by dumpsters** [comment]
Not sure if this helps or is supported but I decided to try it on windows just for the hell of it, not sure if it even worked or not but had some artifacts in loading screen, in the distance (when in-game), crashes and stuff in the logs so I assume it did.
[SkyrimSE_d3d11.log](https://github.com/doitsujin/dxvk/files/1672350/SkyrimSE_d3d11.log)
[SkyrimSE_dxgi.log](https://github.com/doitsujin/dxvk/files/1672351/SkyrimSE_dxgi.log)
couple notes:

- had to rename d3d11_vk to d3d11, **duplicate** dxgi_vk and rename one of them to dxgi placing them in game root folder
- not duplicating dxgi caused "Adapter is not a DXVK adapter" in logs and game wouldn't launch
- trying to spin the loading screen model made the game crash
- both new game (w/ alternate start mod) and load game worked (new game froze 3 seconds after loading), managed to swing my axe a couple times and open inventory but turning the camera too much made it just freeze, didn't even crash just wouldn't respond at all
- couldn't alt tab at all

**Comment by mandruis** [comment]
Now it works

**Comment by TRPB** [comment]
Having switched from a 980Ti to a Radeon VII I am getting stuttering when moving between areas. I had initially attributed this to the shader cache being generated but even after loading the same area I get sutters when walking around despite a generally good framerate (60fps with occasional  dips down to 52 at 4k with everything maxed).
