### ISSUE TITLE
Nier Automata renders at selected resolution instead of 1600x900

### ISSUE THREAD

**Issue by Anti-Ultimate** [doitsujin/dxvk#722]
I'm sure you're aware of this, but Nier Automata always renders at 1600x900 and is then upscaled to whatever resolution you've selected.

However, DXVK always renders it at the resolution requested by the user, like FAR mod. I've noticed this when testing why DXVK performance was lower than Windows DX11. When set to 900p with DXVK, performance is very close.
This also happens when using DXVK on Windows, so it's not related to Wine.

~~When loading the game, it also freezes my DE (Gnome 3.30) whenever the initial loading screen is finished and it proceeds to the start menu. Does not happen on WineD3D nor Windows with DXVK.~~
This is gone now, I have no idea why.

### Software information
Nier Automata, settings don't matter.

### System information
- GPU: NVIDIA GTX 970
- Driver: 396.54.09
- Wine version: Proton 3.16-3 (replaced DXVK with newest version)
- DXVK version: v0.90-10-g5124fd8 (latest commit as of this date)

I think the option to have DXVK override what the game renders at would be nice, but the default behaviour should be to do whatever DX11 does.

**Comment by doitsujin** [comment]
No, the game **doesn't** render at 1600x900.

On Windows, the game is rendered at your monitor's resolution, then downscaled to a lower resolution because the display mode selection in their engine is broken, and then upscaled again. The reason it works on DXVK is because DXGI reports display modes slightly differently than native Windows.

Performance is known to be extremely low on Nvidia hardware in this game, there's nothing you can do about it except hope for a driver update. FWIW my RX 480 runs the game with a constant 60 FPS at 1080p.

**Comment by Anti-Ultimate** [comment]
That's even more scuffed than I had anticipated. I thought they had the game render at 900p intentionally. 

If this is intended behaviour I'll just close this.
