### ISSUE TITLE
Affinity Designer crash when creating an empty document

### ISSUE THREAD

**Issue by workless** [doitsujin/dxvk#785]
Affinity Designer rely heavily on D3D10 Effects which are not currently implemented.
It fails with with undefined 'D3D10StateBlockMaskEnableAll', i tried to add a stub but after that it actually tries to use effects framework and crash anyway.
The standard implementation of wine implements somewhat the effect framework but it crash due to multiple buffer swapping not being supported (i think at least).
Also the whole ui is correctly rendered on dxvk while it is not in the standard wine impl.

https://affinity.serif.com/en-us/designer/
https://affinity.store/download/aea673/

**Comment by doitsujin** [comment]
I have no intention to support the Effects API. It doesn't see much use in games, documentation is terrible, and in general it's just a horrible mess that should't even exist. And since it resides in one of the DLLs that DXVK overrides, it can't rely on wine's implementation either (which would probably work just fine actually).
