### ISSUE TITLE
Only with Winelib DXVK build World of Warcraft don't run without dxgi override, but works fine with it.

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#875]
Hi, @doitsujin ! Thank you for your the great work!

__________

An attempt to run the game ends in a game crash.
![screenshot from 2019-01-21 13-49-46](https://user-images.githubusercontent.com/36989404/51464319-1d3f7800-1d87-11e9-8b5a-eed730028587.png)
But the game works well if I add the dxgi override.

### Software information
World of Warcraft

### System information
- OS: Arch Linux, Linux 4.20.3.
- GPU: AMD Radeon HD7850
- Driver: AMDGPU, Mesa freshest git [0a793c78](https://gitlab.freedesktop.org/mesa/mesa/commit/0a793c78a35ecadad088e34fcc1088f5126e636d)
- Wine version: Wine Staging 4.0-rc7
- DXVK version: cfc3f68

### Apitrace file(s)
- I can't get apitrace because the game don't start.

### Log files
- [wow-wine-dxvk-terminal-output.txt](https://github.com/doitsujin/dxvk/files/2778317/wow-wine-dxvk-terminal-output.txt)

- d3d11.log: [Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/2778315/Wow_d3d11.log)

- dxgi.log: for some unknown reason it was not created during the launch of the game.

**Comment by doitsujin** [comment]
> dxgi.log: for some unknown reason it was not created during the launch of the game.

dxgi.log doesn't get created because you're not even using DXVK's DXGI implementation.

In theory this should work fine, no idea why it doesn't work for WoW. Your terminal output doesn't even mention a crash so it's basically impossible to figure out *where* it crashes based on that.

**Comment by pga256** [comment]
I have WoW working on Nvidia 415.22.05, Arch linux 4.20.3  and there is no DXGI override present.  Using dxvk-git-0.95.r12.g8cc4497f-1.  
Perhaps this is just an issue on AMD / mesa, though I suspect others would be reporting this by now if that were the case.

**Comment by doitsujin** [comment]
@Kerrung can you please test this with latest `master`? #878 fixes an issue with DXVK when using wine's DXGI, I wonder if this was the same problem.

**Comment by SveSop** [comment]
@Kerrung Could you post a snippit of the `WoW/_retail_/Logs/gx.log` file?

**Comment by Kerrung** [comment]
@SveSop 
[gx.log](https://github.com/doitsujin/dxvk/files/2784069/gx.log)

**Comment by Kerrung** [comment]
@doitsujin unfortunately nothing has changed for me with b1540a1:
![screenshot from 2019-01-22 23-38-58](https://user-images.githubusercontent.com/36989404/51557604-376c7980-1e9f-11e9-861f-f7d21d6dea3e.png)

**Comment by doitsujin** [comment]
Can you run it with `WINEDEBUG=dxgi` and post the output?

**Comment by SveSop** [comment]
Would not happen to have built this as a winelib by any chance @Kerrung ?

**Comment by Kerrung** [comment]
>Would not happen to have built this as a winelib by any chance @Kerrung ?

@SveSop but I already using the [AUR winelib version](https://aur.archlinux.org/packages/dxvk-git)

![screenshot from 2019-01-23 00-50-11](https://user-images.githubusercontent.com/36989404/51561376-dba6ee00-1ea8-11e9-8258-7b1a4ea3fc03.png)

**Comment by SveSop** [comment]
WoW does not work with a winelib build i am afraid.
[https://github.com/doitsujin/dxvk/issues/706#issuecomment-442926314](https://github.com/doitsujin/dxvk/issues/706#issuecomment-442926314)

I kinda gave up on getting that working with WoW. Not sure why it doesnt, but i suscpect one of two things: 1. Possibly some "warden" (hack protection thing), or 2. Some strange thing with msvcrt missing when you cant build as a "static library" (winegcc does not support -static flag).

**Comment by Kerrung** [comment]
@doitsujin 
>Can you run it with WINEDEBUG=dxgi and post the output?

[wow-WINEDEBUG_dxgi.txt](https://github.com/doitsujin/dxvk/files/2784385/wow-WINEDEBUG_dxgi.txt)

**Comment by Kerrung** [comment]
>WoW does not work with a winelib build i am afraid.

@SveSop WoW works fine with this winelib DXVK build when DXVK's dxgi overridden.

**Comment by doitsujin** [comment]
Please try a mingw build anyway. WoW does have some weird behaviour related to loading the D3D11/DXGI libraries.

**Comment by Kerrung** [comment]
>Please try a mingw build anyway. WoW does have some weird behavior related to loading the D3D11/DXGI libraries.

I am not able to build a mingw git master build by myself because in AUR there is only a winelib dxvk-git package. Any ideas?

**Comment by SveSop** [comment]
@Kerrung Well.. have you verified that you actually are using dxvk when doing that? With eg. `export DXVK_HUD=fps` or something? So that it is not some strange fallback to winelib d3d11 or some shit :)

I have not tested this in a while tho, but will do just for lulz and giggles, cos there has been quite a few updates to dxvk since i did this last. (Been using vkd3d w/D3D12). Gimme a few min, and ill double check that it works for me then.

**Comment by doitsujin** [comment]
@Kerrung just download the 0.95 release.

**Comment by Kerrung** [comment]
>just download the 0.95 release.
Ok. Just give me time to do it, please...

**Comment by SveSop** [comment]
Same problem with winelib and WoW still. `Fatal exeption` and `GxDeviceD3d11::ILoadD3dLib(): unable to LoadLibrary("dxgi.dll")` in the WoW gx.log.

**Comment by SveSop** [comment]
Probably rude to ask... but you did check that the wineprefix symlinks does not point to non-existing dll.so files? :)
eg. `$HOME/your_wine_prefix/drive_c/windows/system32/d3d11.dll` point to the downloaded d3d11.dll and not dll.so :)

**Comment by Kerrung** [comment]
@SveSop I have restarted the script supplied with this package, which automatically creates links or overwrites them if they previously existed. But if you want, then I can completely delete the WINEPREFIX/windows folder to re-create it and re-run this script.

**Comment by SveSop** [comment]
Nah, its enough that you do a `ls -asl d3d1*` inside the `prefix/drive_c/windows/system32` folder. You will see what the links are then :)

**Comment by Kerrung** [comment]
@SveSop 
![screenshot from 2019-01-23 01-50-56](https://user-images.githubusercontent.com/36989404/51564545-668be680-1eb1-11e9-86b5-dc752d56c822.png)

**Comment by SveSop** [comment]
Looks right to me @Kerrung . Guess its up to @doitsujin to figure out more once you post some logs from dxgi/d3d11 for him with the working mingw-w64 build of dxvk. (Cos it IS working for most ppl)

**Comment by Kerrung** [comment]
>Looks right to me @Kerrung . Guess its up to @doitsujin to figure out more once you post some logs from dxgi/d3d11 for him with the working mingw-w64 build of dxvk.

@SveSop  but unfortunately, during such an attempt to start the game, no logs are created in the folder with Wow.exe.  I remind you that I still use the [dxvk 0.95 release version](https://github.com/doitsujin/dxvk/releases/tag/v0.95) .
![screenshot from 2019-01-23 01-58-34](https://user-images.githubusercontent.com/36989404/51564930-68a27500-1eb2-11e9-9753-f5c6b82739d7.png)

**Comment by Kerrung** [comment]
@SveSop  with DXVK_LOG_LEVEL=debug
[DXVK_LOG_LEVEL-debug_WoW.txt](https://github.com/doitsujin/dxvk/files/2784619/DXVK_LOG_LEVEL-debug_WoW.txt)

**Comment by Kerrung** [comment]
@SveSop I use the [setup_dxvk_aur.verb](https://github.com/doitsujin/dxvk/files/2784693/setup_dxvk_aur.zip) script to automatically create symlinks and Wine overrides. This script ships with the  [AUR dxvk-bin package](https://aur.archlinux.org/packages/dxvk-bin/)

**Comment by SveSop** [comment]
Hmm.. I wonder how dependent the winelib d3d11.dll.so is of d3dcompiler_47.dll?
```
005a:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\d3dcompiler_47.dll" at 0x6bb50000: builtin
005a:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\d3dcompiler_47.dll" : builtin
005a:trace:loaddll:load_native_dll Loaded L"C:\\Program Files (x86)\\Blizzard App\\Battle.net.10904\\d3dcompiler_47.dll" at 0x15810000: native
005a:trace:loaddll:free_modref Unloaded module L"C:\\Program Files (x86)\\Blizzard App\\Battle.net.10904\\d3dcompiler_47.dll" : native
```
```
lib_d3dcompiler_43 = declare_dependency(link_args: [ '-L'+dxvk_library_path, '-ld3dcompiler_43' ])
  lib_d3dcompiler_47 = declare_dependency(link_args: [ '-ld3dcompiler' ])
```
vs. mingw-w64 build:
```
lib_d3dcompiler_43 = dxvk_compiler.find_library('d3dcompiler_43', dirs : dxvk_library_path)

  if dxvk_compiler.get_id() == 'msvc'
    lib_d3dcompiler_47 = dxvk_compiler.find_library('d3dcompiler')
  else
    lib_d3dcompiler_47 = dxvk_compiler.find_library('d3dcompiler_47')
  endif
```
Nah.. ill go to bed now :) (Before i toss out any more ramblings that makes no sense...)

**Comment by SveSop** [comment]
@Kerrung The script i posted is for actually starting World of Warcraft...

**Comment by Kerrung** [comment]
@SveSop but I don't use any script to start wow. I just enter the command:
#### env WINEPREFIX=/home/user/.wine wine64 start /unix '/home/user/.wine/drive_c/Program Files (x86)/World of Warcraft/_retail_/Wow.exe'

**Comment by Kerrung** [comment]
Yesterday I was unable to launch the game in the same configuration because I did not create DXVK symlinks to 32bit libraries, but today I was able to run WoW using the official 0.95 release build, without dxgi override.
But the winelib version of WoW is still not working.

**Comment by SveSop** [comment]
Tested winelib build with no dxgi.dll override, and the problem is the same (for me). But i might have found something weird with vulkan-1.dll perhaps? 
What happens is that with `DXVK_HUD=fps` is that the hud is shown on the battle.net client window, but it HAS crashed, cos the fps counter does not update until you move the mouse over buttons or similar. The comparison between a non-working winelib build and a working mingw-w64 build with `+loaddll` wine debug option is this:

`cat winelog.log | grep -i vulkan`
```
0039:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7c450000: builtin
info:    Vulkan: 1.1.96
info:    Vulkan: 1.1.96
005b:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7b950000: builtin
info:    Vulkan: 1.1.96
00a1:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7bda0000: builtin
00a6:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7c430000: builtin
0097:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7be40000: builtin
info:    Vulkan: 1.1.96
info:    Vulkan: 1.1.96
info:    Vulkan: 1.1.96
00fa:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7c060000: builtin
0112:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7c060000: builtin
info:    Vulkan: 1.1.96
0112:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\vulkan-1.dll" at 0x7a6b0000: builtin
0112:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\vulkan-1.dll" : builtin
012c:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7fc119830000: builtin
info:    Vulkan: 1.1.96
012c:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\winevulkan.dll" : builtin
```
The lines with Vulkan: 1.1.96 is from dxvk, but to ME it seems they indicate some sort of crash/unable to actually load. In correlation with this, i also get:
```
warn:  D3D11DeviceContext::QueryInterface: Unknown interface query
warn:  D3D11DeviceContext::QueryInterface: Unknown interface query
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
```
Clearly dxvk is not loaded/active, ref the "Unknown interface query".

This is a working mingw-w64 snippit:
`cat winelog.log | grep -i vulkan`
```
0038:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\vulkan-1.dll" at 0x7c6b0000: builtin
0038:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7c440000: builtin
005a:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\vulkan-1.dll" at 0x7bd80000: builtin
005a:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7bb50000: builtin
005a:fixme:vulkan:wine_vk_device_convert_create_info Application requested a linked structure of type 0x3b9db032.
005a:fixme:vulkan:wine_vk_device_convert_create_info Application requested a linked structure of type 0x3b9b3760.
00a1:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\vulkan-1.dll" at 0x7bec0000: builtin
00a1:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\winevulkan.dll" at 0x7be80000: builtin
```
"Application requested a linked..." indicates to ME that dxvk is loaded and "responding". Notice that it is no dxvk log-info here (no `info:    Vulkan: 1.1.96`). There is no "Unknown interface query" either.

Anyone wanna give another stab at this with a tracelog from wine perhaps? Seeing of there is something crashing?

1. Winelib build works with loads of d3d11 games, so it cant be a "general fault".
2. Winelib build of dxvk does NOT support the "static" linking you can do to libraries in a mingw-w64 build. Is vulkan-1.lib linked more "correctly" vs. the wine version of libvulkan-1? Dunno.. See #1, cos one would think other games would fail aswell..
3. Winelib build of d3d11/d3d12 works fine with WoW if you use wined3d/vkd3d, so its not a general "winelib" problem with WoW.

The solution is probably some simple crap.. something missing. I have tried to do some adding of `lib_vulkan  = declare_dependency(link_args: [ '-lvulkan-1', '-lwinevulkan' ])` and stuff like that to perhaps try to link something that is missing.. Even tried creating a d3dcompiler_47.def file and linking that in the same way d3dcompiler_43 is linked.. to no avail.

Someone with WoW and some idea are welcome to try :)

**Comment by Kerrung** [comment]
>Someone with WoW and some idea are welcome to try :)

I do not have any new ideas, but I am very interested to know what @doitsujin  will say to this.

**Comment by doitsujin** [comment]
Not much, WoW is essentially a black box to me and I just don't know how to debug something like this.

**Comment by SveSop** [comment]
I think its bound to be some kind of library that is needed, that most other stuff do not require.. For all i know WoW could have its own c++ library baked in somewhere, and since we cant just like the needed c++ library statically like the mingw-w64 build seems to do, it goes tits up on some weird function?

Plenty of 
```
005b:fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 2
00fa:fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 2
00fa:fixme:msvcp:_Mtx_init_in_situ unknown flags ignored: 1
```
stuff in that WoW log aswell (this is obviously non-implemented things in wine's msvcp tho). Just tossing ideas around, since the most glaring difference between the mingw-w64 and the winelib build is `'-static-libgcc', '-static-libstdc++'`. And as mentioned before: winelib/winegcc does not seem to support the --static flag when linking. (For all i know, might be outdated info on the winehq man pages tho?)

**Comment by SveSop** [comment]
Building dxvk without `'-static-libgcc', '-static-libstdc++'` gives no errors, but then the mingw-w64 version does not work. So it is obviously required.
It is mentioned someplace that mingw-w64 builds with the `'-mno-cygwin'` flag by default? But does it do that?

Adding this makes the winelib version not compile, and i would guess it is due to some headers that wine uses is not compatible with dxvk. (cpp). So, since you cannot build with `'-mno-cygwin'`, and winegcc does not support `'-static'` linking the libs the mingw-w64 version does.. Could this be something problematic perhaps?

**Comment by davvvve1** [comment]
Have you all dependencis installed ? https://github.com/lutris/lutris/wiki/How-to:-DXVK

**Comment by Kerrung** [comment]
>Have you all dependencis installed ? https://github.com/lutris/lutris/wiki/How-to:-DXVK

@davvvve1 look here: https://github.com/lutris/lutris/wiki/How-to:-DXVK#arch--antergos--manjaro--other-arch-derivatives
I still use Arch Linux, and yes, all dependencies are installed, thank you.

**Comment by SveSop** [comment]
This seems to work with WoW 8.1.5 and the "new" d3d11 engine.
From the /World of Warcraft/_retail_/Logs/gx.log it seems to use D3D11.1
```
3/16 17:35:33.486  Format 1920 x 1080 Fullscreen, ArgbX888, vsync 0
3/16 17:35:33.545  Taking Adapter by name:"NVIDIA GeForce GTX 970"
3/16 17:35:33.548  Detected NvAPI and checking if it's valid...
3/16 17:35:33.578  Created 11.1 Device
```
I tested this with installing `./setup_dxvk.sh install --without-dxgi --symlink` and wine-4.4 with staging-
6c37563f924b8b268f779725322ebe387c65b8cf

If anyone want to revisit this test for WoW 8.1.5 and confirm that would be nice.

**Comment by Kerrung** [comment]
Thank you! It woks fine now! So, I close this issue.
