### ISSUE TITLE
Async Compute

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#912]
Hello. Is Primitive Culling via Async Compute a valid option? Also is there an option for as users to add general advice for novice users inside the DXVK webpage?

**Comment by Joshua-Ashton** [comment]
> Also is there an option for as users to add general advice for novice users inside the DXVK webpage?

What does this even mean? The documentation is fine on the README -- it's very straightforward.

**Comment by SveSop** [comment]
@artivision [https://github.com/doitsujin/dxvk/wiki](https://github.com/doitsujin/dxvk/wiki)
Lots of useful information there. Some might be a wee bit outdated, but should be able to get you going when USING dxvk (if that was what you meant).

**Comment by doitsujin** [comment]
> Hello. Is Primitive Culling via Async Compute a valid option?

I assume you are referring to the new primitive culling feature in RadeonSI. While it's technically not *impossible* to implement this in DXVK, the RadeonSI implementation is highly complex and has to cover a lot of use cases, and when translating that to Vulkan, there are limitations:

- Using async compute for *anything* is basically not an option right now due to strict synchronization requirements. Doing all the necessary state tracking would increase CPU overhead.
- Primitive ordering cannot be guaranteed since Vulkan does not expose GDS.
- RadeonSI patches the command buffer, whereas DXVK would have to resort to indirect draws. Not an issue per se, but this would increase complexity rather significantly.

And more importantly, it hasn't been shown to have any impact on games yet. I can imagine that some would benefit, but your typical game is significantly heavier on fragment shading than on geometry processing, so the impact will be limited.

> Also is there an option for as users to add general advice for novice users inside the DXVK webpage?

If you're asking me to open up the wiki to everyone, then no, won't happen. If there's anything specific you would like to have added, open an issue about it.

**Comment by artivision** [comment]
Hm OK, but it's not impossible to ask the Vulkan group for changes (i think). Anyway thank you.

**Comment by artivision** [comment]
Also back the the thinking was to compile pert of that that Vertex Program to "Async" Compute Shaders (automatically). Did this change somehow and now this is a core future?

**Comment by K0bin** [comment]
> Hm OK, but it's not impossible to ask the Vulkan group for changes (i think). Anyway thank you.

Please don't annoy Khronos when you have absolutely no idea what you're talking about.

> Also back the the thinking was to compile pert of that that Vertex Program to "Async" Compute Shaders (automatically). Did this change somehow and now this is a core future?

None of that makes sense.

**Comment by doitsujin** [comment]
> None of that makes sense.

Vertex shaders *are* translated to compute shaders to perform culling, but not "automatically" and it is also not a "core f**u**ture" (i guess the word of choice there is "feature").

**Comment by doitsujin** [comment]
According to [this tweet](https://twitter.com/phoronix/status/1095825661556654080) from Michael Larabel, primitive culling doesn't seem to have any impact on games.
