### ISSUE TITLE
Advice for novice users to improve performance.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#915]
1) Disable compositor or unredirect for full screen windows. Example, write to **compton.conf**: **unredir-if-possible = true;**

2) If your monitor is fast like 144Hz and your Gpu cannot fill even half of this on a specific game, then create a **dxvk.conf** inside the folder with the game.exe and write **dxgi.syncInterval = 2**.

3) If you have two Vulkan Gpus then add to your **.bashrc** something like: **export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json**, then update bashrc or reboot. Or just remove Intel Vulkan from your package manager.

4) Open the game's hyperlink and add **WINEESYNC=1** after **env**, usually your Wine build support this, if not find some other repository that does.

5) Also additions like **WINEDEBUG=-all** and **DXVK_LOG_LEVEL=none** might help, especially when there is error spamming.

6) Disable **TearFree** (if its on).

**Comment by doitsujin** [comment]
1. Not everyone uses compton, and the DXVK wiki is not the Compoton wiki.
2. That doesn't improve performance.
3. This is **really** terrible advice as it will prevent you from using different Vulkan drivers without edinting .bashrc.
4. Esync is already mentioned in the wiki. I have absolutely no clue what you mean by "opening a game's hyperlink".
5. Fair enough.

**Comment by artivision** [comment]
For 1: Compton and XFCEs compositors both destroy DXVK.
For 2: 40Fps on a 144Hz monitor tremble because of empty Hz. Good if you start developing on a 
          144Hz monitor, its not the same.
For 3: If you remove Intel Vulkan on a laptop, Hainan for example works by default. But ok if you need 
          it.

**Comment by doitsujin** [comment]
1. That's why the Wiki tells you to disable desktop effects. *It is already there*, no need for overly specific instructions. Proton also uses compositor bypass by default for fullscreen games; if Compton does not respect it, you should file a Compton bug.
2. There's nothing special about 144 Hz monitors in that regard. 40 FPS on 60Hz also won't deliver an ideal experience.
3. Telling people to set `VK_ICD_FILENAMES` in .bashrc is insane, end of discussion. It might be an acceptable solution for you, but that doesn't mean that users who probably don't even know what it does / have multiple drivers installed / want to use their Intel GPUs for something other than DXVK should do it, and telling them to do it is harmful at best.

**Comment by artivision** [comment]
OK removed.
