### ISSUE TITLE
Inbuilt Tracing Support

### ISSUE THREAD

**Issue by StinkyAnimeGirl** [doitsujin/dxvk#943]
Hiii! ^-^

I was wondering if there was ever going to be plans to bring in in-built tracing support into DXVK.
Akin to Wine and other translation layers.

I do realise apitrace exists but it has its own issues and it takes a while to try and debug an issue with it.
If the tracing was in-built, a trace of the last 100 or so calls could be spewed, allowing the tracking of incorrect behaviour.

This would also allow tracking of different paths that get taken when DXVK is used, as sometimes apitrace produces different results which works which makes issues like this harder to debug.

Thanks
🌳

**Comment by doitsujin** [comment]
This was asked before, but I can't find the issue anymore (thanks github search for being crap), so I'll recite my arguments against this:

I'm aware that apitrace doesn't always work, but it's simply the best thing we have since it offers a way to **replay** captured traces. Regarding "built-in" support for tracing (or rather, logging):
- it's a large effort to implement and makes the code less maintainable
- it either has an inherent performance impact, which is unacceptable, or it's disabled in release builds, which makes it... pretty much useless unless you compile DXVK yourself.
- it's just *not useful*. Seeing D3D11 commands on the console is generally *not useful* it you cannot repeat the process.
- Just logging D3D11 commands doesn't tell you anything if it's the backend that screws up. And it's usually the backend that screws up.
