### ISSUE TITLE
DXVK: v1.0-11-ga40d8d4 DxvkInstance: Failed to create instance Linux 5.0 AMDGPU

### ISSUE THREAD

**Issue by ashleysommer** [doitsujin/dxvk#954]
### Description
- I was using Wine with DXVK a couple of weeks ago to play some DX11 windows games without problem.
- Yesterday I upgraded to the new Linux Kernel version (5.0) with built-in AMDGPU kernel driver.
- And last night I upgraded Mesa to the latest release from the Padoka PPA.
- I Played some native Linux Vulkan games without issue.
- Today downloaded and installed the latest DXVK [v1.0-11-ga40d8d4 from the buildserver here](https://haagch.frickel.club/files/dxvk/r2011.a40d8d4/).
- DXVK thinks the system Vulkan is broken. (See Attached wine output and Logs)
- Vulkaninfo output is normal: [vulkaninfo](https://gist.github.com/ashleysommer/e3a775342224036d4d814e0e4bc6f71a#file-vulkaninfo)
- Linux Native Vulkan games start without issue.

### Software information
Affects all dx11 and dx10 games in Wine.
Affects both wine64 and wine32.

### System information
- GPU: AMD R7 260x
- Driver: Mesa 19.1 Padoka (RADV vulkan driver)
- Wine version: 3.20-Staging
- DXVK version: 1.0-11-ga40d8d4

### Wine output
[wine output](https://gist.github.com/ashleysommer/e3a775342224036d4d814e0e4bc6f71a#file-wine-output)

### Log files
- d3d11.log: [d3d11.log](https://gist.github.com/ashleysommer/e3a775342224036d4d814e0e4bc6f71a#file-infra_d3d11-log)
- dxgi.log: [dxgi.log](https://gist.github.com/ashleysommer/e3a775342224036d4d814e0e4bc6f71a#file-infra_dxgi-log)

Possibly related to: https://github.com/doitsujin/dxvk/issues/931 ? But I'm not using the AUR package.

**Comment by ashleysommer** [comment]
I just tried downgrading to the previous build on the buildserver, v1.0-7-gd011102 seeing the same issue.

**Comment by ashleysommer** [comment]
Resolution:
I found that package `mesa-vulkan-drivers:i386` was not installed on my system (had been removed at some point previously).
VulkanInfo was working correctly because it is a 64-bit executable. But I guess these games I'm testing are all 32-bit, and required the 32bit version of the vulkan drivers.

**Comment by DwarfFighterCleric** [comment]
Thank you so much for sharing! That was the trick for my Dxvk to start working inside Wine too!  
  
Just in case anyone else is having problems with installing Vulkan/DxVk I will write down here the packages that I've installed, I performed manual installation, I didn't use any automated scripts.  
(procedure done on MX Linux which comes with custom updated Debian repositories, no need to add 3rd party repositories manually, they're already there... for other distros you will need additional manual steps)  
  
sudo apt-get install libvulkan1 libvulkan-dev vulkan-utils
sudo apt-get install mesa-vulkan-drivers
sudo apt-get install dxvk
sudo apt-get install lutris
winetricks dxvk
sudo apt-get install mesa-vulkan-drivers:i386

With these packages installed I got The Sims 1: Complete Edition to work, in combination with dgVoodoo2. dgVoodoo2 is required to translate the Directx8 calls into Directx11, and then Dxvk translates Dx11 into OpenGL.
**Additional required step:**
In order for dgVoodoo2 to get activated inside of Wine, you need to copy the dgvoodoo DLL files into the game folder, and then run winecfg, create Library override for ddraw.dll (native, builtin) dgVoodoo also gives you the option to run the game windowed, so you will know when dgvoodoo is properly working, there's also a watermark logo in the bottom right corner when it's activated.

Note:
Families previously created that had the "no textures" problem (also known as "white sims") will remain with that problem. The Sims will be rendered correctly on the screen but their portraits are still white. You will need to create a new family or reset the game entirely in order to get rid of that problem.
